#!/usr/bin/env node
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const bridgeRoot = join(repo, 'assets', 'blender', 'bridge')
const outPath = join(repo, 'src', 'services', 'blender', 'bridgeFiles.generated.ts')

function walk(dir) {
  const out = []
  for (const name of readdirSync(dir)) {
    if (name === '__pycache__') continue
    const p = join(dir, name)
    if (statSync(p).isDirectory()) out.push(...walk(p))
    else if (!name.endsWith('.pyc')) out.push(p)
  }
  return out
}

let files
try {
  files = walk(bridgeRoot)
    .map(p => ({ path: relative(bridgeRoot, p).split('\\').join('/'), content: readFileSync(p, 'utf8') }))
    .sort((a, b) => (a.path < b.path ? -1 : 1))
} catch {
  console.error(`regen-bridge: no add-on sources at ${bridgeRoot}`)
  process.exit(1)
}
if (files.length === 0) {
  console.error('regen-bridge: add-on dir is empty — nothing to embed')
  process.exit(1)
}

const h = createHash('sha256')
for (const f of files) h.update(f.path).update('\0').update(f.content).update('\0')
const digest = h.digest('hex')

const generated = `// GENERATED by scripts/blender-bridge/regen-bridge.mjs from assets/blender/bridge/ — DO NOT EDIT.
// Regenerate: node scripts/blender-bridge/regen-bridge.mjs   (drift-gated by --check in scripts/blender-bridge/)

export interface BlenderBridgeFile {
  /** Path relative to the user addon home (carries the mercury_blender_bridge/ prefix). */
  path: string
  content: string
}

export const BLENDER_BRIDGE_DIGEST = '${digest}'

export const BLENDER_BRIDGE_FILES: readonly BlenderBridgeFile[] = ${JSON.stringify(files, null, 2)}
`

const KEEP_HASH_COMMENT = /^\s*#\s*(!|-\*-|gate-(class|watch|env|inputs):|shellcheck|type:|noqa|pragma|pylint|fmt:|ruff:|mypy:|flake8:)/

function commentFreeProjection(pythonSource) {
  const lines = pythonSource.split('\n')
  const out = []
  let quote = null
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    let cut = -1
    let j = 0
    while (j < line.length) {
      const ch = line[j]
      if (quote !== null) {
        if (ch === '\\') {
          j += 2
          continue
        }
        if (line.startsWith(quote, j)) {
          j += quote.length
          quote = null
          continue
        }
        j++
        continue
      }
      if (ch === '"' || ch === "'") {
        const triple = line.slice(j, j + 3)
        quote = triple === '"""' || triple === "'''" ? triple : ch
        j += quote.length
        continue
      }
      if (ch === '#') {
        cut = j
        break
      }
      j++
    }
    if (quote !== null && quote.length === 1) quote = null
    if (cut === -1) {
      out.push(line)
      continue
    }
    const comment = line.slice(cut)
    const keep = KEEP_HASH_COMMENT.test(comment) || (i === 0 && comment.startsWith('#!')) || comment.includes('-*- coding')
    if (keep) {
      out.push(line)
      continue
    }
    if (line.slice(0, cut).trim() === '') continue
    out.push(line.slice(0, cut).replace(/\s+$/, ''))
  }
  const joined = out.join('\n').replace(/\n{4,}/g, '\n\n\n')
  return joined.endsWith('\n') ? joined.replace(/\n+$/, '\n') : joined
}

function embeddedFilesOf(moduleText) {
  const marker = 'export const BLENDER_BRIDGE_FILES: readonly BlenderBridgeFile[] = '
  const at = moduleText.indexOf(marker)
  if (at === -1) return null
  try {
    return JSON.parse(moduleText.slice(at + marker.length))
  } catch {
    return null
  }
}

function embeddedMatchesPublishedProjection(moduleText) {
  const embedded = embeddedFilesOf(moduleText)
  if (!Array.isArray(embedded) || embedded.length !== files.length) return false
  return files.every((onDisk, i) => {
    const e = embedded[i]
    if (!e || e.path !== onDisk.path) return false
    if (!onDisk.path.endsWith('.py')) return e.content === onDisk.content
    return commentFreeProjection(onDisk.content) === onDisk.content && commentFreeProjection(e.content) === onDisk.content
  })
}

if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(outPath, 'utf8')
  } catch {
    console.error('regen-bridge --check: generated module missing — run the regen')
    process.exit(1)
  }
  if (current !== generated && !embeddedMatchesPublishedProjection(current)) {
    console.error('regen-bridge --check: DRIFT between assets/blender/bridge/ and bridgeFiles.generated.ts — run: node scripts/blender-bridge/regen-bridge.mjs')
    process.exit(1)
  }
  console.log(`regen-bridge --check: clean (${files.length} files, digest ${digest.slice(0, 12)}…)`)
  process.exit(0)
}

writeFileSync(outPath, generated)
console.log(`regen-bridge: wrote ${outPath} (${files.length} files, digest ${digest.slice(0, 12)}…)`)
