#!/usr/bin/env node
// regen-bridge — assets/blender/bridge/** → src/services/blender/bridgeFiles.generated.ts
// (the unity regen-bridge grammar; `--check` drift-gates the blender-bridge
// suite). The Python add-on ships INSIDE the single-file bundle as SOURCE —
// it never runs here (runs-in-Blender is the written Mac drill);
// blender_bridge_install materializes it into the user addon home. Paths
// are relative to assets/blender/bridge/, so they carry the
// mercury_blender_bridge/ module prefix and land path-for-path in the
// addon home. Deterministic: files sorted, digest over the sorted
// (path, content) stream; __pycache__/.pyc never ship.
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const bridgeRoot = join(repo, 'assets', 'blender', 'bridge')
const outPath = join(repo, 'src', 'services', 'blender', 'bridgeFiles.generated.ts')

function walk(dir) {
  const out = []
  for (const name of readdirSync(dir)) {
    if (name === '__pycache__') continue
    const p = join(dir, name)
    if (statSync(p).isDirectory()) out.push(...walk(p))
    else if (!name.endsWith('.pyc')) out.push(p)
  }
  return out
}

let files
try {
  files = walk(bridgeRoot)
    .map(p => ({ path: relative(bridgeRoot, p).split('\\').join('/'), content: readFileSync(p, 'utf8') }))
    .sort((a, b) => (a.path < b.path ? -1 : 1))
} catch {
  console.error(`regen-bridge: no add-on sources at ${bridgeRoot}`)
  process.exit(1)
}
if (files.length === 0) {
  console.error('regen-bridge: add-on dir is empty — nothing to embed')
  process.exit(1)
}

const h = createHash('sha256')
for (const f of files) h.update(f.path).update('\0').update(f.content).update('\0')
const digest = h.digest('hex')

const generated = `// GENERATED by scripts/blender-bridge/regen-bridge.mjs from assets/blender/bridge/ — DO NOT EDIT.
// Regenerate: node scripts/blender-bridge/regen-bridge.mjs   (drift-gated by --check in scripts/blender-bridge/)

export interface BlenderBridgeFile {
  /** Path relative to the user addon home (carries the mercury_blender_bridge/ prefix). */
  path: string
  content: string
}

export const BLENDER_BRIDGE_DIGEST = '${digest}'

export const BLENDER_BRIDGE_FILES: readonly BlenderBridgeFile[] = ${JSON.stringify(files, null, 2)}
`

if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(outPath, 'utf8')
  } catch {
    console.error('regen-bridge --check: generated module missing — run the regen')
    process.exit(1)
  }
  if (current !== generated) {
    console.error('regen-bridge --check: DRIFT between assets/blender/bridge/ and bridgeFiles.generated.ts — run: node scripts/blender-bridge/regen-bridge.mjs')
    process.exit(1)
  }
  console.log(`regen-bridge --check: clean (${files.length} files, digest ${digest.slice(0, 12)}…)`)
  process.exit(0)
}

writeFileSync(outPath, generated)
console.log(`regen-bridge: wrote ${outPath} (${files.length} files, digest ${digest.slice(0, 12)}…)`)
