// ============================================================================
//  capability/declarations — the ratified capability constitution for the
//  EXISTING tool estate. One reviewable table, keyed by
//  canonical tool name; the ONE read seam is declaredCapability() in
//  contract-read.ts (an inline Tool.capability declaration WINS over this
//  table — new tools self-describe; this table backfills the estate).
//
//  Every entry is a CLAIM with a mechanical cross-check
//  (scripts/builtin-tools/prove-builtin-tools-constitution.ts + prove-builtin-tools-census.ts):
//    gate        → must exist in flagRegistry
//    execution   → kind must be classified in EXECUTION_DOMAIN_CENSUS
//    transaction → receipt kinds must be in the receipt operation vocabulary
//    resources   → kinds must be registered resource adapters
//    operations  → must match the tool's own zod op vocabulary exactly
//
//  Declaration honesty:
//    · transaction is declared ONLY where mutations actually settle through
//      the change-receipt / transaction-plane seam today;
//    · execution is declared ONLY for tools whose running work is on the
//      execution plane (executionCensus classifications);
//    · resources are the mercury:// kinds the tool PRODUCES or addresses;
//      omitted = outputs are ephemeral by declaration;
//    · omitted operations = the zod op vocabulary (extracted) is canonical.
// ============================================================================

import type { ToolCapability } from './contract.js'

export const TOOL_CAPABILITY_DECLARATIONS: Record<string, ToolCapability> = {
  Agent: {
    intents: ['delegate a task to a subagent', 'run parallel research or implementation', 'fan out independent work'],
    units: ['task-coordination'],
    class: 'coordination',
    execution: { kind: 'agent', representation: 'external-projection' },
    resources: ['agent'],
    cancellation: 'cooperative',
    latency: 'long-running',
  },
  ArtifactsList: {
    intents: ['list durable artifacts', 'find a stored artifact'],
    units: ['resource-inspection'],
    class: 'observation',
    resources: ['artifact'],
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  ApolloReview: {
    intents: ['present the closing review of an Apollo pre-flight spec', 'ask the operator to approve or revise an Apollo spec', 'close an Apollo interview'],
    units: ['operator-io'],
    class: 'coordination',
    cancellation: 'not-applicable',
    latency: 'interactive',
    conditions: ['an Apollo Mode interview in the main session'],
    workflows: false,
  },
  AskUserQuestion: {
    intents: ['ask the operator a structured question', 'offer choices for a decision'],
    units: ['operator-io'],
    class: 'coordination',
    cancellation: 'not-applicable',
    latency: 'interactive',
  },
  Bash: {
    intents: ['run a shell command', 'execute a build or test command', 'run git commands', 'start a background process'],
    units: ['process-execution'],
    class: 'execution',
    execution: { kind: 'background-job', representation: 'external-projection' },
    resources: ['task'],
    cancellation: 'kill',
    latency: 'long-running',
  },
  Correct: {
    intents: ['correct a remembered fact', 'supersede or retract project memory'],
    units: ['memory'],
    class: 'mutation',
    operations: ['supersede', 'amend', 'retract'],
    cancellation: 'not-applicable',
    latency: 'fast',
    gate: 'MERCURY_MNEME',
    proof: 'scripts/memory/prove-verbs-lifecycle.ts',
  },
  Checkpoint: {
    intents: ['mark a named checkpoint in the session', 'snapshot the working state for a later rewind'],
    units: ['task-coordination'],
    class: 'mutation',
    cancellation: 'not-applicable',
    latency: 'fast',
    proof: 'scripts/run-recovery/run-all.sh',
  },
  Rewind: {
    intents: ['rewind the session to a checkpoint', 'restore the checkpointed working state'],
    units: ['task-coordination'],
    class: 'mutation',
    cancellation: 'not-applicable',
    latency: 'interactive',
    proof: 'scripts/run-recovery/run-all.sh',
  },
  CronCreate: {
    intents: ['schedule a recurring run', 'create a cron job'],
    units: ['scheduling'],
    class: 'mutation',
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  CronDelete: {
    intents: ['delete a scheduled run'],
    units: ['scheduling'],
    class: 'mutation',
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  CronList: {
    intents: ['list scheduled runs'],
    units: ['scheduling'],
    class: 'observation',
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  Debug: {
    intents: ['debug a program with breakpoints', 'step through code', 'inspect stack and variables', 'attach to a process'],
    units: ['debugging'],
    class: 'execution',
    execution: { kind: 'debug-adapter', representation: 'external-projection' },
    cancellation: 'cooperative',
    latency: 'long-running',
    gate: 'MERCURY_DAP',
    conditions: ['a resolvable debug adapter for the language (debugpy · lldb-dap · gdb · godot)'],
    proof: 'scripts/ide/prove-native-debug.ts',
  },
  Edit: {
    intents: ['edit a file by exact string replacement', 'apply a small code change'],
    units: ['text-mutation'],
    class: 'mutation',
    transaction: { kind: 'file', receipts: true },
    evidence: ['change'],
    resources: ['file', 'receipt'],
    cancellation: 'not-applicable',
    latency: 'fast',
    proof: 'scripts/project-services/prove-change-receipts.ts',
  },
  EnterPlanMode: {
    intents: ['start planning before implementation'],
    units: ['planning'],
    class: 'coordination',
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  EnterWorktree: {
    intents: ['work in an isolated git worktree'],
    units: ['git-transactions'],
    class: 'mutation',
    cancellation: 'not-applicable',
    latency: 'interactive',
  },
  Eval: {
    intents: [
      'run python or javascript with persistent state',
      'orchestrate tools and agents from inside code',
      'data work over a retained kernel',
      'bulk transforms the shell is too stateless for',
    ],
    units: ['persistent-evaluation'],
    class: 'execution',
    execution: { kind: 'eval-kernel', representation: 'child-execution' },
    evidence: ['execution'],
    cancellation: 'cooperative',
    latency: 'long-running',
    gate: 'MERCURY_EVAL',
    conditions: ['a Python 3.10+ interpreter or a node binary reachable for kernels'],
    proof: 'scripts/eval/prove-kernel-persistence.ts',
  },
  ExitPlanMode: {
    intents: ['present the plan for approval', 'leave strategy mode'],
    units: ['planning'],
    class: 'coordination',
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  ExitWorktree: {
    intents: ['leave the isolated worktree'],
    units: ['git-transactions'],
    class: 'mutation',
    cancellation: 'not-applicable',
    latency: 'interactive',
  },
  Recall: {
    intents: ['search project memory', 'read a remembered record by id'],
    units: ['memory'],
    class: 'observation',
    cancellation: 'not-applicable',
    latency: 'fast',
    gate: 'MERCURY_MNEME',
    proof: 'scripts/memory/prove-verbs-lifecycle.ts',
  },
  Reflect: {
    intents: ['synthesize an answer over project memory with citations'],
    units: ['memory'],
    class: 'observation',
    cancellation: 'cooperative',
    latency: 'interactive',
    gate: 'MERCURY_MNEME',
    proof: 'scripts/memory/prove-reflect-grounding.ts',
  },
  Retain: {
    intents: ['store durable facts into project memory'],
    units: ['memory'],
    class: 'mutation',
    cancellation: 'not-applicable',
    latency: 'fast',
    gate: 'MERCURY_MNEME',
    proof: 'scripts/memory/prove-retain-honesty.ts',
  },
  Glob: {
    intents: ['find files by name pattern', 'list files matching a glob'],
    units: ['source-reading'],
    class: 'observation',
    cancellation: 'not-applicable',
    latency: 'fast',
    conditions: ['a search binary (vendored ripgrep or PATH rg)'],
  },
  Godot: {
    intents: ['drive the godot editor', 'edit scenes nodes and resources', 'run and test a godot game'],
    units: ['game-engine'],
    class: 'mutation',
    cancellation: 'cooperative',
    latency: 'interactive',
    gate: 'MERCURY_GODOT_TOOLS',
    conditions: ['a project.godot root', 'the mercury_vulcan addon listening on loopback'],
    proof: 'scripts/vulcan/run-all.sh',
  },
  Grep: {
    intents: ['search file contents by regex', 'find symbol references as text'],
    units: ['source-reading'],
    class: 'observation',
    cancellation: 'not-applicable',
    latency: 'fast',
    conditions: ['a search binary (vendored ripgrep or PATH rg)'],
  },
  Inspect: {
    intents: ['read a mercury:// resource', 'inspect a receipt transaction execution or evidence record', 'page through bounded resource views'],
    units: ['resource-inspection'],
    class: 'observation',
    resources: ['file', 'run', 'receipt', 'task', 'execution', 'transaction', 'evidence'],
    cancellation: 'not-applicable',
    latency: 'fast',
    gate: 'MERCURY_REFS',
    proof: 'scripts/project-services/prove-resource-plane.ts',
  },
  Launch: {
    intents: ['run a launch profile', 'debug run test or build from unified profiles'],
    units: ['process-execution', 'debugging'],
    class: 'execution',
    execution: { kind: 'debug-adapter', representation: 'external-projection' },
    cancellation: 'cooperative',
    latency: 'long-running',
    gate: 'MERCURY_LAUNCH',
    proof: 'scripts/ide/prove-launch-profiles.ts',
  },
  LaunchFleet: {
    intents: ['launch a fleet of teammates'],
    units: ['task-coordination'],
    class: 'coordination',
    resources: ['team'],
    cancellation: 'cooperative',
    latency: 'long-running',
  },
  ListMcpResourcesTool: {
    intents: ['list resources exposed by mcp servers'],
    units: ['resource-inspection'],
    class: 'observation',
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  LSP: {
    intents: [
      'rename a symbol across the project',
      'go to definition or references',
      'get diagnostics for a file',
      'apply a server code action or quick fix',
      'format a document',
      'move a source file with import updates',
    ],
    units: ['code-intelligence'],
    class: 'mutation',
    transaction: { kind: 'lsp.rename', receipts: true },
    evidence: ['change'],
    resources: ['file', 'receipt'],
    preview: true,
    cancellation: 'cooperative',
    latency: 'interactive',
    gate: 'MERCURY_LSP',
    conditions: ['a connected language server for the file type'],
    proof: 'scripts/lsp/run-all.sh',
  },
  Monitor: {
    intents: ['wait on a background task until a condition', 'watch task output'],
    units: ['task-coordination'],
    class: 'observation',
    resources: ['task'],
    cancellation: 'cooperative',
    latency: 'long-running',
  },
  NotebookEdit: {
    intents: ['edit a jupyter notebook cell'],
    units: ['text-mutation'],
    class: 'mutation',
    transaction: { kind: 'notebook', receipts: true },
    evidence: ['change'],
    resources: ['file', 'receipt'],
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  PushNotification: {
    intents: ['send the operator a push notification'],
    units: ['operator-io'],
    class: 'coordination',
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  Read: {
    intents: ['read a file', 'view an image or pdf', 'read a notebook'],
    units: ['source-reading'],
    class: 'observation',
    resources: ['file'],
    cancellation: 'not-applicable',
    latency: 'fast',
    proof: 'scripts/project-services/prove-change-anchors.ts',
  },
  ReadMcpResourceTool: {
    intents: ['read a resource from an mcp server'],
    units: ['resource-inspection'],
    class: 'observation',
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  RememberLesson: {
    intents: ['bank a verified transferable lesson', 'save an experience card'],
    units: ['memory'],
    class: 'mutation',
    cancellation: 'not-applicable',
    latency: 'fast',
    gate: 'MERCURY_EXPERIENCE_CARDS',
  },
  ScheduleWakeup: {
    intents: ['schedule my own next wake', 'pace a self-driven loop'],
    units: ['scheduling'],
    class: 'coordination',
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  SendMessage: {
    intents: ['message a teammate or team', 'relay work between agents'],
    units: ['task-coordination'],
    class: 'coordination',
    resources: ['team'],
    cancellation: 'not-applicable',
    latency: 'fast',
    proof: 'scripts/crew/run-all.sh',
  },
  SendUserFile: {
    intents: ['send a file to the operator'],
    units: ['operator-io'],
    class: 'coordination',
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  SendUserMessage: {
    intents: ['send the operator a brief out-of-band message'],
    units: ['operator-io'],
    class: 'coordination',
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  Service: {
    intents: [
      'start a named long-lived dev service',
      'wait for service readiness',
      'read service logs',
      'stop or restart a service',
    ],
    units: ['service-management'],
    class: 'execution',
    execution: { kind: 'service', representation: 'full-execution-owner' },
    evidence: ['check', 'execution'],
    resources: ['service', 'execution'],
    cancellation: 'cooperative',
    latency: 'long-running',
    gate: 'MERCURY_SERVICES',
    proof: 'scripts/project-services/prove-services.ts',
  },
  SetTier: {
    intents: ['retune model and effort tier in autopilot'],
    units: ['task-coordination'],
    class: 'coordination',
    cancellation: 'not-applicable',
    latency: 'fast',
    gate: 'MERCURY_AUTOPILOT',
  },
  Skill: {
    intents: ['invoke a packaged skill or slash command'],
    units: ['capability-discovery'],
    class: 'coordination',
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  Sleep: {
    intents: ['wait a bounded interval'],
    units: ['scheduling'],
    class: 'observation',
    cancellation: 'cooperative',
    latency: 'long-running',
    proof: 'scripts/tools/prove-sleep-tool.ts',
  },
  TaskCreate: {
    intents: ['create a tracked task'],
    units: ['task-coordination'],
    class: 'mutation',
    resources: ['task'],
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  TaskGet: {
    intents: ['read one tracked task'],
    units: ['task-coordination'],
    class: 'observation',
    resources: ['task'],
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  TaskList: {
    intents: ['list tracked tasks'],
    units: ['task-coordination'],
    class: 'observation',
    resources: ['task'],
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  TaskOutput: {
    intents: ['read output from a background task or agent'],
    units: ['task-coordination'],
    class: 'observation',
    resources: ['task', 'agent'],
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  TaskStop: {
    intents: ['stop a background task or agent'],
    units: ['task-coordination'],
    class: 'coordination',
    resources: ['task'],
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  TaskUpdate: {
    intents: ['update a tracked task'],
    units: ['task-coordination'],
    class: 'mutation',
    resources: ['task'],
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  TeamBrief: {
    intents: ['brief a chartered team'],
    units: ['task-coordination'],
    class: 'coordination',
    resources: ['team'],
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  TeamCreate: {
    intents: ['charter a team of teammates'],
    units: ['task-coordination'],
    class: 'coordination',
    resources: ['team'],
    cancellation: 'cooperative',
    latency: 'interactive',
  },
  TeamDelete: {
    intents: ['dissolve a chartered team'],
    units: ['task-coordination'],
    class: 'coordination',
    resources: ['team'],
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  Test: {
    intents: [
      'run the test suite structurally',
      'rerun failed tests',
      'debug one failing test',
      'run the relevant tests',
      'run the relevant tests for my changes',
      'run the tests touched by changed files',
    ],
    units: ['application-verification'],
    class: 'execution',
    execution: { kind: 'background-job', representation: 'external-projection' },
    evidence: ['check'],
    resources: ['test'],
    cancellation: 'kill',
    latency: 'long-running',
    gate: 'MERCURY_TESTS',
    conditions: ['a discoverable test framework (pytest · unittest · node-test · vitest · jest · cargo · go)'],
    proof: 'scripts/ide/prove-python-tests.ts',
  },
  TodoWrite: {
    intents: ['track a short todo list for the session'],
    units: ['planning'],
    class: 'coordination',
    cancellation: 'not-applicable',
    latency: 'fast',
  },
  ToolSearch: {
    intents: ['find the right tool for a job', 'load a deferred tool schema', 'discover capability by intent'],
    units: ['capability-discovery'],
    class: 'observation',
    cancellation: 'not-applicable',
    latency: 'fast',
    proof: 'scripts/builtin-tools/prove-toolsearch-capability.ts',
  },
  Transaction: {
    intents: ['bind a coding loop into one evidence record', 'prove a fix end to end'],
    units: ['application-verification'],
    class: 'coordination',
    resources: ['ide'],
    cancellation: 'not-applicable',
    latency: 'fast',
    gate: 'MERCURY_IDE_LOOP',
    proof: 'scripts/ide/prove-closed-loop.ts',
  },
  WebFetch: {
    intents: ['fetch and read a web page'],
    units: ['web-access'],
    class: 'observation',
    cancellation: 'cooperative',
    latency: 'interactive',
  },
  ProviderSearch: {
    intents: ["search the web through the session provider's own native search"],
    units: ['web-access'],
    class: 'observation',
    cancellation: 'cooperative',
    latency: 'interactive',
    proof: 'scripts/search/run-all.sh',
  },
  WebSearch: {
    intents: ['search the web'],
    units: ['web-access'],
    class: 'observation',
    cancellation: 'cooperative',
    latency: 'interactive',
    proof: 'scripts/search/run-all.sh',
  },
  Workflow: {
    intents: ['orchestrate many subagents deterministically', 'fan out and verify at scale'],
    units: ['task-coordination'],
    class: 'coordination',
    execution: { kind: 'workflow-worker', representation: 'child-execution' },
    resources: ['workflow'],
    cancellation: 'cooperative',
    latency: 'long-running',
    gate: 'MERCURY_WORKFLOWS',
    proof: 'scripts/workflows/run-all.sh',
  },
  Workshop: {
    intents: [
      'evaluate code in a persistent kernel',
      'keep state across evaluations',
      'script tools and resources programmatically',
    ],
    units: ['persistent-evaluation'],
    class: 'execution',
    execution: { kind: 'workshop-js', representation: 'full-execution-owner' },
    transaction: { kind: 'workshop', receipts: true },
    evidence: ['execution'],
    resources: ['execution', 'artifact'],
    cancellation: 'kill',
    latency: 'long-running',
    gate: 'MERCURY_WORKSHOP',
    proof: 'scripts/project-services/prove-workshop.ts',
    workshop: false, // recursive Workshop is refused by the bridge
  },
  Write: {
    intents: ['create a file', 'overwrite a file wholesale'],
    units: ['text-mutation'],
    class: 'mutation',
    transaction: { kind: 'file', receipts: true },
    evidence: ['change'],
    resources: ['file', 'receipt'],
    cancellation: 'not-applicable',
    latency: 'fast',
    proof: 'scripts/project-services/prove-change-receipts.ts',
  },
}
