#!/usr/bin/env bun
import { spawnSync } from 'node:child_process'
import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'

const ROOT = resolve(import.meta.dir, '..', '..')
const GENERATOR = 'scripts/sdk/generate.ts'
const OUTPUTS = ['rows.ts', 'door.ts'] as const
const COMMITTED = join(ROOT, 'sdk', 'src')
const PLANTED = process.argv.includes('--planted-only')
let failures = 0
function check(label: string, cond: boolean, detail = ''): void {
  if (!cond) failures++
  console.log(`  [${cond ? 'PASS' : 'FAIL'}] ${label}${!cond && detail ? ` — ${detail}` : ''}`)
}
function section(t: string): void {
  console.log(`\n${'─'.repeat(76)}\n${t}`)
}
const env = { ...process.env, MERCURY_CONFIG_DIR: process.env.MERCURY_CONFIG_DIR ?? mkdtempSync(join(tmpdir(), 'sdk-drift-home-')), MERCURY_LOCAL_PROBE_TARGETS: 'none' }
const generate = (args: string[]): { status: number | null; out: string } => {
  const result = spawnSync(process.execPath, ['run', join(ROOT, GENERATOR), ...args], { cwd: ROOT, encoding: 'utf8', env, timeout: 180_000 })
  return { status: result.status, out: `${result.stdout}${result.stderr}` }
}

const scratch = mkdtempSync(join(tmpdir(), 'sdk-drift-'))
try {
  if (!PLANTED) {
    section('D1 the committed generated files are byte-identical to a fresh generation from the tree')
    const fresh = join(scratch, 'fresh')
    mkdirSync(fresh)
    const run = generate(['--out', fresh])
    check('the generator exits 0 against the tree', run.status === 0, run.out.slice(0, 1200))
    for (const name of OUTPUTS) {
      const committed = readFileSync(join(COMMITTED, name), 'utf8')
      const generated = readFileSync(join(fresh, name), 'utf8')
      const firstDifference = [...committed].findIndex((char, i) => char !== generated[i])
      check(`sdk/src/${name} is byte-identical to the generator's output (${committed.length} bytes)`, committed === generated, firstDifference >= 0 ? `first difference at byte ${firstDifference}: committed ${JSON.stringify(committed.slice(firstDifference, firstDifference + 60))} vs generated ${JSON.stringify(generated.slice(firstDifference, firstDifference + 60))}` : `lengths ${committed.length} vs ${generated.length}`)
    }
    const checkMode = generate(['--check'])
    check('the generator\'s own --check mode agrees (exit 0, SAME for every output)', checkMode.status === 0 && OUTPUTS.every(name => checkMode.out.includes(`SAME ${join(COMMITTED, name)}`)), checkMode.out.slice(0, 600))
    const header = readFileSync(join(COMMITTED, 'rows.ts'), 'utf8')
    check('the generated file names its generator and its source as data on its first lines, not as comments', header.startsWith(`export const GENERATED = 'generated by bun ${GENERATOR}'\n`) && header.includes(`export const GENERATED_BY = '${GENERATOR}'`) && header.includes("export const GENERATED_FROM = ['src/rows/vocabulary.ts'] as const") && !/^\s*\/\//m.test(header))
    const map = readFileSync(join(ROOT, 'scripts/gate/generated-assets.tsv'), 'utf8').split('\n').find(line => line.startsWith('sdk/src/rows.ts'))
    check('the generated-assets map carries the package row (the commit gate owes the asset to a vocabulary change)', map !== undefined && map.includes(`bun ${GENERATOR}`) && map.includes('src/rows/vocabulary.ts') && map.includes('src/main.tsx'), map ?? 'no row')
  }

  section('D2 the planted red: a renamed schema field on a scratch copy of the tree moves the output, and --check reads DRIFT')
  const tree = join(scratch, 'tree')
  mkdirSync(tree)
  cpSync(join(ROOT, 'src'), join(tree, 'src'), { recursive: true })
  symlinkSync(join(ROOT, 'node_modules'), join(tree, 'node_modules'))
  const vocabularyPath = join(tree, 'src', 'rows', 'vocabulary.ts')
  const vocabulary = readFileSync(vocabularyPath, 'utf8')
  const needle = 'cached_input_tokens: z.number().int().min(0),'
  check('the vocabulary spells the field the plant renames', vocabulary.includes(needle))
  writeFileSync(vocabularyPath, vocabulary.replace(needle, 'cached_tokens: z.number().int().min(0),'))
  const planted = join(scratch, 'planted')
  mkdirSync(planted)
  for (const name of OUTPUTS) cpSync(join(COMMITTED, name), join(planted, name))
  const checkPlanted = generate(['--root', tree, '--out', planted, '--check'])
  check('--check against the planted tree exits 1 and names rows.ts as DRIFT', checkPlanted.status === 1 && checkPlanted.out.includes(`DRIFT ${join(planted, 'rows.ts')}`), checkPlanted.out.slice(0, 600))
  check('the door file, untouched by the plant, still reads SAME', checkPlanted.out.includes(`SAME ${join(planted, 'door.ts')}`), checkPlanted.out.slice(0, 600))
  const regenerated = generate(['--root', tree, '--out', planted])
  const moved = readFileSync(join(planted, 'rows.ts'), 'utf8')
  check('regenerating from the planted tree writes the renamed field into the types and the schemas', regenerated.status === 0 && moved.includes('cached_tokens: number') && moved.includes('"cached_tokens"') && !moved.includes('cached_input_tokens'), regenerated.out.slice(0, 400))
  check('the committed rows.ts differs from the planted output (the drift a vocabulary change makes)', readFileSync(join(COMMITTED, 'rows.ts'), 'utf8') !== moved)
  const keyword = join(scratch, 'keyword')
  mkdirSync(keyword)
  writeFileSync(vocabularyPath, vocabulary.replace("timestamp: z.string(),", "timestamp: z.string().regex(/^\\d/),"))
  const refused = generate(['--root', tree, '--out', keyword])
  check('a construct outside the interpreter\'s keyword set refuses to generate (a regex check on the envelope)', refused.status !== 0 && /keyword "pattern" is outside the set/.test(refused.out), refused.out.slice(0, 400))
} finally {
  rmSync(scratch, { recursive: true, force: true })
}

console.log(`\n${'═'.repeat(76)}`)
if (failures > 0) {
  console.log(`❌ prove-rows-drift: ${failures} failure(s)`)
  process.exit(1)
}
console.log('✅ prove-rows-drift: the committed row types are what the tree generates, and a moved schema reads red')
