
export type WardScope = 'edit' | 'bash'

export type GeneratedPath = {
  pattern: string
  generator?: string
  sources?: string
  check?: string | null
}

export type WardRule = {
  name: string
  teach: string
  scope: WardScope
  patterns: string[]
  flags?: string
  pathPattern?: string
  allowPathPattern?: string
  newContentOnly?: boolean
  skipCommentLines?: boolean
  outsideQuotes?: boolean
  refusal?: boolean
  foldLines?: boolean
  generatedPaths?: GeneratedPath[]
  leadingMarker?: string
}

export type WardVerdict =
  | { allow: true }
  | {
      allow: false
      rule: WardRule
      excerpt: string
      line: number
      target: string
      generator?: string
      sources?: string
      check?: string | null
    }

export type ResolvedPath = {
  path: string
  root: string | undefined
}

export type PendingToolCall = {
  toolName: string
  input: Record<string, unknown>
  shellCommand?: string
  readHead?: (path: string) => string | undefined
  resolvePath?: (path: string) => ResolvedPath
}

const EDIT_TOOLS = new Set(['Edit', 'NotebookEdit'])
const WRITE_TOOLS = new Set(['Write'])
const CHANGESET_TOOLS = new Set(['ChangeSet'])
const AST_EDIT_TOOLS = new Set(['AstEdit'])
const STRUCTURE_TOOLS = new Set(['Structure'])
const GIT_TOOLS = new Set(['Git'])
const LSP_TOOLS = new Set(['LSP'])
export const WARDS_TOOL_MATCHER = '*'

const EMOJI_PATTERN = '[\\u{1F300}-\\u{1FAFF}]|\\uFE0F'

const OMISSION_MARK = '(?:\\.{3,}(?!\\.)|\\u2026+)'
const OMISSION_LEADER = '(?:\\/\\/+|#+|--+|;+|%+|<!--|\\{\\/\\*+|\\/\\*+|\\*+)[ \\t]*'
const OMISSION_CLOSE = '(?=((?:[ \\t]*(?:\\*+\\/\\}?|-->|[\\)\\]\\}>]))*))\\1[ \\t]*\\.?'
const OMISSION_NOUN = '(?:code|methods?|functions?|file|class|implementation|logic|markup|imports|lines|content|template)'
const OMISSION_STATE =
  '(?:unchanged|omitted|is[ \\t]+unchanged|is[ \\t]+the[ \\t]+same|remains?[ \\t]+(?:unchanged|the[ \\t]+same)|stays?[ \\t]+the[ \\t]+same)'
const OMISSION_PHRASE =
  '(?=[A-Za-z])(?:' +
  `rest[ \\t]+of(?:[ \\t]+the)?(?:[ \\t]+${OMISSION_NOUN})?(?:[ \\t]+${OMISSION_STATE})?` +
  `|unchanged(?:[ \\t]+${OMISSION_NOUN})?` +
  `|existing[ \\t]+${OMISSION_NOUN}(?:[ \\t]+${OMISSION_STATE})?` +
  `|(?:the[ \\t]+)?${OMISSION_NOUN}[ \\t]+${OMISSION_STATE}` +
  `|(?:the[ \\t]+)?rest[ \\t]+${OMISSION_STATE}` +
  ")(?![\\w'-])"
const OMISSION_OPEN = '[\\(\\[\\{]?[ \\t]*'
const OMISSION_SHUT = '[ \\t]*[\\)\\]\\}]?'
const OMISSION_DOTS = `${OMISSION_MARK}(?:[ \\t]+\\.+)*`
const OMISSION_TRAILING = `${OMISSION_OPEN}${OMISSION_PHRASE}${OMISSION_SHUT}[ \\t]*${OMISSION_DOTS}`
const OMISSION_LEADING = (gap: string): string =>
  `${OMISSION_OPEN}${OMISSION_DOTS}${gap}${OMISSION_OPEN}${OMISSION_PHRASE}${OMISSION_SHUT}(?:[ \\t]*${OMISSION_DOTS})?`
export const OMISSION_PLACEHOLDER =
  `^(?=[^\\n]*?${OMISSION_MARK})` +
  `(?:${OMISSION_LEADER}(?:${OMISSION_TRAILING}|${OMISSION_LEADING('[ \\t]*')})|${OMISSION_TRAILING}|${OMISSION_LEADING('[ \\t]+')})` +
  `${OMISSION_CLOSE}$`

const GENERATOR_SCRIPT = '((?:[A-Za-z0-9_.-]+\\/)*[A-Za-z0-9_.-]+\\.(?:ts|tsx|mts|mjs|cjs|js|sh|py|rb|go|rs))'
const GENERATOR_RUNNER = '`?(?:bun run |bun |node |bash |sh |python3? |deno run |deno )?'
export const GENERATED_MARKER =
  '@generated\\b' +
  '|\\bdo not (?:edit|modify)(?:[ \\t]+(?:this[ \\t]+file|the[ \\t]+file|by[ \\t]+hand|manually|directly|it))*[ \\t]*(?:[.!,;:)\\]\\u2014\\u2013-]|\\*\\/|-->|$)' +
  '|\\bauto[ -]?generated\\b' +
  '|\\bcode generated by\\b' +
  '|\\b(?:automatically|programmatically) generated\\b' +
  '|\\b(?:generated|maintained) automatically\\b' +
  '|\\bdo not hand-?edit\\b' +
  '|"(?:generatedBy|composedBy)"[ \\t]*:' +
  `|"generator"[ \\t]*:[ \\t]*"${GENERATOR_SCRIPT}"` +
  '|^[ \\t]*>?[ \\t]*Regenerate:[ \\t]' +
  `|\\b(?:generated|composed|managed) by[ \\t]+${GENERATOR_RUNNER}${GENERATOR_SCRIPT}\\b`
export const GENERATED_DECLARATION =
  `\\b(?:generated|composed|managed) by[ \\t]+${GENERATOR_RUNNER}${GENERATOR_SCRIPT}\\b` +
  `|"(?:generatedBy|composedBy|generator)"[ \\t]*:[ \\t]*"${GENERATOR_SCRIPT}"` +
  `|^[ \\t]*>?[ \\t]*Regenerate:[ \\t]+${GENERATOR_RUNNER}${GENERATOR_SCRIPT}\\b`
export const GENERATED_HEAD_LINES = 12
export const GENERATED_HEAD_CHARS = 4096

const GENERATED_PATHS: GeneratedPath[] = [
  { pattern: '^scripts/settings/settings-schema\\.json$', generator: 'bun scripts/settings/gen-settings-schema.ts', sources: 'src/utils/settings/**', check: 'bun scripts/settings/prove-settings-schema.ts' },
  { pattern: '^scripts/ownership/contract-inventory\\.json$', generator: 'bun scripts/ownership/prove-contract-inventory.ts --record', sources: 'the modules the inventory names (files-of:scripts/ownership/contract-inventory.json)', check: 'bun scripts/ownership/prove-contract-inventory.ts' },
  { pattern: '^scripts/ink-runtime/facade-inventory\\.json$', generator: 'bun scripts/ink-runtime/prove-facade-inventory.ts --record', sources: 'src/ink.ts', check: 'bun scripts/ink-runtime/prove-facade-inventory.ts' },
  { pattern: '^scripts/ink-runtime/deep-import-inventory\\.json$', generator: 'bun scripts/ink-runtime/prove-deep-import-policy.ts --record', sources: 'src/**/*.{ts,tsx} scripts/**/*.{ts,tsx}', check: 'bun scripts/ink-runtime/prove-deep-import-policy.ts' },
  { pattern: '^scripts/consistency-census/shellstring-census\\.json$', generator: 'bun scripts/consistency-census/gen-shellstring-census.ts', sources: 'src/**/*.{ts,tsx,mjs} scripts/**/*.{ts,tsx,mjs}', check: 'bun scripts/consistency-census/prove-shellstring-census.ts' },
  { pattern: '^scripts/consistency-census/lockup-census\\.json$', generator: 'bun scripts/consistency-census/gen-lockup-census.ts', sources: 'src/**/*.tsx', check: 'bun scripts/consistency-census/prove-lockup-census.ts' },
  { pattern: '^scripts/consistency-census/basename-census\\.json$', generator: 'bun scripts/consistency-census/gen-basename-census.ts', sources: 'src/**/*.{ts,tsx,mjs}', check: 'bun scripts/consistency-census/prove-basename-census.ts' },
  { pattern: '^assets/completions/(?:mercury\\.bash|_mercury|mercury\\.fish)$', generator: 'bun run build.ts && bun scripts/project-services/gen-completions.ts', sources: 'src/main.tsx src/commands/mcp/addCommand.ts', check: 'bun scripts/project-services/gen-completions.ts --check' },
  { pattern: '^(?:mercury-skills|src/skills/bundled)/extension-maker/references/CONTRACT\\.md$', generator: 'bun scripts/extensions/gen-contract.ts', sources: 'src/extensions/manifest.ts src/extensions/catalogue.ts', check: 'bun scripts/extensions/prove-contract-in-sync.ts' },
  { pattern: '^src/skills/bundled/[^/.]+(?:/.*)?$', generator: 'bun scripts/skills/gen-bundled.ts', sources: 'mercury-skills/**', check: null },
  { pattern: '^src/services/blender/bridgeFiles\\.generated\\.ts$', generator: 'node scripts/blender-bridge/regen-bridge.mjs', sources: 'assets/blender/bridge/**', check: 'node scripts/blender-bridge/regen-bridge.mjs --check' },
  { pattern: '^src/services/unity/bridgeFiles\\.generated\\.ts$', generator: 'node scripts/unity-bridge/regen-bridge.mjs', sources: 'assets/unity/bridge/**', check: 'node scripts/unity-bridge/regen-bridge.mjs --check' },
  { pattern: '^src/services/vulcan/addonFiles\\.generated\\.ts$', generator: 'node scripts/vulcan/regen-addon.mjs', sources: 'assets/vulcan/addon/**', check: 'node scripts/vulcan/regen-addon.mjs --check' },
  { pattern: '^(?:src/utils/vulcan/optable\\.generated\\.ts|assets/vulcan/addon/core/op_classes\\.gd)$', generator: 'node scripts/vulcan/regen-optable.mjs', sources: 'assets/vulcan/optable.json', check: 'node scripts/vulcan/regen-optable.mjs --check' },
  { pattern: '^scripts/builtin-tools/fixtures/tool-census\\.(?:json|md)$', generator: 'bun scripts/builtin-tools/census-gen.ts', sources: 'src/Tool.ts src/tools.ts src/tools/** src/utils/capability/**', check: 'bun scripts/builtin-tools/prove-builtin-tools-census.ts' },
  { pattern: '^scripts/builtin-tools/fixtures/(?:RESULTS\\.md|results\\.json)$', generator: 'bun scripts/builtin-tools/bench-builtin-tools.ts --write', sources: 'scripts/builtin-tools/bench-builtin-tools.ts', check: null },
  { pattern: '^scripts/ui/fixtures/motion-menu/[^/]+\\.txt$', generator: 'bun scripts/ui/motion-menu-stills.ts --write', sources: 'scripts/ui/motion-menu-stills.ts assets/splash/splash-core.mjs src/substrate/startupMenu.ts src/services/switchboard/capacityCheck.ts src/utils/cockpit/motion* src/utils/cockpit/liveGlyphs.ts src/utils/cockpit/critterIdle.ts', check: 'bun scripts/transcript-rows/prove-motion-setting.ts' },
  { pattern: '^scripts/compositor/fixtures/surface-census\\.md$', generator: 'bun scripts/compositor/prove-surface-census.ts --write', sources: 'src/commands/** src/interactiveHelpers.tsx src/screens/ResumeConversation.tsx src/ink/components/AlternateScreen.tsx src/entrypoints/cli.tsx', check: 'bun scripts/compositor/prove-surface-census.ts' },
  { pattern: '^scripts/critters/fixtures/zzz-frames\\.json$', generator: 'bun scripts/critters/gen-zzz-frames.ts', sources: 'scripts/critters/zzzFrames.ts', check: 'bun scripts/critters/prove-critter-sleep.ts' },
  { pattern: '^design-system/live/(?:manifest\\.json|grids/[^/]+\\.grid\\.json)$', generator: 'bun scripts/ui/generate-visual-baseline.ts', sources: 'the built runtime (bun run build.ts) and the screens the baseline captures' },
  { pattern: '(?:^|/)bun\\.lockb?$', generator: 'its package manager (bun), from package.json' },
  { pattern: '(?:^|/)(?:package-lock\\.json|npm-shrinkwrap\\.json)$', generator: 'its package manager (npm), from package.json' },
  { pattern: '(?:^|/)yarn\\.lock$', generator: 'its package manager (yarn), from package.json' },
  { pattern: '(?:^|/)pnpm-lock\\.yaml$', generator: 'its package manager (pnpm), from package.json' },
  { pattern: '(?:^|/)Cargo\\.lock$', generator: 'its package manager (cargo), from Cargo.toml' },
  { pattern: '(?:^|/)poetry\\.lock$', generator: 'its package manager (poetry), from pyproject.toml' },
  { pattern: '(?:^|/)Pipfile\\.lock$', generator: 'its package manager (pipenv), from the Pipfile' },
  { pattern: '(?:^|/)uv\\.lock$', generator: 'its package manager (uv), from pyproject.toml' },
  { pattern: '(?:^|/)composer\\.lock$', generator: 'its package manager (composer), from composer.json' },
  { pattern: '(?:^|/)Gemfile\\.lock$', generator: 'its package manager (bundler), from the Gemfile' },
  { pattern: '(?:^|/)go\\.sum$', generator: 'the go tool, from go.mod' },
  { pattern: '(?:^|/)flake\\.lock$', generator: 'nix, from flake.nix' },
  { pattern: '(?:^|/)Podfile\\.lock$', generator: 'its package manager (cocoapods), from the Podfile' },
  { pattern: '(?:^|/)mix\\.lock$', generator: 'its package manager (mix), from mix.exs' },
  { pattern: '(?:^|/)pubspec\\.lock$', generator: 'its package manager (pub), from pubspec.yaml' },
  { pattern: '(?:^|/)packages\\.lock\\.json$', generator: 'its package manager (dotnet), from the project file' },
  { pattern: '(?:^|/)\\.terraform\\.lock\\.hcl$', generator: 'terraform, from the provider requirements' },
  { pattern: '\\.generated\\.[A-Za-z0-9]+$' },
  { pattern: '^(?:.*/)?(?:__generated__|generated)(?:/|$)' },
]

export const BUILTIN_WARDS: readonly WardRule[] = [
  {
    name: 'no-new-hex-outside-theme',
    teach:
      'Zero new hex outside the theme tokens (the UI hard rules). Import the ' +
      'token instead (mercuryPalette / sessionAccent); if a genuinely new color is needed, ' +
      'add it to mercuryPalette.ts first, then import it here.',
    scope: 'edit',
    patterns: ['#[0-9a-fA-F]{3,8}\\b'],
    pathPattern: 'src/(components|screens|commands)/.*\\.(ts|tsx)$',
    allowPathPattern:
      '(components/mercuryPalette\\.ts|mercury-ui/sessionAccent\\.ts' +
      '|components/Spinner/(GlimmerMessage\\.tsx|SpinnerGlyph\\.tsx|utils\\.ts))$',
    newContentOnly: true,
  },
  {
    name: 'no-emoji-in-tui-source',
    teach:
      'No emoji in live TUI sources (the UI hard rules): the marks are <Crab/> ' +
      '(product lockup) / <SessionMark/> (session-identity slots) and the sanctioned ' +
      'glyph vocabulary lives in mercury-ui glyphs. Use those or plain text.',
    scope: 'edit',
    patterns: [EMOJI_PATTERN],
    flags: 'u',
    pathPattern: 'src/(components|screens|commands)/.*\\.(ts|tsx)$',
    newContentOnly: true,
  },
  {
    name: 'no-force-push-protected',
    teach:
      'Never force-push a SHARED ref — main/master is append-only here (the ' +
      'push-green-to-main directive assumes it). Push normally after pull --rebase, or use ' +
      '--force-with-lease on a topic branch only you own.',
    scope: 'bash',
    patterns: [
      'git\\s+push[^\\n;|&]*(?:--force(?!-with-lease)|\\s-f\\b)[^\\n;|&]*\\s(?:origin\\s+)?(?:main|master)\\b',
      'git\\s+push[^\\n;|&]*\\s(?:origin\\s+)?(?:main|master)\\b[^\\n;|&]*(?:--force(?!-with-lease)|\\s-f\\b)',
    ],
    skipCommentLines: false,
  },
  {
    name: 'no-omission-placeholder',
    teach:
      'An omission placeholder ("rest of code ...", "... existing code ...") is not content: the tool lands ' +
      'exactly the bytes it is given, so the line would replace the code it stands for. Provide the literal ' +
      'content in full; a placeholder that already stands in the file is edited by carrying it in old_string.',
    scope: 'edit',
    patterns: [OMISSION_PLACEHOLDER],
    flags: 'i',
    newContentOnly: true,
    skipCommentLines: false,
    foldLines: true,
  },
  {
    name: 'no-hand-edit-generated-file',
    teach:
      'A generated file is not edited by hand: the next regeneration overwrites the edit. Change the source it is ' +
      'derived from, then run its generator.',
    scope: 'edit',
    patterns: [],
    generatedPaths: GENERATED_PATHS,
    leadingMarker: GENERATED_MARKER,
    skipCommentLines: false,
  },
]

export const AUTONOMOUS_WARDS: readonly WardRule[] = [
  {
    name: 'no-home-recursive-delete',
    teach:
      'Autonomous sessions never recursively delete inside the user home (the ' +
      'deleted-workspace incident class). Do destructive cleanup inside ' +
      'your own worktree or tempdir (/tmp, $TMPDIR); if this delete is genuinely ' +
      'required, surface it to the lead/operator in your report instead of running it.',
    scope: 'bash',
    patterns: [
      '\\brm\\b(?=[^\\n;|&]*\\s(?:-[a-zA-Z]*[rR][a-zA-Z]*\\b|--recursive\\b))[^\\n;|&]*\\s(?:~(?:\\/|\\s|$)|\\$\\{?HOME|\\/Users\\/)',
      '\\bfind\\s+(?:~(?:\\/|\\s)|\\$\\{?HOME|\\/Users\\/)[^\\n;|&]*\\s-delete\\b',
    ],
    skipCommentLines: false,
  },
]

const WORD_END = '(?![\\w./-])'
const CMD_START = '(?:^|[;&|(`{]|\\$\\(|\\b(?:then|do|else)\\b|\\bsudo\\s+)\\s*'

export const REFUSAL_WARDS: readonly WardRule[] = [
  { name: 'npm-exec-yes', scope: 'bash', teach: 'npx/npm exec with an auto-confirm flag runs an unvetted remote package non-interactively.', refusal: true, skipCommentLines: false, patterns: ['\\b(?:npx|npm\\s+exec|pnpm\\s+dlx|yarn\\s+dlx)\\b[^\\n]*\\s(?:-y|--yes)\\b'] },
  { name: 'git-install-sha', scope: 'bash', teach: 'pip/npm install from a git URL pinned to an arbitrary commit SHA (bypasses release review).', refusal: true, skipCommentLines: false, patterns: ['\\b(?:pip|pip3|npm|pnpm|yarn)\\s+install\\b[^\\n]*git\\+[^\\s]+@[0-9a-f]{7,40}\\b'] },
  { name: 'curl-pipe-shell', scope: 'bash', teach: 'curl|bash / wget|sh — the Codecov class: execute a remote script sight-unseen.', refusal: true, skipCommentLines: false, patterns: ['\\b(?:curl|wget)\\b[^\\n|]*\\|\\s*(?:sudo\\s+)?(?:ba|z|da|)sh\\b'] },
  { name: 'self-daemonize', scope: 'bash', teach: "detached background self-spawn (nohup/disown/setsid &) — the ua-parser-js persistence class; a long command runs with the Bash tool's run_in_background flag.", refusal: true, skipCommentLines: false, patterns: ['\\b(?:nohup|setsid)\\b[^\\n]+&\\s*$|\\bdisown\\b'] },
  { name: 'cron-persist', scope: 'bash', teach: 'crontab install from a file — establishes scheduled persistence.', refusal: true, skipCommentLines: false, patterns: ['\\bcrontab\\s+(?!-l\\b)[^\\n]*\\b(?:-|[^\\s]+)\\b'] },
  { name: 'systemd-persist', scope: 'bash', teach: 'write into a systemd unit dir or enable a freshly-dropped unit — persistence.', refusal: true, skipCommentLines: false, patterns: ['(?:\\/etc\\/systemd\\/system|\\/etc\\/init\\.d|~?\\/\\.config\\/systemd\\/user)\\/[^\\s]+|systemctl\\s+enable\\b'] },
  { name: 'systemd-persist', scope: 'edit', teach: 'write into a systemd unit dir or enable a freshly-dropped unit — persistence.', refusal: true, skipCommentLines: false, pathPattern: '(?:\\/etc\\/systemd\\/system|\\/etc\\/init\\.d|\\/\\.config\\/systemd\\/user)\\/[^\\s]+', patterns: ['^.*$'] },
  { name: 'autostart-persist', scope: 'bash', teach: 'write into an XDG autostart / login-item dir — the xz-utils persistence class.', refusal: true, skipCommentLines: false, patterns: ['(?:\\.config\\/autostart|Library\\/LaunchAgents|Library\\/LaunchDaemons)\\/[^\\s]+\\.(?:desktop|plist)\\b'] },
  { name: 'autostart-persist', scope: 'edit', teach: 'write into an XDG autostart / login-item dir — the xz-utils persistence class.', refusal: true, skipCommentLines: false, pathPattern: '(?:\\.config\\/autostart|Library\\/LaunchAgents|Library\\/LaunchDaemons)\\/[^\\s]+\\.(?:desktop|plist)$', patterns: ['^.*$'] },
  { name: 'git-config-global', scope: 'bash', teach: 'git config --global/--system mutates config outside the repo (can redirect URLs, set filters).', refusal: true, skipCommentLines: false, outsideQuotes: true, patterns: [
    '\\bgit\\s+config\\s+(?:--global|--system)\\b(?![^\\n;|&]*\\s(?:--get|--get-all|--get-regexp|--get-urlmatch|--list|-l)\\b)[^\\n;|&]*\\s(?:--add\\s+|--unset\\s+)?[^\\s-][^\\n;|&]*\\s[^\\s;|&]+',
    '\\bgit\\s+config\\b[^\\n;|&]*\\s--(?:global|system)\\b[^\\n;|&]*\\s(?:--(?:add|unset|unset-all|replace-all|remove-section|rename-section|edit)|-e)\\b',
    '\\bgit\\s+config\\b[^\\n;|&]*\\s(?:--(?:add|unset|unset-all|replace-all|remove-section|rename-section|edit)|-e)\\b[^\\n;|&]*\\s--(?:global|system)\\b',
    '\\bgit\\s+config\\s+(?:set|unset|edit|remove-section|rename-section)\\b[^\\n;|&]*\\s--(?:global|system)\\b',
  ] },
  { name: 'git-hooks-path', scope: 'bash', teach: 'setting core.hooksPath redirects git hooks to an untrusted directory (a bare read stays clear).', refusal: true, skipCommentLines: false, outsideQuotes: true, patterns: [
    '\\bgit\\s+config\\b(?![^\\n;|&]*\\s(?:--get|--get-all|--get-regexp|--list|-l)\\b)(?:[^\\n;|&]*\\s(?:--add|--unset|--unset-all|--replace-all|--edit|--file)\\b[^\\n;|&]*\\bcore\\.hooksPath\\b|[^\\n;|&]*\\bcore\\.hooksPath[^\\S\\n]+(?!\\d*[<>])[^\\s<>|&;)]+)',
    '\\bgit\\s+config\\s+(?:set|unset)\\b[^\\n;|&]*\\bcore\\.hooksPath\\b',
  ] },
  { name: 'git-internals-write', scope: 'bash', teach: 'direct write into .git/config or .git/hooks — installs a hook or rewrites config under the radar.', refusal: true, skipCommentLines: false, patterns: ['(?:^|[\\s>|;&])(?:>>?|tee|cp|mv|install|ln)\\b[^\\n]*\\.git\\/(?:config\\b|hooks\\/)'] },
  { name: 'no-sudo', scope: 'bash', teach: 'Privilege escalation (sudo, doas, pkexec) never runs from a session; a root command is the operator\'s to run by hand.', refusal: true, skipCommentLines: false, outsideQuotes: true, patterns: [CMD_START + '(?:(?:env|nice|nohup|time|command|builtin|exec|eval|xargs|timeout|stdbuf)(?:\\s+-\\S+)*(?:\\s+\\w+=\\S*)*\\s+)*(?:sudo|doas|pkexec)' + WORD_END] },
  { name: 'no-device-write', scope: 'bash', teach: 'A raw write to a device node (dd of=/dev/…, a redirect into a disk) overwrites a disk sight-unseen.', refusal: true, skipCommentLines: false, patterns: ['\\bdd\\b[^\\n;|&]*\\bof=["\']?\\/dev\\/(?!null\\b|zero\\b|full\\b|random\\b|urandom\\b|stdout\\b|stderr\\b|stdin\\b|tty|fd\\/|shm\\/)', '>\\s*["\']?\\/dev\\/(?:r?disk\\d|sd[a-z]|hd[a-z]|nvme\\d|mmcblk\\d|vd[a-z]|xvd[a-z]|loop\\d|dm-\\d|md\\d)'] },
  { name: 'no-disk-format', scope: 'bash', teach: 'Formatting or repartitioning a disk (mkfs, fdisk, parted, diskutil erase, format) destroys everything on it.', refusal: true, skipCommentLines: false, outsideQuotes: true, patterns: [CMD_START + '(?:mkfs(?:\\.[a-z0-9]+)?' + WORD_END + '|(?:mke2fs|mkswap|wipefs|cfdisk|sgdisk)' + WORD_END + '|(?:fdisk|sfdisk|gdisk)(?!\\s+-l\\b)' + WORD_END + '|parted(?!\\s+(?:-l|--list|print)\\b)' + WORD_END + '|diskutil\\s+(?:erase\\w*|partitionDisk|zeroDisk|randomDisk|secureErase|reformat|apfs\\s+(?:deleteContainer|eraseVolume|deleteVolume))\\b|format(?:\\.com)?\\s+[A-Za-z]:|(?:Format-Volume|Clear-Disk|Initialize-Disk)\\b)'] },
  { name: 'no-system-halt', scope: 'bash', teach: 'Shutting down, rebooting or halting the machine ends every session on it, the operator\'s included.', refusal: true, skipCommentLines: false, outsideQuotes: true, patterns: [CMD_START + '(?:(?:shutdown|reboot|halt|poweroff)' + WORD_END + '|(?:init|telinit)\\s+[06]\\b|systemctl\\s+(?:poweroff|reboot|halt|kexec)\\b|(?:Stop-Computer|Restart-Computer)\\b)'] },
  { name: 'no-fork-bomb', scope: 'bash', teach: 'A process that forks itself without bound takes the machine down.', refusal: true, skipCommentLines: false, patterns: ['(:|\\w+)\\s*\\(\\s*\\)\\s*\\{\\s*\\1\\s*\\|\\s*\\1\\s*&', 'function\\s+(\\w+)\\s*\\{\\s*\\1\\s*\\|\\s*\\1\\s*&', '\\bfork\\s+while\\s+fork\\b'] },
  { name: 'no-root-recursive-delete', scope: 'bash', teach: 'A recursive delete of the filesystem root, the home directory or a system directory destroys the machine or the operator\'s files; delete inside the project, a worktree or a scratch directory instead.', refusal: true, skipCommentLines: false, patterns: [
    '\\brm\\b(?=[^\\n;|&]*\\s(?:-[a-zA-Z]*[rR][a-zA-Z]*\\b|--recursive\\b))[^\\n;|&]*\\s["\']?(?:\\/(?:\\*|\\s|$|["\'])|~(?:\\/\\*?)?(?:\\s|$|["\'])|\\$\\{?HOME\\}?(?:\\/\\*?)?(?:\\s|$|["\'])|\\/(?:Users|home)(?:\\/[^\\/\\s"\']+)?\\/?\\*?(?:\\s|$|["\'])|\\/root\\/?\\*?(?:\\s|$|["\'])|\\/(?:etc|usr|bin|sbin|lib|lib64|opt|boot|dev|proc|sys|System|Library|Applications|cores)(?:\\/[^\\s"\']*)?(?:\\s|$|["\'])|\\/var(?!\\/(?:tmp|folders)\\/)(?:\\/[^\\s"\']*)?(?:\\s|$|["\'])|\\/private(?!\\/(?:tmp|var\\/(?:tmp|folders))\\/)(?:\\/[^\\s"\']*)?(?:\\s|$|["\'])|\\/Volumes(?:\\/[^\\/\\s"\']+)?\\/?\\*?(?:\\s|$|["\']))',
    '\\b(?:rd|rmdir)\\s+\\/s\\b[^\\n;|&]*\\s["\']?[A-Za-z]:\\\\?["\']?(?:\\s|$)',
    '\\bRemove-Item\\b[^\\n;|&]*-Recurse[^\\n;|&]*\\s["\']?[A-Za-z]:\\\\?["\']?(?:\\s|$)',
  ] },
]

function blankQuotedRuns(text: string): string {
  let out = ''
  let quote: '' | "'" | '"' = ''
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]!
    if (quote === '') {
      out += ch
      if (ch === "'" || ch === '"') quote = ch
    } else if (quote === '"') {
      if (ch === '\\' && i + 1 < text.length) {
        i++
        continue
      }
      if (ch === '"') {
        out += ch
        quote = ''
      }
    } else if (ch === "'") {
      out += ch
      quote = ''
    }
  }
  return quote === '' ? out : text
}

function dropHeredocBodies(text: string): string {
  const out: string[] = []
  let terminator: string | null = null
  let dashed = false
  for (const line of text.split('\n')) {
    if (terminator !== null) {
      if ((dashed ? line.replace(/^\t+/, '') : line) === terminator) terminator = null
      continue
    }
    out.push(line)
    const m = /<<(?!<)(-?)\s*(?:'([^']+)'|"([^"]+)"|\\?([A-Za-z_][A-Za-z0-9_]*))/.exec(line)
    if (m) {
      terminator = m[2] ?? m[3] ?? m[4] ?? null
      dashed = m[1] === '-'
    }
  }
  return out.join('\n')
}

function commandOutsideQuotes(command: string): string {
  return blankQuotedRuns(dropHeredocBodies(command))
}

const compiledPatterns = new WeakMap<WardRule, RegExp[]>()
const compiledPathPatterns = new WeakMap<WardRule, RegExp | null>()
const compiledAllowPathPatterns = new WeakMap<WardRule, RegExp | null>()
const compiledGeneratedPaths = new WeakMap<WardRule, Array<{ re: RegExp; row: GeneratedPath }>>()
const compiledLeadingMarkers = new WeakMap<WardRule, RegExp | null>()
const LEADING_SLASH = /^\//
const BLANK_RUN = /[ \t]+/g
let generatedDeclaration: RegExp | null | undefined

function declaredGenerator(lines: string[]): string | undefined {
  if (generatedDeclaration === undefined) {
    try {
      generatedDeclaration = new RegExp(GENERATED_DECLARATION, 'i')
    } catch {
      generatedDeclaration = null
    }
  }
  if (generatedDeclaration === null) return undefined
  for (const line of lines) {
    const m = line.match(generatedDeclaration)
    if (!m) continue
    const script = m.slice(1).find(group => group !== undefined)
    if (script !== undefined) return script
  }
  return undefined
}

function cachedGeneratedPaths(rule: WardRule): Array<{ re: RegExp; row: GeneratedPath }> {
  let rows = compiledGeneratedPaths.get(rule)
  if (rows === undefined) {
    rows = []
    for (const row of rule.generatedPaths ?? []) {
      try {
        rows.push({ re: new RegExp(row.pattern), row })
      } catch {
        continue
      }
    }
    compiledGeneratedPaths.set(rule, rows)
  }
  return rows
}

function cachedLeadingMarker(rule: WardRule): RegExp | null {
  let re = compiledLeadingMarkers.get(rule)
  if (re === undefined) {
    try {
      re = rule.leadingMarker === undefined ? null : new RegExp(rule.leadingMarker, 'i')
    } catch {
      re = null
    }
    compiledLeadingMarkers.set(rule, re)
  }
  return re
}

function leadingMarkerHit(re: RegExp, head: string): { excerpt: string; line: number; generator?: string } | null {
  const lines = head.slice(0, GENERATED_HEAD_CHARS).split('\n', GENERATED_HEAD_LINES)
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i]!.match(re)
    if (!m || m[0] === undefined) continue
    const generator = declaredGenerator(lines)
    return generator === undefined ? { excerpt: m[0].slice(0, 80), line: i + 1 } : { excerpt: m[0].slice(0, 80), line: i + 1, generator }
  }
  return null
}

function cachedPathRegex(
  map: WeakMap<WardRule, RegExp | null>,
  rule: WardRule,
  source: string,
): RegExp | null {
  let re = map.get(rule)
  if (re === undefined) {
    try {
      re = new RegExp(source)
    } catch {
      re = null
    }
    map.set(rule, re)
  }
  return re
}

function compile(rule: WardRule): RegExp[] {
  const cached = compiledPatterns.get(rule)
  if (cached !== undefined) return cached
  const out: RegExp[] = []
  for (const src of rule.patterns) {
    try {
      out.push(new RegExp(src, rule.flags ?? 'u'))
    } catch {
    }
  }
  compiledPatterns.set(rule, out)
  return out
}

function isCommentLine(line: string): boolean {
  const t = line.trimStart()
  return t.startsWith('//') || t.startsWith('*') || t.startsWith('/*')
}

function editedText(input: Record<string, unknown>): string {
  const parts: string[] = []
  if (typeof input.new_string === 'string') parts.push(input.new_string)
  if (typeof input.new_source === 'string') parts.push(input.new_source)
  if (Array.isArray(input.hunks)) {
    for (const hunk of input.hunks) {
      const replace = hunk !== null && typeof hunk === 'object' ? (hunk as { replace?: unknown }).replace : undefined
      if (typeof replace === 'string') parts.push(replace)
    }
  }
  if (typeof input.append === 'string') parts.push(input.append)
  return parts.join('\n')
}

type WardTarget = {
  scope: WardScope
  path: string
  text: string
  oldText: string | undefined
  whole: boolean
  asGiven?: boolean
}

function editTarget(path: string, text: string): WardTarget {
  return { scope: 'edit', path, text, oldText: undefined, whole: false }
}

function stringOf(value: unknown): string {
  return typeof value === 'string' ? value : ''
}

function patchTargets(patch: string): WardTarget[] {
  const out: WardTarget[] = []
  let path: string | null = null
  let body: string[] = []
  const flush = (): void => {
    if (path !== null) out.push(editTarget(path, body.join('\n')))
    path = null
    body = []
  }
  for (const raw of patch.split('\n')) {
    if (raw === '|') {
      body.push('')
      continue
    }
    if (raw.startsWith('| ')) {
      body.push(raw.slice(2))
      continue
    }
    const tokens = raw.trim().split(/\s+/)
    if (tokens[0] === 'file' && tokens.length >= 2) {
      flush()
      path = tokens[1]!
    } else if (tokens[0] === 'move-to' && tokens.length >= 2) {
      out.push(editTarget(tokens[1]!, ''))
    }
  }
  flush()
  return out
}

function extractTargets(pending: PendingToolCall): WardTarget[] {
  const input = pending.input
  if (EDIT_TOOLS.has(pending.toolName)) {
    return [
      {
        scope: 'edit',
        path: String(input.file_path ?? input.notebook_path ?? ''),
        text: editedText(input),
        oldText: typeof input.old_string === 'string' ? input.old_string : undefined,
        whole: false,
      },
    ]
  }
  if (WRITE_TOOLS.has(pending.toolName)) {
    return [{ scope: 'edit', path: String(input.file_path ?? ''), text: String(input.content ?? ''), oldText: undefined, whole: true }]
  }
  if (CHANGESET_TOOLS.has(pending.toolName)) {
    const out: WardTarget[] = []
    if (Array.isArray(input.changes)) {
      for (const change of input.changes) {
        if (change === null || typeof change !== 'object') continue
        const member = change as Record<string, unknown>
        out.push(editTarget(String(member.file_path ?? ''), editedText(member)))
      }
    }
    if (typeof input.patch === 'string') out.push(...patchTargets(input.patch))
    return out
  }
  if (AST_EDIT_TOOLS.has(pending.toolName)) {
    return [editTarget(stringOf(input.path), stringOf(input.rewrite))]
  }
  if (STRUCTURE_TOOLS.has(pending.toolName)) {
    const parts = [input.replacement, input.out, input.newValue, input.to, input.newModule].filter(part => typeof part === 'string')
    return parts.length === 0 ? [] : [editTarget('', parts.join('\n'))]
  }
  if (GIT_TOOLS.has(pending.toolName)) {
    if (input.op !== 'resolve' || typeof input.content !== 'string') return []
    return [{ scope: 'edit', path: stringOf(input.path), text: input.content, oldText: undefined, whole: true, asGiven: true }]
  }
  if (LSP_TOOLS.has(pending.toolName)) {
    if (input.apply !== true) return []
    return [input.filePath, input.targetPath, input.newPath].filter(path => typeof path === 'string' && path !== '').map(path => editTarget(path as string, ''))
  }
  if (pending.shellCommand !== undefined) {
    return [{ scope: 'bash', path: '', text: pending.shellCommand, oldText: undefined, whole: false }]
  }
  return []
}

function normalisePath(path: string): string {
  const absolute = path.startsWith('/')
  const out: string[] = []
  for (const segment of path.split('/')) {
    if (segment === '' || segment === '.') continue
    if (segment === '..') {
      if (out.length > 0 && out[out.length - 1] !== '..') out.pop()
      else if (!absolute) out.push('..')
      continue
    }
    out.push(segment)
  }
  return (absolute ? '/' : '') + out.join('/')
}

function bindPath(target: WardTarget, pending: PendingToolCall): { relative: string; absolute: string } {
  const given = normalisePath(target.path)
  if (target.asGiven === true && !given.startsWith('/')) return { relative: given, absolute: '' }
  const resolved = pending.resolvePath?.(given) ?? { path: given, root: undefined }
  const path = resolved.path
  if (resolved.root !== undefined && resolved.root !== '') {
    const base = resolved.root.endsWith('/') ? resolved.root : `${resolved.root}/`
    if (path.startsWith(base)) return { relative: path.slice(base.length), absolute: path }
  }
  if (!path.startsWith('/')) return { relative: path, absolute: path }
  return { relative: path.slice(path.lastIndexOf('/') + 1), absolute: path }
}

export function evaluateWards(
  rules: readonly WardRule[],
  pending: PendingToolCall,
): WardVerdict {
  for (const target of extractTargets(pending)) {
    const verdict = evaluateTarget(rules, pending, target)
    if (!verdict.allow) return verdict
  }
  return { allow: true }
}

function evaluateTarget(rules: readonly WardRule[], pending: PendingToolCall, target: WardTarget): WardVerdict {
  let words: string | undefined
  let oldFolded: string | undefined
  let head: string | undefined | null = null
  let bound: { relative: string; absolute: string } | null = null

  for (const rule of rules) {
    if (rule.scope !== target.scope) continue
    if (target.scope === 'edit') {
      if (rule.pathPattern) {
        const re = cachedPathRegex(compiledPathPatterns, rule, rule.pathPattern)
        if (re === null || !re.test(target.path)) continue
      }
      if (rule.allowPathPattern) {
        const re = cachedPathRegex(compiledAllowPathPatterns, rule, rule.allowPathPattern)
        if (re !== null && re.test(target.path)) continue
      }
      if (rule.generatedPaths !== undefined && target.path) {
        if (bound === null) bound = bindPath(target, pending)
        for (const { re, row } of cachedGeneratedPaths(rule)) {
          const m = re.exec(bound.relative)
          if (!m) continue
          return {
            allow: false,
            rule,
            excerpt: m[0].replace(LEADING_SLASH, '').slice(0, 80),
            line: 0,
            target: target.path,
            ...(row.generator === undefined ? {} : { generator: row.generator }),
            ...(row.sources === undefined ? {} : { sources: row.sources }),
            ...(row.check === undefined ? {} : { check: row.check }),
          }
        }
      }
      const marker = rule.leadingMarker === undefined ? null : cachedLeadingMarker(rule)
      if (marker !== null) {
        if (head === null) {
          if (bound === null && target.path !== '') bound = bindPath(target, pending)
          head = bound !== null && bound.absolute !== '' && pending.readHead !== undefined ? pending.readHead(bound.absolute) : undefined
        }
        const hit = (head === undefined ? null : leadingMarkerHit(marker, head)) ?? (target.whole ? leadingMarkerHit(marker, target.text) : null)
        if (hit !== null) {
          return {
            allow: false,
            rule,
            excerpt: hit.excerpt,
            line: hit.line,
            target: target.path || pending.toolName,
            ...(hit.generator === undefined ? {} : { generator: hit.generator }),
          }
        }
      }
    }
    if (!target.text) continue
    const regexes = compile(rule)
    if (regexes.length === 0) continue

    const skipComments = rule.skipCommentLines !== false
    const fold = rule.foldLines === true
    const text = rule.outsideQuotes === true && target.scope === 'bash' ? (words ??= commandOutsideQuotes(target.text)) : target.text
    const lines = text.split('\n')
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i] ?? ''
      if (skipComments && isCommentLine(line)) continue
      const view = fold ? line.trim().replace(BLANK_RUN, ' ') : line
      for (const re of regexes) {
        const m = view.match(re)
        if (!m || m[0] === undefined) continue
        if (rule.newContentOnly && target.oldText !== undefined) {
          const previous = fold ? (oldFolded ??= target.oldText.replace(BLANK_RUN, ' ')) : target.oldText
          if (previous.includes(m[0])) continue
        }
        return {
          allow: false,
          rule,
          excerpt: m[0].slice(0, 80),
          line: i + 1,
          target: target.path || pending.toolName,
        }
      }
    }
  }
  return { allow: true }
}

export function parseProjectWardsWithReport(jsonText: string): {
  rules: WardRule[]
  problems: string[]
  loss?: string
} {
  const problems: string[] = []
  let parsed: unknown
  try {
    parsed = JSON.parse(jsonText)
  } catch (error) {
    problems.push(
      `wards.json is not valid JSON (${error instanceof Error ? error.message.slice(0, 80) : 'parse error'}) — every project ward is inactive`,
    )
    return { rules: [], problems, loss: 'not valid JSON — its safety rules are OFF' }
  }
  if (!Array.isArray(parsed)) {
    problems.push('wards.json must be a JSON ARRAY of rules — every project ward is inactive')
    return { rules: [], problems, loss: 'not a JSON array of rules — its safety rules are OFF' }
  }
  const out: WardRule[] = []
  for (let i = 0; i < parsed.length; i++) {
    const entry: unknown = parsed[i]
    const label = (): string => {
      const e = entry as Record<string, unknown> | null
      return e && typeof e.name === 'string' && e.name ? `'${e.name}'` : `#${i + 1}`
    }
    if (!entry || typeof entry !== 'object' || Array.isArray(entry)) {
      problems.push(`rule ${label()} is not an object — dropped`)
      continue
    }
    const e = entry as Record<string, unknown>
    const name = typeof e.name === 'string' && e.name ? e.name : `project-rule-${i + 1}`
    if (name !== e.name) problems.push(`rule #${i + 1} has no name — kept as '${name}'`)
    let teach = typeof e.teach === 'string' && e.teach ? e.teach : ''
    if (!teach) {
      teach = `Denied by project ward '${name}' (.mercury/wards.json); the rule carries no teach text.`
      problems.push(`rule '${name}' has no teach text — a default was synthesized (the deny still stands)`)
    }
    const scopeRaw = e.scope
    const scopeFolded = typeof scopeRaw === 'string' ? scopeRaw.trim().toLowerCase() : ''
    if (scopeFolded !== 'edit' && scopeFolded !== 'bash') {
      problems.push(
        `rule '${name}' scope ${JSON.stringify(scopeRaw)} is not 'edit' or 'bash' — dropped (it can guard nothing)`,
      )
      continue
    }
    if (scopeFolded !== scopeRaw) problems.push(`rule '${name}' scope ${JSON.stringify(scopeRaw)} folded to '${scopeFolded}'`)
    let flags: string | undefined
    if (typeof e.flags === 'string') {
      const cleaned = e.flags.replace(/\s+/g, '')
      if (cleaned !== e.flags) problems.push(`rule '${name}' flags ${JSON.stringify(e.flags)} cleaned to '${cleaned}'`)
      if (cleaned) {
        try {
          new RegExp('', cleaned)
          flags = cleaned
        } catch {
          problems.push(`rule '${name}' flags '${cleaned}' are not valid regex flags — using the default 'u'`)
          flags = undefined
        }
      }
    } else if (e.flags !== undefined) {
      problems.push(`rule '${name}' flags must be a string — using the default 'u'`)
    }
    if (!Array.isArray(e.patterns)) {
      problems.push(`rule '${name}' has no patterns list — dropped`)
      continue
    }
    const patterns: string[] = []
    for (const p of e.patterns) {
      if (typeof p !== 'string') {
        problems.push(`rule '${name}' carries a non-string pattern — that pattern is dropped`)
        continue
      }
      try {
        new RegExp(p, flags ?? 'u')
        patterns.push(p)
      } catch {
        problems.push(`rule '${name}' pattern ${JSON.stringify(p.slice(0, 40))} does not compile — that pattern is dropped`)
      }
    }
    if (patterns.length === 0) {
      problems.push(`rule '${name}' has no usable pattern left — dropped`)
      continue
    }
    out.push({
      name,
      teach,
      scope: scopeFolded,
      patterns,
      flags,
      pathPattern: typeof e.pathPattern === 'string' ? e.pathPattern : undefined,
      allowPathPattern:
        typeof e.allowPathPattern === 'string' ? e.allowPathPattern : undefined,
      newContentOnly: e.newContentOnly === true,
      skipCommentLines:
        typeof e.skipCommentLines === 'boolean' ? e.skipCommentLines : undefined,
    })
  }
  const dropped = parsed.length - out.length
  return dropped > 0
    ? { rules: out, problems, loss: `${dropped} of ${parsed.length} rules unreadable — dropped` }
    : { rules: out, problems }
}

export function parseProjectWardsDetailed(jsonText: string): {
  rules: WardRule[]
  problem?: string
} {
  const { rules, loss } = parseProjectWardsWithReport(jsonText)
  return loss === undefined ? { rules } : { rules, problem: loss }
}

export function parseProjectWards(jsonText: string): WardRule[] {
  return parseProjectWardsWithReport(jsonText).rules
}

export function buildWardDenial(
  verdict: Extract<WardVerdict, { allow: false }>,
  toolName: string,
): string {
  const closing =
    verdict.rule.refusal === true
      ? 'Do not rephrase the command to evade this rule — surface the refusal to the operator instead.'
      : 'This rule is mechanical: re-issuing the same content will be denied again; rewrite the call to comply.'
  const where = verdict.line > 0 ? `${verdict.target}:${verdict.line}` : verdict.target
  const road =
    (verdict.sources === undefined ? '' : ` Source: ${verdict.sources}.`) +
    (verdict.generator === undefined ? '' : ` Regenerated by: ${verdict.generator}.`) +
    (verdict.check === undefined
      ? ''
      : verdict.check === null
        ? ' The commit gate refuses the drift.'
        : ` The commit gate refuses the drift; its check: ${verdict.check}.`)
  return (
    `Ward '${verdict.rule.name}' blocked this ${toolName} call — matched ` +
    `"${verdict.excerpt}" (${where}). ${verdict.rule.teach}${road} ${closing}`
  )
}
