#!/usr/bin/env node
// regen-addon — assets/vulcan/addon/** → src/services/vulcan/addonFiles.generated.ts
// (the regen-wrapper pattern; `--check` drift-gates the vulcan suite). The addon
// ships INSIDE the single-file bundle; vulcan_install materializes it into a
// project. Deterministic: files sorted, digest over the sorted (path, content)
// stream.
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const addonRoot = join(repo, 'assets', 'vulcan', 'addon')
const outPath = join(repo, 'src', 'services', 'vulcan', 'addonFiles.generated.ts')

function walk(dir) {
  const out = []
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) out.push(...walk(p))
    else out.push(p)
  }
  return out
}

let files
try {
  files = walk(addonRoot)
    .map(p => ({ path: relative(addonRoot, p).split('\\').join('/'), content: readFileSync(p, 'utf8') }))
    .sort((a, b) => (a.path < b.path ? -1 : 1))
} catch {
  console.error(`regen-addon: no addon sources at ${addonRoot}`)
  process.exit(1)
}
if (files.length === 0) {
  console.error('regen-addon: addon dir is empty — nothing to embed')
  process.exit(1)
}

const h = createHash('sha256')
for (const f of files) h.update(f.path).update('\0').update(f.content).update('\0')
const digest = h.digest('hex')

const generated = `// GENERATED by scripts/vulcan/regen-addon.mjs from assets/vulcan/addon/ — DO NOT EDIT.
// Regenerate: node scripts/vulcan/regen-addon.mjs   (drift-gated by --check in scripts/vulcan/)

export interface VulcanAddonFile {
  /** Path relative to <project>/addons/mercury_vulcan/ */
  path: string
  content: string
}

export const VULCAN_ADDON_DIGEST = '${digest}'

export const VULCAN_ADDON_FILES: readonly VulcanAddonFile[] = ${JSON.stringify(files, null, 2)}
`

if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(outPath, 'utf8')
  } catch {
    console.error('regen-addon --check: generated module missing — run the regen')
    process.exit(1)
  }
  if (current !== generated) {
    console.error('regen-addon --check: DRIFT between assets/vulcan/addon/ and addonFiles.generated.ts — run: node scripts/vulcan/regen-addon.mjs')
    process.exit(1)
  }
  console.log(`regen-addon --check: clean (${files.length} files, digest ${digest.slice(0, 12)}…)`)
  process.exit(0)
}

writeFileSync(outPath, generated)
console.log(`regen-addon: wrote ${outPath} (${files.length} files, digest ${digest.slice(0, 12)}…)`)
