#!/usr/bin/env node
// regen-optable — assets/vulcan/optable.json → src/utils/vulcan/optable.generated.ts
// AND assets/vulcan/addon/core/op_classes.gd (the editor-side op→class table the
// ctx.op_class seam reads; frontier's batch_transaction validates against it).
// The regen-wrapper pattern: both generated files are committed; `--check`
// re-derives and fails on drift so the trio can never silently diverge.
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const srcPath = join(repo, 'assets', 'vulcan', 'optable.json')
const outPath = join(repo, 'src', 'utils', 'vulcan', 'optable.generated.ts')
const gdOutPath = join(repo, 'assets', 'vulcan', 'addon', 'core', 'op_classes.gd')

const raw = readFileSync(srcPath, 'utf8')
const digest = createHash('sha256').update(raw).digest('hex')
const table = JSON.parse(raw)
if (table.version !== 1 || !Array.isArray(table.categories)) {
  console.error('regen-optable: optable.json shape unexpected (want {version:1, categories:[…]})')
  process.exit(1)
}

const ops = []
const seen = new Set()
for (const cat of table.categories) {
  if (!cat.key || !Array.isArray(cat.ops)) {
    console.error(`regen-optable: bad category ${JSON.stringify(cat.key)}`)
    process.exit(1)
  }
  for (const op of cat.ops) {
    if (!op.name || !['read', 'mutate', 'exec'].includes(op.class) || typeof op.lite !== 'boolean' || !op.summary) {
      console.error(`regen-optable: bad op ${JSON.stringify(op.name)} in ${cat.key}`)
      process.exit(1)
    }
    if (seen.has(op.name)) {
      console.error(`regen-optable: duplicate op ${op.name}`)
      process.exit(1)
    }
    seen.add(op.name)
    ops.push({
      name: op.name,
      category: cat.key,
      cls: op.class,
      lite: op.lite,
      summary: op.summary,
      args: op.args ?? {},
    })
  }
}

const header = `// GENERATED by scripts/vulcan/regen-optable.mjs from assets/vulcan/optable.json — DO NOT EDIT.
// Regenerate: node scripts/vulcan/regen-optable.mjs   (drift-gated by --check in scripts/vulcan/)

export interface VulcanOp {
  name: string
  category: string
  cls: 'read' | 'mutate' | 'exec'
  lite: boolean
  summary: string
  /** arg name → short human type/shape note (validation is editor-side). */
  args: Readonly<Record<string, string>>
}

export const VULCAN_OPTABLE_DIGEST = '${digest}'

export const VULCAN_OPS: readonly VulcanOp[] = `

const body = JSON.stringify(ops, null, 2)
const footer = ` as const

const byName = new Map(VULCAN_OPS.map(o => [o.name, o]))

export function vulcanOp(name: string): VulcanOp | undefined {
  return byName.get(name)
}

export function vulcanOpNames(opts?: { lite?: boolean }): string[] {
  return VULCAN_OPS.filter(o => (opts?.lite ? o.lite : true)).map(o => o.name)
}

export function vulcanCategories(): string[] {
  return [...new Set(VULCAN_OPS.map(o => o.category))]
}
`

const generated = header + body + footer

const gdGenerated = `# GENERATED by scripts/vulcan/regen-optable.mjs from assets/vulcan/optable.json — DO NOT EDIT.
# Regenerate: node scripts/vulcan/regen-optable.mjs   (drift-gated by --check in scripts/vulcan/)
# The editor-side op → permission-class table (ctx.op_class): read | mutate | exec.
# core/server.gd preloads this; no class_name on purpose (never a global).
@tool
extends RefCounted

const CLASSES := {
${ops.map(o => `\t"${o.name}": "${o.cls}",`).join('\n')}
}

static func of(op: String) -> String:
\treturn String(CLASSES.get(op, ""))
`

if (process.argv.includes('--check')) {
  const targets = [
    [outPath, generated, 'optable.generated.ts'],
    [gdOutPath, gdGenerated, 'addon/core/op_classes.gd'],
  ]
  for (const [p, want, label] of targets) {
    let current = ''
    try {
      current = readFileSync(p, 'utf8')
    } catch {
      console.error(`regen-optable --check: ${label} missing — run the regen`)
      process.exit(1)
    }
    if (current !== want) {
      console.error(`regen-optable --check: DRIFT between optable.json and ${label} — run: node scripts/vulcan/regen-optable.mjs`)
      process.exit(1)
    }
  }
  console.log(`regen-optable --check: clean (${ops.length} ops, digest ${digest.slice(0, 12)}…)`)
  process.exit(0)
}

writeFileSync(outPath, generated)
writeFileSync(gdOutPath, gdGenerated)
console.log(`regen-optable: wrote ${outPath} + ${gdOutPath} (${ops.length} ops, digest ${digest.slice(0, 12)}…)`)
