// AUTO-GENERATED by scripts/skills/gen-bundled.ts — DO NOT EDIT BY HAND.
// Source of truth: mercury-skills/drafting-partner/. Re-run the codegen to update.
import skillMd from './drafting-partner/SKILL.md'
import ref_scripts_outline_check_py from './drafting-partner/scripts/outline_check.py'

export const SKILL_MD: string = skillMd

export const SKILL_FILES: Record<string, string> = {
  "scripts/outline_check.py": ref_scripts_outline_check_py,
}
