// AUTO-GENERATED by scripts/skills/gen-bundled.ts — DO NOT EDIT BY HAND.
// Source of truth: mercury-skills/pdf-documents/. Re-run the codegen to update.
import skillMd from './pdf-documents/SKILL.md'
import ref_scripts_pdf_pages_py from './pdf-documents/scripts/pdf_pages.py'

export const SKILL_MD: string = skillMd

export const SKILL_FILES: Record<string, string> = {
  "scripts/pdf_pages.py": ref_scripts_pdf_pages_py,
}
