// AUTO-GENERATED by scripts/skills/gen-bundled.ts — DO NOT EDIT BY HAND.
// Source of truth: mercury-skills/skill-forge/. Re-run the codegen to update.
import skillMd from './skill-forge/SKILL.md'
import ref_scripts_skill_lint_py from './skill-forge/scripts/skill_lint.py'

export const SKILL_MD: string = skillMd

export const SKILL_FILES: Record<string, string> = {
  "scripts/skill_lint.py": ref_scripts_skill_lint_py,
}
