// AUTO-GENERATED by scripts/skills/gen-bundled.ts — DO NOT EDIT BY HAND.
// Source of truth: mercury-skills/slide-decks/. Re-run the codegen to update.
import skillMd from './slide-decks/SKILL.md'
import ref_scripts_deck_outline_py from './slide-decks/scripts/deck_outline.py'

export const SKILL_MD: string = skillMd

export const SKILL_FILES: Record<string, string> = {
  "scripts/deck_outline.py": ref_scripts_deck_outline_py,
}
