// AUTO-GENERATED by scripts/skills/gen-bundled.ts — DO NOT EDIT BY HAND.
// Source of truth: mercury-skills/word-documents/. Re-run the codegen to update.
import skillMd from './word-documents/SKILL.md'
import ref_scripts_docx_outline_py from './word-documents/scripts/docx_outline.py'

export const SKILL_MD: string = skillMd

export const SKILL_FILES: Record<string, string> = {
  "scripts/docx_outline.py": ref_scripts_docx_outline_py,
}
