export const ASEPRITE_TOOL_NAME = 'Aseprite' as const

export function getAsepriteToolDescription(): string {
  return `Drive the local Aseprite in its own BATCH mode (aseprite -b — the GUI is never launched): sprite census, exports and sprite sheets with the real CLI options, new sprites, and Lua scripts. Every operation is one bounded background run against the binary the resolution law finds (MERCURY_ASEPRITE_BIN pin > PATH > the app bundles > the Steam library > the win32 installer/itch roots); results carry the file acted on, the output files with their bytes verified on disk, and the binary's version. No Aseprite on the box ⇒ every op answers with the install roads by name — nothing is ever installed or launched for you.

op:"status" — the resolution verdict (which rung found the binary, or the precise unavailable naming every road probed), the version from the binary's own --version, and the sprite census of the working tree (.aseprite/.ase, bounded walk).
op:"info" (file) — the sprite's truth via a bundled read-only Lua probe: size, color mode, frame count + per-frame durations, the layer tree (groups, visibility), animation tags (0-based from/to, matching frameRange), slices, palette size.
op:"export" (file, output, …options) — the CLI's real export surface. Plain road: --save-as to the output (png/gif/webp/bmp/tga/jpg by extension; a multi-frame sprite saved to a still format writes one file per frame with the frame number inserted — or use tag/frameRange to choose frames, or {frame} in the output name to place the number). Sheet road (selected by sheetType or dataOutput): --sheet with layout sheetType (horizontal · vertical · rows · columns · packed), sheetColumns/sheetRows, and optional dataOutput (+dataFormat json-hash|json-array) writing the engine-ready JSON metadata beside the image. Shared options: scale (resize factor), layer/ignoreLayer (repeatable), allLayers (include hidden), tag, frameRange "from,to" (0-based), splitLayers/splitTags ({layer}/{tag} templates land in the output name), trim, ignoreEmpty, mergeDuplicates, borderPadding/shapePadding/innerPadding. The result verifies bytes landed and lists the produced files.
op:"create" (output, width, height, colorMode?) — a new sprite born via a bundled Lua program (rgb · indexed · gray; .aseprite/.ase native by extension, or any exportable format). The result verifies the file's bytes.
op:"run-script" (source, file?, params?, timeoutMs?) — YOUR Lua against the app's full scripting API (app, Sprite, io — the whole surface), optionally with a sprite file opened first; params land as app.params key/values. This is the road for everything the fixed verbs do not cover (palettes, cel edits, tilesets, batch renames) and the ONE road that may touch files outside the working tree.

PATHS: file/output/dataOutput resolve against the working directory and are FENCED inside it for info/export/create — the refusal names the tree and the remedy (run-script, behind its own ask, is the out-of-tree road). Split/multi-frame exports may use {layer}/{tag}/{frame} templates in output; the fence checks the template's directory.

PERMISSIONS: status/info are reads — never ask. export and create ask naming source and destination(s). run-script ALWAYS asks carrying the code's byte count and first line — the script runs with the app's own authority (it can modify sprites and write files as you; there is no sandbox beyond a bounded deadline, and a runaway script is killed at it).

BOUNDS: every spawn is deadline-killed (status/info 15s · create 30s · export 60s · run-script 60s default, timeoutMs caps at 120s) with stdout/stderr capped honestly. Scripting needs a script-capable Aseprite (the store builds all are); an older binary's own error is carried, never guessed at.`
}
