#!/usr/bin/env bun
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { CURRENT_NOTICE_SLOTS } from '../../src/constants/legalNotice.js'

const ROOT = join(import.meta.dir, '..', '..')

type Row = { name: string; version: string; license: string; homepage?: string }

function pkgMeta(name: string): Row {
  const p = join(ROOT, 'node_modules', name, 'package.json')
  if (!existsSync(p)) return { name, version: 'not installed', license: 'UNKNOWN — package not installed' }
  const j = JSON.parse(readFileSync(p, 'utf8')) as {
    version?: string
    license?: string | { type?: string }
    homepage?: string
    repository?: { url?: string } | string
  }
  const license =
    typeof j.license === 'string' ? j.license : (j.license?.type ?? 'UNKNOWN')
  const repo =
    typeof j.repository === 'string' ? j.repository : j.repository?.url
  return {
    name,
    version: j.version ?? '?',
    license,
    homepage: j.homepage ?? repo,
  }
}

const rootPkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as {
  version: string
  dependencies?: Record<string, string>
}
const runtime = Object.keys(rootPkg.dependencies ?? {}).sort()
const rows = runtime.map(pkgMeta)

const byLicense = new Map<string, Row[]>()
for (const r of rows) {
  const list = byLicense.get(r.license) ?? []
  list.push(r)
  byLicense.set(r.license, list)
}

function vendorLock(file: string): { version?: string; license?: string; url?: string; repository?: string } {
  const p = join(ROOT, 'vendor', file)
  if (!existsSync(p)) return {}
  return JSON.parse(readFileSync(p, 'utf8')) as { version?: string; license?: string; url?: string; repository?: string }
}
const debugpy = vendorLock('debugpy.lock.json')
const pyright = vendorLock('pyright.lock.json')
const jsDebug = vendorLock('js-debug.lock.json')
const nodeRuntime = vendorLock('node.lock.json')
const brush = vendorLock('brush.lock.json')
const tsMeta = pkgMeta('typescript')
const treeSitterMeta = pkgMeta('@vscode/tree-sitter-wasm')
const ripgrepMeta = pkgMeta('@vscode/ripgrep')

interface FoundNotice {
  pkg: string
  version: string
  file: string
  content: string
}
function sweepNoticeFiles(): FoundNotice[] {
  const found: FoundNotice[] = []
  const NOTICE_RE = /^NOTICE(\.(txt|md))?$/i
  const walk = (dir: string): void => {
    let entries: string[]
    try {
      entries = readdirSync(dir)
    } catch {
      return
    }
    const hasPkgJson = entries.includes('package.json')
    if (hasPkgJson) {
      for (const e of entries) {
        if (NOTICE_RE.test(e) && statSync(join(dir, e)).isFile()) {
          let name = dir
          let version = '?'
          try {
            const meta = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) as { name?: string; version?: string }
            name = meta.name ?? dir
            version = meta.version ?? '?'
          } catch {
          }
          found.push({ pkg: name, version, file: e, content: readFileSync(join(dir, e), 'utf8') })
        }
      }
    }
    for (const e of entries) {
      if (e === '.bin' || e === '.cache') continue
      const full = join(dir, e)
      try {
        if (statSync(full).isDirectory()) walk(full)
      } catch {
      }
    }
  }
  walk(join(ROOT, 'node_modules'))
  return found.sort((a, b) => (a.pkg < b.pkg ? -1 : a.pkg > b.pkg ? 1 : 0))
}
const preservedNotices = sweepNoticeFiles()

const lines: string[] = []
lines.push('# Third-party notices — Mercury')
lines.push('')
if (CURRENT_NOTICE_SLOTS.copyrightLine) lines.push(CURRENT_NOTICE_SLOTS.copyrightLine, '')
if (CURRENT_NOTICE_SLOTS.licensePointer) lines.push(CURRENT_NOTICE_SLOTS.licensePointer, '')
lines.push(
  `Generated by \`scripts/distribution/generate-third-party-notices.ts\` from the actual dependency truth (package.json + bun.lock + the checked-in vendor lock receipts) for Mercury ${rootPkg.version}. Regenerate after any dependency or vendor change; \`scripts/distribution/prove-distribution-notices.ts\` fails the gate when this file drifts from the lockfile truth. Mercury is published under the Business Source License 1.1 (LICENSE.md) — this inventory records each third-party body, its licence identifier, and where the applicable licence text is retained.`,
)
lines.push('')
lines.push('## Bundled runtime packages')
lines.push('')
lines.push(
  `The built artifact (\`dist/mercury.mjs\`) is a self-contained bundle that inlines the ${rows.length} runtime packages below (versions = the installed/bun.lock resolutions). Full licence texts are retained in each package's \`node_modules/<name>/\` tree in the source checkout; per-file copyright headers survive inside the bundle where the sources carried them.`,
)
lines.push('')
for (const [license, list] of [...byLicense.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  lines.push(`### ${license}`)
  lines.push('')
  for (const r of list.sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(`- **${r.name}** ${r.version}${r.homepage ? ` — ${r.homepage}` : ''}`)
  }
  lines.push('')
}
lines.push('## Vendored tool payloads (`dist/vendor/`)')
lines.push('')
lines.push(
  `- **ripgrep** (via ${ripgrepMeta.name} ${ripgrepMeta.version}, ${ripgrepMeta.license}) — the platform search binary, © the ripgrep contributors, dual-licensed MIT / UNLICENSE (https://github.com/BurntSushi/ripgrep). Redistributed unmodified; the wrapper package's licence text lives at node_modules/@vscode/ripgrep/LICENSE.`,
)
lines.push(
  `- **debugpy** ${debugpy.version ?? '(not vendored on this checkout)'} — Microsoft, ${debugpy.license ?? 'MIT'} (${debugpy.url ?? 'https://github.com/microsoft/debugpy'}). Receipt: vendor/debugpy.lock.json; licence text ships at dist/vendor/debugpy/…/licenses/LICENSE + ThirdPartyNotices.txt.`,
)
lines.push(
  `- **pyright** ${pyright.version ?? '(not vendored on this checkout)'} — Microsoft, ${pyright.license ?? 'MIT'} (${pyright.url ?? 'https://github.com/microsoft/pyright'}). Receipt: vendor/pyright.lock.json; licence text ships at dist/vendor/pyright/LICENSE.txt (+ typeshed LICENSE).`,
)
lines.push(
  `- **js-debug** ${jsDebug.version ?? '(not vendored on this checkout)'} — Microsoft, ${jsDebug.license ?? 'MIT'} (${jsDebug.url ?? 'https://github.com/microsoft/vscode-js-debug'}). Receipt: vendor/js-debug.lock.json; licence text ships at dist/vendor/js-debug/LICENSE.`,
)
lines.push(
  `- **TypeScript compiler** ${tsMeta.version} — Microsoft, ${tsMeta.license} (https://github.com/microsoft/TypeScript). Vendored from the repo devDependency; licence text ships at dist/vendor/typescript/LICENSE.txt.`,
)
lines.push(
  `- **tree-sitter WASM engine + grammars** (${treeSitterMeta.name} ${treeSitterMeta.version}) — Microsoft, ${treeSitterMeta.license} (https://github.com/microsoft/vscode-tree-sitter-wasm). Licence text ships at dist/vendor/treesitter/LICENSE.`,
)
{
  const grammarsLockPath = join(ROOT, 'vendor', 'grammars.lock.json')
  if (existsSync(grammarsLockPath)) {
    const gl = JSON.parse(readFileSync(grammarsLockPath, 'utf8')) as {
      version?: string
      grammars?: Array<{ wasm: string; upstream?: { package?: string; license?: string; repository?: string } }>
    }
    const per = (gl.grammars ?? [])
      .map(g => `${g.upstream?.package ?? g.wasm} (${g.upstream?.license ?? 'unknown'}, ${g.upstream?.repository ?? ''})`)
      .join(' · ')
    lines.push(
      `- **grammar-pack extension** (tree-sitter-wasms ${gl.version ?? '?'}, pack scripts Unlicense — https://github.com/Gregoor/tree-sitter-wasms) — cherry-picked prebuilt grammar wasms; EACH grammar keeps its upstream licence: ${per}. Receipt: vendor/grammars.lock.json; the pack licence ships at dist/vendor/treesitter/LICENSE.grammar-pack and the per-grammar licence record at dist/vendor/treesitter/GRAMMAR-NOTICES.json.`,
    )
  }
}
lines.push(
  `- **Node.js runtime** ${nodeRuntime.version ?? '(not vendored on this checkout)'} — OpenJS Foundation and Node.js contributors, ${nodeRuntime.license ?? 'MIT'} (https://nodejs.org/dist/v${nodeRuntime.version ?? '<version>'}/). Receipt: vendor/node.lock.json (one official nodejs.org archive + sha256 per platform, every digest from that release's SHASUMS256.txt); the release archive ships the platform's runtime binary and Node's own LICENSE at dist/vendor/node/ — that LICENSE carries the notices of the components Node bundles (V8, libuv, OpenSSL, ICU, zlib, c-ares, nghttp2, simdjson and the rest).`,
)
{
  lines.push(
    `- **voice capture pack** (\`dist/vendor/voice/<platform>/mercury_voice.node\`) — Mercury's own Node-API addon, built from the repository's native/voice sources with cargo (never fetched). It statically links the Rust crates it depends on, chiefly cpal (Apache-2.0 / MIT, https://github.com/RustAudio/cpal) and napi-rs (MIT, https://github.com/napi-rs/napi-rs); the full per-platform crate inventory ships beside the addon as \`NOTICES.json\`, with every linked crate's licence text under \`licenses/<crate>-<version>/\`.`,
  )
}
{
  const sharpMeta = pkgMeta('sharp')
  lines.push(
    `- **image-processor pack** (\`dist/vendor/image-processor/<platform>/node_modules/@img/\`) — sharp's prebuilt binding (@img/sharp-<platform> ${sharpMeta.version}, ${sharpMeta.license}, https://github.com/lovell/sharp) and the libvips library it links (@img/sharp-libvips-<platform>, LGPL-3.0-or-later, https://github.com/lovell/sharp-libvips — its bundled dependencies and their licences are inventoried upstream at https://github.com/lovell/sharp-libvips/blob/main/THIRD-PARTY-NOTICES.md; on Windows the binding package carries the libraries itself). Redistributed unmodified from the pinned dependency; each package's LICENSE, README and versions.json ship inside the pack.`,
  )
}
lines.push(
  `- **shell engine pack** (\`dist/vendor/brush/<platform>/brush\`) — brush, a bash-compatible shell written in Rust by reuben olinsky and contributors, ${brush.license ?? 'MIT'} (${brush.repository ?? 'https://github.com/reubeno/brush'}). Receipt: vendor/brush.lock.json (one upstream release archive + sha256 per platform, every digest copied from that release's published \`<archive>.sha256\` asset); the release archive ships the platform's engine binary and upstream's own \`LICENSE\` + \`THIRD_PARTY_LICENSES.html\` (the crate notices of everything linked into the binary) at dist/vendor/brush/<platform>/.`,
)
lines.push('')
lines.push('## Preserved NOTICE files (Apache-2.0 §4(d))')
lines.push('')
if (preservedNotices.length === 0) {
  lines.push(
    'The preservation sweep walked every installed package root (transitive dependencies included) for `NOTICE`/`NOTICE.txt`/`NOTICE.md` files and found **none** in the current dependency set — the Apache-2.0 packages above (including `@anthropic-ai/sandbox-runtime`) ship a LICENSE file only. Any NOTICE file a future dependency introduces is embedded verbatim here on regeneration; `prove-notice-stamp.ts` re-runs the sweep and fails the gate if this section drifts from the installed truth.',
  )
} else {
  lines.push(
    `The preservation sweep found ${preservedNotices.length} NOTICE file(s); each is reproduced verbatim below per Apache-2.0 §4(d).`,
  )
  for (const n of preservedNotices) {
    lines.push('')
    lines.push(`### ${n.pkg} ${n.version} — ${n.file}`)
    lines.push('')
    lines.push('```text')
    lines.push(n.content.replace(/`{3}/g, '` ` `').trimEnd())
    lines.push('```')
  }
}
lines.push('')
lines.push('## Source attributions')
lines.push('')
lines.push(
  '- Parts of the terminal runtime (`src/ink/` — reconciler, DOM, styles, component shells) derive from the **Ink** project — © Vadim Demedes and contributors, MIT (https://github.com/vadimdemedes/ink). The layout engine, termio tokenizer, input byte layer and frame writer are Mercury-native.',
)
lines.push('')
lines.push(
  '- The extensions estate: archive sources are decompressed with **fflate** (MIT; a direct dependency) through the hardened reader at `src/utils/archive/zip.ts`. **@anthropic-ai/mcpb** (MIT) is retained as a dependency deliberately; the extensions estate reads no bundle files — an extension declares its servers in its own manifest — and the package stays available, with this notice, for a later bundle-backed server kind.',
)
lines.push('')
lines.push('## Bundled skills')
lines.push('')
lines.push(
  '- The skills compiled into the bundle under `src/skills/bundled/` are Mercury\'s own work and ship under the product licence.',
)
lines.push('')

writeFileSync(join(ROOT, 'THIRD_PARTY_NOTICES.md'), lines.join('\n'))
console.log(
  `THIRD_PARTY_NOTICES.md written — ${rows.length} runtime packages across ${byLicense.size} licence identifiers + 8 vendor payloads + source attributions`,
)
