
export const MERCURY_CHANGELOG = `# Mercury changelog

## 1.0.0-beta.5
- Removed the internal feature-gate table; every setting it used to answer is now plain code with the same behaviour
- Changed the sign-in list in the Logins screen, /login and the first run to start on the most recent sign-in's row when one is recorded and on the first row otherwise
- Changed /model to list only real models, with its sections as OpenAI, Anthropic, OpenRouter, then the other families; a session that has picked no model keeps the automatic default
- Removed three environment variables that had no effect: MERCURY_IDLE_THRESHOLD_MINUTES, MERCURY_IDLE_TOKEN_THRESHOLD and MERCURY_AGENT_ID
- Fixed a GPT reply whose stream closed after a tool call but before its end: the call is no longer kept in the reply's replay record without its tool use, the model is asked to continue instead, and a saved conversation that already carries such a record replays without it, so the provider no longer refuses every later request with "No tool output found for function call"
- Fixed automatic compaction retrying a summary request the provider refused for a malformed history as if it were too long: one attempt, a line naming the provider's reason and the remedies, and automatic compaction pauses for the session
- Changed the "sub-agents still running" line to say how to stop one: x twice on its row in the crew view

## 1.0.0-beta.4
- Added an optional built-in shell engine (the /config row "Shell engine" set to brush, or MERCURY_SHELL_ENGINE=brush): one persistent shell for the conversation and one per sub-agent, the same shell on every platform, and Windows no longer needs Git for Windows
- Added a "Shell engine sessions" setting that caps how many shell sessions stay alive (8 by default; MERCURY_SHELL_ENGINE_SESSIONS overrides it); an agent past the cap waits for a free one
- Added on-device speech-to-text: /speak on, space to talk, space to stop, no API key and nothing leaving the machine, once the install carries the on-device pack and you have fetched its 60 MB English model with /speak download
- Added /speak options to list the transcribers this install can use and save the one you pick
- Added a "Patience with a quiet model" setting in /config (normal, patient, custom) that sets the wait on a silent model, the retry ceiling and the recovery budget together, with environment variables as overrides
- Added a Motion setting (auto, full, reduced, off) in /config and the Boot Menu; auto slows the idle animations only while painting falls behind and says "reduced" in the status line
- Added an effort field to the Agent tool, and sub-agent defaults (model, effort, how many at once) as /config rows
- Added a browser fallback for /bug: when the GitHub CLI cannot file the report, the prefilled issue form opens in the browser
- Changed /supercode to delegate to parallel agents only when that helps, with the agents' tokens and cost shown in the turn summary
- Changed a sub-agent that hits a short provider throttle to wait it out and finish; only a limit hours away stops it, with its work kept and the parent told
- Changed a sub-agent that hits a usage limit to pause and resume at the reset; its row says why and when
- Changed the parent agent to hear from each sub-agent the moment it finishes or fails, and a wait on several agents to return at the first failure
- Changed an agent stopped mid-stream to hand back its partial work, the files it touched and the reason, resumable; one stopped by the retry budget resumes by itself once
- Changed the notice for a stream that ends with no error code and no message to name the provider, the stream's closing reason and what Mercury did next
- Changed a shell-engine command that times out, ends the shell or is stopped by you to reset that session and tell the model; a message typed during a command waits until it ends
- Changed a session to make no request of its own before your first turn; sign-in, the model requests and the update check are the only calls that leave the machine
- Changed a provider's model list to load only when something on screen needs it, once per sign-in
- Changed the usage meters to read only when shown or after a retry, never on a timer; a meter not shown for two minutes reads stale until it is shown again
- Changed a permission ask on a session you are not looking at to wait with no time limit; a sub-agent's ask still expires after ten minutes
- Changed finished background commands to collapse into one transcript line while the model is busy; a failed one keeps its title
- Changed the sign-in list in the Logins screen, /logins and the first run to put OpenAI first
- Changed voice input to prefer the on-device transcriber when its pack and model are present; a signed-in cloud transcriber serves otherwise, or when chosen with /speak options or MERCURY_VOICE_TRANSCRIBER
- Changed an option Mercury does not know to be refused with exit code 2
- Changed the stream-json feed to spell every key it defines in snake_case at every depth (feed contract 3); provider, tool, hook and permission-rule shapes keep their own spellings
- Changed a settings file written for an older version to be rewritten in place the first time it is read, a project's checked-in file included; it shows as modified once
- Changed the macOS keychain to one entry per config home; a sign-in stored by a much older build asks for one fresh sign-in
- Changed the MCP connection memory to keep a server's fingerprint instead of its full configuration
- Removed the "ultra" effort level; effort now ends at max
- Removed the .mercury/commands folder from the project command search; move a command to .mercury/skills/<name>/SKILL.md
- Updated the MCP client to the 2026-07-28 protocol revision; older servers still connect and the doctor names the revision in use
- Fixed agents stopping with "provider throttled" after a quiet or dropped stream when nothing was refused; a retry now counts only the time waited, and the stop line says how to resume
- Fixed a live but quiet model stream being cut after 90 seconds; keep-alive signals now count as signs of life
- Fixed a sub-agent with no sign of life from the model and no tool running being left as running; it is now stopped with its reason
- Fixed the crew row reading "no tokens yet" beside a growing context
- Fixed the exit prompt counting agents that had already ended and disagreeing with the crew view
- Fixed a "still running" notice lingering after a compaction for an agent that had finished, and a workflow being counted as a sub-agent
- Fixed a compaction with an OpenAI model sending a shorter request than the session, which left most of the context uncached afterwards
- Fixed a session with only an OpenAI sign-in being refused at its start
- Fixed a message to a worker inside a running workflow starting a second copy of it, and a late result from an earlier run marking a resumed agent finished
- Fixed a resumed agent losing one of its two completion notices when queued guidance restarted it
- Fixed a named foreground agent never getting its name for SendMessage, and retired names lingering after eviction
- Fixed an agent stopping without a reason after an interruption during a Stop hook or a workflow permission ask that timed out
- Fixed a workflow child's capped report ending with a bare "[outcome truncated at cap]" instead of saying where the full text is
- Fixed the /model picker dropping keys typed in its first second while a chat was still loading
- Fixed the idle screen keeping a CPU core busy on a slow machine
- Fixed the "back to the bottom" pill never appearing after PgUp or PgDn
- Fixed a background file count started at boot outliving a Mercury that exits right away
- Fixed on-device voice loading its speed-optimised pack on a CPU that cannot run it, which could end Mercury on the doctor's voice row or the first take
- Fixed the first use of voice on Windows stalling while it checked the CPU
- Fixed a file read from offset 0 numbering its lines from 0, which broke them as Edit targets
- Fixed the fallback image reader labelling PNG bytes as JPEG when the image processor is absent
- Fixed the Bash tool inserting a backslash before every ! once a command contained a single quote, which corrupted commit messages
- Fixed the Transaction tool refusing agent, transcript and workbench evidence references when noting a step or resuming
- Fixed a repeat install that changed nothing still telling you to open a new terminal
- Fixed Godot validation of a script with a class_name reporting a duplicate global class
- Fixed Workshop cells with statements and an await on one line failing with a syntax error, and braces inside strings returning the wrong value
- Fixed a Workshop workspace failing to find TypeScript when node_modules is a link
- Fixed the render_tui tool failing outside the source checkout; on a release install it now says there is no render script instead of failing
- Known on Windows with the shell engine at this version: a .cmd shim such as npm fails (run cmd /c npm … or node on the script) and a program named by a relative path after a cd is not found (use its absolute path)

## 1.0.0-beta.3
- Added GPT-6 Astra as a first-class model: it appears once a connected OpenAI account serves it, effort reaches max, and each turn is priced at the published rate
- Updated GPT-5.6 pricing to the current published rates, including the long-context tier
- Added a sixth effort level, ultra, above max, wherever the account serves it; a level the provider refuses is remembered and the nearest served level runs, with a note in the transcript
- Fixed a model switch on a stopped runner doing nothing; it now restarts the runner on the requested model, and an agent paused by a rate limit resumes when the window resets
- Fixed /model, /effort, /status, the strip, the picker, /config and /accounts disagreeing about the model being served
- Fixed the preserved-thinking notice appearing after a resume or restart even though the session kept its reasoning
- Changed the notice for dropped older reasoning after a model switch or a context trim to one quiet line instead of a warning on every message
- Fixed usage meters going stale without saying so; they now refresh themselves, show their age, and say when a read failed
- Fixed the Anthropic usage panel getting stuck on "Failed to load … HTTP 429"; it now honours the server's retry wait and says how long to wait
- Fixed a refused API key or token reading "Not logged in"; the error now names the setting to fix
- Fixed removing or switching an account being announced more than once, and added c on the sign-in cards to copy the code
- Added image paste in the composer on every platform (ctrl+v; alt+v on Windows) at any size; a large image is resized to the provider's limits and the composer says what it attached
- Changed Esc to interrupt the chat's own turn only: sub-agents and workflows keep running and the transcript says how many; in the Crew view x x stops one agent and r resumes it
- Added up arrow on an empty composer to take back a message sent while the turn was busy, before the model reads it; once read, the up arrow says so
- Changed the text before a tool call to a one-line working note that the final answer never restates
- Fixed deepthink and supercode glowing in a rainbow or mixed theme colours; they now glow in your critter's colour, in the composer and in the sent message
- Fixed selected text not following the view while scrolling, and the highlight painting outside the chat pane
- Fixed mouse drags repainting on every report, and made /mouse off stick across boots
- Fixed a mis-bound shortcut flashing "Unknown command" for a line you never typed, and a split key sequence leaking characters into the input
- Changed the chat's title bar to show the session's name instead of a ticking clock, and added how long your sub-agents have worked under the composer
- Fixed /rename being refused in every session; it now renames the session everywhere it is shown
- Added compaction progress in the chat (the stage, a bar, a clock); Esc cancels it cleanly, and a stalled or cancelled compaction keeps no half summary
- Fixed Mercury re-spawning or forgetting agents, workflows and shells after a compaction
- Fixed a false "rewrote sent history" warning when old tool results are trimmed to fit the window; it is now named as routine cleanup
- Changed the seat ceiling to one number everywhere: /seats, the Boot Menu and /config set it, idle agents no longer hold a seat, and the reading counts available memory
- Fixed a waiting agent's row not saying what it waits for, and a throttled agent's retries each spending their own budget
- Fixed sub-agents ending without saying how; they now report the real cause and what they wrote once, and a timeout is never blamed on you
- Fixed a background agent's completion arriving late in the chat; it now shows the moment it arrives, marked queued until the model reads it
- Fixed the workflow panel, the board, the crew view and the chip disagreeing about what is running, and reading "idle" right after a start instead of "not reported yet"
- Added "waiting for your answer" in the crew view and the tasks list for a sub-agent waiting on your permission
- Fixed a blocked team task not reading blocked on every screen, and creating a team hiding earlier tasks
- Fixed the Concourse close chord's hint going stale; it now does exactly what it says (stop, then archive, then delete), and a parked session reopens on one Enter
- Fixed a silent workflow stream waiting on the provider's guard instead of being cut at the stall budget
- Changed Sovereign mode to ask nothing: sensitive-file edits, ask rules and a server's ask ceiling run without a card, and the transcript says what would have asked
- Fixed the mode band showing a mode the runner did not hold; it now paints the real mode from the first frame, and a refused mode change reaches the screen with its reason
- Fixed a consent answer switching Apollo mode off; it now ends only through the review's approval or shift+tab, and writes outside the spec directory are refused
- Fixed Flow's safety check denying an action when it could not read its own verdict; it now keeps the evidence and says so
- Changed a Flow block in a session you are not looking at to wait for your answer there instead of being denied on the spot; a sub-agent's ask waits the same way
- Fixed a hook's deny decision leaving no audit row in the transcript
- Fixed consent cards overflowing the screen; a long edit or command is cut with a "+N more lines" line and ctrl+f shows the whole thing
- Fixed web search failing on a throttled request; it now cools down, answers a repeated query from the cache, and names what refused in one line
- Added Godot runtime pause, step and resume to drive a game frame by frame, and fixed the editor not being found where it lives and action presses not reaching the game's callbacks
- Fixed Unity test results landing where the editor could not write them; a bridged test run is no longer refused
- Fixed the interrupt not ending a running Bash command, and a request accepted with nothing arriving hanging instead of being named and ended
- Added /bug to show the exact report and file it through your own signed-in GitHub CLI, with every provider's key shape and GitHub tokens masked; /feedback opens the three-form chooser
- Added the Intel Mac build (macos-x64) to the release; mercury update names it on an Intel Mac
- Added release signing: archives are signed and verified before they publish, an unsigned build is announced once per install, and the archive carries the licence documents
- Changed mercury update to read the release channel anonymously, so no GitHub CLI or sign-in is needed; an update whose signature does not verify is refused
- Changed mercury install to put the command on your PATH once, and to say so when the version is already in place
- Fixed the doctor judging a headless run as a broken boot and reading the boot's rungs out of order
- Fixed a git init offer for the home directory, a drive root or a huge folder without a project marker; the doctor now names a home-directory repository and how to remove it
- Changed the project's .mercury folder to hold shared config only; machine-local files live in your Mercury home, and the doctor names any leftovers
- Fixed git and process spawns in the idle loop and at boot, and the daemon polling its own files instead of watching them
- Fixed a piped doctor --json printing more than one record or exiting before the reader drained
- Fixed a headless stream-json run not opening with its init line
- Fixed a fresh /logins not reaching hosted sessions until the daemon restarted
- Changed the companion's tips so every one is true today and teaches one thing

## 1.0.0-beta.2
- The first published build of the public line; 1.0.0-beta.1 was tagged and never published
- The repository is github.com/Whq02/MercuryCLI; the app's update channel and the release bridge read it
- The daemon runs the model a dispatch names under either field spelling; an unknown id refuses, never the default in silence
- A permission ask that expires or is withdrawn always settles its needs-you row, even when the row was still being written
- Background start-up probes never hold the process open at exit
- On the Concourse board, Enter on an example prompt fills the composer and never sends it; the next Enter sends
- The close chord is a ladder: stop, then archive, then delete; the --chat face always shows the shift-arrow key row
- The split view's size floor is the viewport's (80 columns by 22 rows)
- The status row keeps a wait's budget word on a narrow terminal; a cold model switch names its first-byte budget
- Twelve Bash tool fixes: the sandbox allows its own temp dir, pipes keep the special parameters, here-strings read, the timeout note reaches the model, an unavailable sandbox is refused and named

## 1.0.0-beta.1
- The first build published from this repository; README.md says what is inside
- Release notes ship inside the build: this bundled changelog is the only source
- The scribe and router party modes are retired; the concourse is the multi-agent path
- Release archives carry their own Node runtime; a release install needs git only
- A direct node dist/mercury.mjs start paints the launch splash before the Boot face, as the launcher does; the build ships the splash beside the bundle
- Voice input: /speak on, then space in an empty composer dictates into it through the OpenAI or Gemini API key you signed in with; audio leaves only after you stop, and Mercury never speaks aloud
- True Black is the default appearance: the same palette on a pure-black ground, on the launch splash and in the terminal; the oasis dark ground stays one row away in the first-run walk and /appearance, and a saved choice always wins
- Two per-session switches in the boot menu's Agents section, Sub-agents and Workflows: off removes the Agent or Workflow tool from that session's roster and every spawn road answers one receipt; /subagents on|off and /workflows on|off flip a running session at its next turn boundary, and the doctor names both switches with their source
`
