
export const MERCURY_CHANGELOG = `# Mercury changelog

## 1.0.0-beta.4
- Fixed on-device voice loading its speed-optimised pack on a CPU that cannot run it, which could end Mercury on the doctor's voice row or the first take; the check now runs once in a helper, and the doctor and /speak say what it found. The first use of voice on Windows no longer stalls while it checks
- Fixed the MCP connection memory keeping a server's full configuration on disk; it now keeps a fingerprint only
- Added a Motion setting (auto, full, reduced, off) in /config and in a new Boot Menu "Performance" section; auto keeps today's look and slows the idle motion only while the screen cannot keep up, saying "reduced" in the status line, then returns to full
- Fixed the idle cockpit keeping a core busy on a slow machine: the clock and the idle animation now follow the measured cost of painting instead of ticking at full rate
- Changed the usage meters to read when shown and after a retry, and the model picker to load its catalogue when it opens
- Updated the MCP client to the current protocol revision: servers built for it connect without the old handshake, older servers keep working, and the doctor's MCP row reads current
- Fixed a "still running" notice lingering after a compaction for an agent that had already finished, and a running workflow being counted as a sub-agent; the notice now names sub-agents and workflow runs separately, each with its own door
- Updated and refactored internal names and structure across the codebase; settings, rules and records saved under former names still apply
- Changed a permission ask on a session you are not looking at to wait for you with no time limit; its Session Concourse row reads "waiting for your answer" and the card is there when you focus the session; an ask raised by a sub-agent waits ten minutes
- Added /speak options: it lists the transcribers this install can use, marks the one serving now, and saves the one you pick; a saved choice that cannot serve is named and the default serves
- Changed the effort ladder to end at max; the extra word some provider lists advertise above it is never offered or sent
- Added an effort field to the Agent tool, defaulting to high or the provider's equivalent, and sub-agent defaults (model, effort, how many at once) as settings with config rows; a supercode turn delegates when parallel agents would help and works alone at max otherwise, and the turn receipt shows what delegated agents spent
- Added an optional built-in shell engine: with the setting "Shell engine" set to the built-in one, the Bash tool runs one shell per session whose directory, variables, functions and aliases persist between calls, the same shell on every platform, and Windows no longer needs Git for Windows; the system shell stays the default and the doctor names which engine is live
- Fixed the Bash tool under the built-in engine mangling non-ASCII text, hanging on a command that reads stdin, and dropping an external command's error output
- Fixed agents stopping with "provider throttled" after a stream went quiet or dropped, when no provider had refused anything: a recovery is now charged only for the time actually waited, every wait names its real cause, and the stop line says how to resume the agent
- Fixed a live but quiet model stream being cut after 90 seconds; the watchdog now sees the provider's keep-alive signals
- Changed a stream that ends with a bare error to read the stream's own closing reason first; the notice names the road and what Mercury did next
- Fixed the exit prompt counting agents that had already ended, and the crew view disagreeing with it; a row whose process is gone now settles, and the prompt names what is still running by kind and points at /tasks
- Changed what happens when an agent stops mid-stream: it hands back what it produced so far, the files it touched and why it stopped, and its work stays resumable; a seat cut by the recovery budget resumes once by itself when its allowance refills
- Fixed the "back to the bottom" pill never appearing after PgUp or PgDn in the transcript; it now paints as it does after the mouse wheel
- Fixed a repeat install that changed nothing still telling you to open a new terminal; it now says the folder is already on PATH and stops
- Added a browser road for /bug: when the GitHub CLI cannot file the report, the prefilled issue form opens in the browser and the link is printed in full
- Changed finished background commands to fold into one transcript row counted by outcome while the model is busy, a failed one keeping its title, instead of one row each
- Fixed a compaction on the OpenAI road sending a shorter request than the session had been sending, which left most of the context uncached afterwards; the summary request now carries the same rows plus the ask, and a forked agent keeps its parent's cache setting
- Fixed a message to a worker owned by a running workflow starting a second copy of that worker; the message is refused and names the workflow, and a finished run can no longer settle its successor
- Added on-device speech-to-text: with no API key at all, /speak on, space to talk, space to stop, and the words land in the composer without anything leaving the machine; the first use downloads a 60 MB English model once, behind /speak download, and the doctor names the engine, the model and the memory it takes
- Changed voice input to prefer the on-device transcriber whenever its pack and model are present; a signed-in cloud transcriber serves when they are not, or when you pin one
- Fixed a file read that starts at line 0 numbering its lines from 0, which made its anchors unusable by Edit; a read from offset 0 numbers its first line 1
- Fixed the last-resort image read advertising JPEG for PNG bytes on the JavaScript image road; the type now follows the bytes
- Fixed two cut paths losing their reason, an interruption during a Stop hook and a workflow permission ask that timed out; both now name their cause
- Fixed the Transaction tool refusing agent, transcript and workbench evidence references when noting a step or resuming; it now reads them with the session's own reader
- Fixed the Bash tool inserting a backslash before every ! once a command contained a single quote, which corrupted commit messages; a command reaches the shell exactly as written
- Fixed the Godot addon's sources arriving with Windows line endings on a checkout that converts them, which broke the addon's regeneration check
- Fixed a workflow child's capped report ending with a bare "[outcome truncated at cap]"; it now names the page that holds the rest
- Fixed Godot validation of a script with a class_name reporting a duplicate global class; validating by path reuses the script's own identity
- Fixed a resumed agent losing one of its two completion notices when queued guidance restarted it
- Fixed a named foreground agent never getting its name for SendMessage, its handover receipt missing the name, and retired names lingering after eviction
- Fixed Workshop cells that put statements and an await on one line failing with a syntax error, and brace characters inside strings silently returning the wrong value; the cell grammar is parsed, never scanned line by line
- Fixed a Workshop workspace failing to find TypeScript when node_modules is a link
- Fixed the render_tui tool failing outside the checkout and on every release install; it resolves the checkout and the bun runtime, and says plainly when it cannot run

## 1.0.0-beta.3
- Added GPT-6 Astra as a first-class model: it appears once a connected OpenAI account serves it, effort reaches max, and each turn is priced at the published rate
- Updated GPT-5.6 pricing to the current published rates, including the long-context tier
- Added a sixth effort level, ultra, above max, wherever the account serves it; a level the provider refuses is remembered and the nearest served level runs, with a note in the transcript
- Fixed a model switch on a stopped runner doing nothing; it now restarts the runner on the requested model, and an agent paused by a rate limit resumes when the window resets
- Fixed /model, /effort, /status, the strip, the picker, /config and /accounts disagreeing about the model being served
- Fixed the preserved-thinking notice appearing after a resume or restart even though the session kept its reasoning
- Changed the notice for dropped older reasoning after a model switch or a context trim to one quiet line instead of a warning on every message
- Fixed usage meters going stale without saying so; they now refresh themselves, show their age, and say when a read failed
- Fixed the Anthropic usage panel getting stuck on "Failed to load … HTTP 429"; it now honours the server's retry wait and says how long to wait
- Fixed a refused API key or token reading "Not logged in"; the error now names the setting to fix
- Fixed removing or switching an account being announced more than once, and added c on the sign-in cards to copy the code
- Added image paste in the composer on every platform (ctrl+v; alt+v on Windows) at any size; a large image is resized to the provider's limits and the composer says what it attached
- Changed Esc to interrupt the chat's own turn only: sub-agents and workflows keep running and the transcript says how many; in the Crew view x x stops one agent and r resumes it
- Added up arrow on an empty composer to take back a message sent while the turn was busy, before the model reads it; once read, the up arrow says so
- Changed the text before a tool call to a one-line working note that the final answer never restates
- Fixed deepthink and supercode glowing in a rainbow or mixed theme colours; they now glow in your critter's colour, in the composer and in the sent message
- Fixed selected text not following the view while scrolling, and the highlight painting outside the chat pane
- Fixed mouse drags repainting on every report, and made /mouse off stick across boots
- Fixed a mis-bound shortcut flashing "Unknown command" for a line you never typed, and a split key sequence leaking characters into the input
- Changed the chat's title bar to show the session's name instead of a ticking clock, and added how long your sub-agents have worked under the composer
- Fixed /rename being refused in every session; it now renames the session everywhere it is shown
- Added compaction progress in the chat (the stage, a bar, a clock); Esc cancels it cleanly, and a stalled or cancelled compaction keeps no half summary
- Fixed Mercury re-spawning or forgetting agents, workflows and shells after a compaction
- Fixed a false "rewrote sent history" warning when old tool results are trimmed to fit the window; it is now named as routine cleanup
- Changed the seat ceiling to one number everywhere: /seats, the Boot Menu and /config set it, idle agents no longer hold a seat, and the reading counts available memory
- Fixed a waiting agent's row not saying what it waits for, and a throttled agent's retries each spending their own budget
- Fixed sub-agents ending without saying how; they now report the real cause and what they wrote once, and a timeout is never blamed on you
- Fixed a background agent's completion arriving late in the chat; it now shows the moment it arrives, marked queued until the model reads it
- Fixed the workflow panel, the board, the crew view and the chip disagreeing about what is running, and reading "idle" right after a start instead of "not reported yet"
- Added "waiting for your answer" in the crew view and the tasks list for a sub-agent waiting on your permission
- Fixed a blocked team task not reading blocked on every screen, and creating a team hiding earlier tasks
- Fixed the Concourse close chord's hint going stale; it now does exactly what it says (stop, then archive, then delete), and a parked session reopens on one Enter
- Fixed a silent workflow stream waiting on the provider's guard instead of being cut at the stall budget
- Changed Sovereign mode to ask nothing: sensitive-file edits, ask rules and a server's ask ceiling run without a card, and the transcript says what would have asked
- Fixed the mode band showing a mode the runner did not hold; it now paints the real mode from the first frame, and a refused mode change reaches the screen with its reason
- Fixed a consent answer switching Apollo mode off; it now ends only through the review's approval or shift+tab, and writes outside the spec directory are refused
- Fixed Flow's safety check denying an action when it could not read its own verdict; it now keeps the evidence and says so
- Changed a Flow block in a session you are not looking at to wait for your answer there instead of being denied on the spot; a sub-agent's ask waits the same way
- Fixed a hook's deny decision leaving no audit row in the transcript
- Fixed consent cards overflowing the screen; a long edit or command is cut with a "+N more lines" line and ctrl+f shows the whole thing
- Fixed web search failing on a throttled request; it now cools down, answers a repeated query from the cache, and names what refused in one line
- Added Godot runtime pause, step and resume to drive a game frame by frame, and fixed the editor not being found where it lives and action presses not reaching the game's callbacks
- Fixed Unity test results landing where the editor could not write them; a bridged test run is no longer refused
- Fixed the interrupt not ending a running Bash command, and a request accepted with nothing arriving hanging instead of being named and ended
- Added /bug to show the exact report and file it through your own signed-in GitHub CLI, with every provider's key shape and GitHub tokens masked; /feedback opens the three-form chooser
- Added the Intel Mac build (macos-x64) to the release; mercury update names it on an Intel Mac
- Added release signing: archives are signed and verified before they publish, an unsigned build is announced once per install, and the archive carries the licence documents
- Changed mercury update to read the release channel anonymously, so no GitHub CLI or sign-in is needed; an update whose signature does not verify is refused
- Changed mercury install to put the command on your PATH once, and to say so when the version is already in place
- Fixed the doctor judging a headless run as a broken boot and reading the boot's rungs out of order
- Fixed a git init offer for the home directory, a drive root or a huge folder without a project marker; the doctor now names a home-directory repository and how to remove it
- Changed the project's .mercury folder to hold shared config only; machine-local files live in your Mercury home, and the doctor names any leftovers
- Fixed git and process spawns in the idle loop and at boot, and the daemon polling its own files instead of watching them
- Fixed a piped doctor --json printing more than one record or exiting before the reader drained
- Fixed a headless stream-json run not opening with its init line
- Fixed a fresh /logins not reaching hosted sessions until the daemon restarted
- Changed the companion's tips so every one is true today and teaches one thing

## 1.0.0-beta.2
- The first published build of the public line; 1.0.0-beta.1 was tagged and never published
- The repository is github.com/Whq02/MercuryCLI; the app's update channel and the release bridge read it
- The daemon runs the model a dispatch names under either field spelling; an unknown id refuses, never the default in silence
- A permission ask that expires or is withdrawn always settles its needs-you row, even when the row was still being written
- Background start-up probes never hold the process open at exit
- On the Concourse board, Enter on an example prompt fills the composer and never sends it; the next Enter sends
- The close chord is a ladder: stop, then archive, then delete; the --chat face always shows the shift-arrow key row
- The split view's size floor is the viewport's (80 columns by 22 rows)
- The status row keeps a wait's budget word on a narrow terminal; a cold model switch names its first-byte budget
- Twelve Bash tool fixes: the sandbox allows its own temp dir, pipes keep the special parameters, here-strings read, the timeout note reaches the model, an unavailable sandbox is refused and named

## 1.0.0-beta.1
- The first build published from this repository; README.md says what is inside
- Release notes ship inside the build: this bundled changelog is the only source
- The scribe and router party modes are retired; the concourse is the multi-agent path
- Release archives carry their own Node runtime; a release install needs git only
- A direct node dist/mercury.mjs start paints the launch splash before the Boot face, as the launcher does; the build ships the splash beside the bundle
- Voice input: /speak on, then space in an empty composer dictates into it through the OpenAI or Gemini API key you signed in with; audio leaves only after you stop, and Mercury never speaks aloud
- True Black is the default appearance: the same palette on a pure-black ground, on the launch splash and in the terminal; the oasis dark ground stays one row away in the first-run walk and /appearance, and a saved choice always wins
- Two per-session switches in the boot menu's Agents section, Sub-agents and Workflows: off removes the Agent or Workflow tool from that session's roster and every spawn road answers one receipt; /subagents on|off and /workflows on|off flip a running session at its next turn boundary, and the doctor names both switches with their source
`
