#!/usr/bin/env bun
// gen-lifecycle-manifest — renders the state-lifecycle manifest from the
// typed LIFECYCLE_MANIFEST declarations (the flag-table pattern: untracked
// derived output — generate → read → never commit; the collector prover
// asserts the render succeeds from the declarations).
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

process.env.MERCURY_CONFIG_DIR ??= '/tmp/gen-lifecycle-noop'
;(globalThis as Record<string, unknown>).MACRO ??= { VERSION: '0.0.0' }

const { LIFECYCLE_MANIFEST } = await import('../../src/substrate/stateLifecycle.ts')

const OUT = join(import.meta.dir, '.out', 'STATE-LIFECYCLE-MANIFEST.md')

const esc = (s: string): string => s.replace(/\|/g, '\\|')

const lines: string[] = [
  '# State lifecycle manifest',
  '',
  '<!-- GENERATED by scripts/substrate/gen-lifecycle-manifest.ts — edit',
  '     src/substrate/stateLifecycle.ts and regenerate; never hand-edit. -->',
  '',
  'Every durable state class Mercury writes, with its declared lifecycle.',
  'Classes whose action is `retain`/`reference` are',
  'declared-only: their collection (or deliberate exemption) is owned by the',
  'named module. The collector sweeps the `remove`/`rotate` classes in three',
  'lanes — mechanical debris, semantic state, daemon reconciliation —',
  'incrementally, budgeted, and cursor-resumable; the `.last-cleanup` sentinel',
  'advances only on a complete zero-failure cycle.',
  '',
  '| id | lane | kind | action | owner | root/key | live reference | terminal | retention | prover |',
  '|---|---|---|---|---|---|---|---|---|---|',
]
for (const c of LIFECYCLE_MANIFEST) {
  lines.push(
    `| ${c.id} | ${c.lane} | ${c.kind} | ${c.action}${c.collect ? ' (collector)' : ''} | ${esc(c.owner)} | ${esc(c.root)} | ${esc(c.liveReference)} | ${esc(c.terminal)} | ${esc(c.retention)} | ${esc(c.prover)} |`,
  )
}
lines.push('')
lines.push('Debris patterns:')
lines.push('')
for (const c of LIFECYCLE_MANIFEST) {
  if (c.debrisPatterns?.length) {
    lines.push(`- **${c.id}**: ${c.debrisPatterns.map(p => `\`${p}\``).join(' · ')}`)
  }
}
lines.push('')
const rendered = lines.join('\n')

if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(OUT, 'utf8')
  } catch {
    /* absent counts as drift */
  }
  if (current !== rendered) {
    console.error(
      'gen-lifecycle-manifest --check: the rendered manifest is stale — run `bun run scripts/substrate/gen-lifecycle-manifest.ts`',
    )
    process.exit(1)
  }
  console.log('gen-lifecycle-manifest --check: current')
  process.exit(0)
}

mkdirSync(join(import.meta.dir, '.out'), { recursive: true })
writeFileSync(OUT, rendered)
console.log(`wrote scripts/substrate/.out/STATE-LIFECYCLE-MANIFEST.md (${LIFECYCLE_MANIFEST.length} classes)`)
