#!/usr/bin/env bash
# gate-class: cpu
# gate-watch: src/bootstrap/state* src/commands/kill/**
# gate-watch: src/components/messages/nullRenderingAttachments* src/constants/** src/daemon/**
# gate-watch: src/hooks/useAgentStateClassifier* src/memdir/experienceCards*
# gate-watch: src/services/agentStateClassifier* src/services/agentStateHeuristic*
# gate-watch: src/services/analytics/config* src/services/compact/microCompactDigest*
# gate-watch: src/services/compact/verbatimTail* src/services/mcp/**
# gate-watch: src/utils/secrets/secretScanner* src/substrate/**
# gate-watch: src/tools/FileEditTool/constants* src/tools/FileReadTool/prompt*
# gate-watch: src/tools/FileWriteTool/prompt* src/tools/NotebookEditTool/constants*
# gate-watch: src/tools/ScheduleCronTool/prompt* src/tools/ToolSearchTool/prompt*
# gate-watch: src/tools/WorkflowTool/** src/tools/shared/spawnMultiAgent* src/utils/**
set -u
. "$(dirname "$0")/../lib/suite-env.sh" || exit 78; suite_env_guard "$0"
prover_mark() { local p="$1"; case "$p" in */scripts/*) p="scripts/${p##*/scripts/}";; ./*) p="${p#./}";; esac; printf '── %s  %ss rc=%s\n' "$p" "$(( SECONDS - $2 ))" "${3:?proof exit code required}"; }

here="$(cd "$(dirname "$0")" && pwd)"
bun="${BUN:-$HOME/.bun/bin/bun}"
fail=0
echo "############################################################"
echo "# Mercury substrate — wire-live proof harness"
echo "############################################################"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-git-cache-coldread.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-git-cache-coldread.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-git-facts-owner.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-git-facts-owner.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-filestore.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-filestore.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-filestore-ordering.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-filestore-ordering.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-trace-chip-states.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-trace-chip-states.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-prompt-draft.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-prompt-draft.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-lead-team-identity.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-lead-team-identity.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-classifier-prompt.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-classifier-prompt.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-filestore-subscribe.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-filestore-subscribe.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-filestore-stat-gate.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-filestore-stat-gate.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-gauge-owners.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-gauge-owners.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-coordination-service.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-coordination-service.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-pidlock.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-pidlock.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-mailbox-reaper.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-mailbox-reaper.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-flag-registry.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-flag-registry.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-env-switches.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-env-switches.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-prompt-provenance.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-prompt-provenance.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-runtime-posture.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-runtime-posture.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-harness-map.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-harness-map.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-mcp-policy-honest.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-mcp-policy-honest.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-substrate-umbrella.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-substrate-umbrella.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-agent-classifier.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-agent-classifier.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-trace-rotation.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-trace-rotation.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-capability-kill.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-capability-kill.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-kill-command.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-kill-command.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-daemon-breaker.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-daemon-breaker.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-feature-toggles.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-feature-toggles.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-breaker-timeout.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-breaker-timeout.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-mcp-policy.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-mcp-policy.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-mcp-instr-delta.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-mcp-instr-delta.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-coordination-server.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-coordination-server.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-lease-guard.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-lease-guard.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-team-roster-lock.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-team-roster-lock.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-mc-digest.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-mc-digest.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-fgts-carve.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-fgts-carve.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-glob-env-toggles.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-glob-env-toggles.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-tool-defer-carve.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-tool-defer-carve.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-verbatim-tail.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-verbatim-tail.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-away-summary.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-away-summary.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-cache-stability.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-cache-stability.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-handoff-summary.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-handoff-summary.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-artifacts-redaction.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-artifacts-redaction.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-shutdown-authority.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-shutdown-authority.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-compaction-trace.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-compaction-trace.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-evolution-ledger.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-evolution-ledger.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-daemon-snapshot.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-daemon-snapshot.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-daemon-supervisor-view.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-daemon-supervisor-view.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-daemon-reconcile.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-daemon-reconcile.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-ledger-flush-death.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-ledger-flush-death.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-pidlock-release.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-pidlock-release.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-lifecycle-collector.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-lifecycle-collector.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-no-telemetry-egress.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-no-telemetry-egress.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-snapshot-contract.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-snapshot-contract.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-wrapper.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-wrapper.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-trace-once.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-trace-once.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-schema-hint.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-schema-hint.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-telemetry-absence.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-telemetry-absence.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-identity-constants.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-identity-constants.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-kill-target.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-kill-target.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-presence-agent-ignored.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-presence-agent-ignored.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-startup-menu.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-startup-menu.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-boot-order.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-boot-order.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-spawn-ledger.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-spawn-ledger.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-live-e2e-hermetic.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-live-e2e-hermetic.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-friction-stopwatch.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-friction-stopwatch.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-health-self-recognition.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-health-self-recognition.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-headless-one-shot-roster.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-headless-one-shot-roster.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-bus-envelopes.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-bus-envelopes.ts" "$__t" "$__rc"
echo "############################################################"
if [ "$fail" = "0" ]; then echo "# ✅ ALL SUBSTRATE PROOFS PASS"; else echo "# ❌ SOME SUBSTRATE PROOFS FAILED"; fi
echo "############################################################"
exit "$fail"
