#!/usr/bin/env bun
// ============================================================================
//  scripts/extensions/gen-contract.ts — ONE source of truth for the maker
//  contract. The manifest and catalogue schemas (the runtime's own zod
//  definitions, `.describe()` on every field) render:
//
//    · the CONTRACT section of docs/EXTENSIONS.md (between the markers)
//    · mercury-skills/extension-maker/references/CONTRACT.md (the bundled
//      skill's reference file; gen-bundled embeds it)
//
//  prove-contract-in-sync.ts regenerates both into scratch and fails on any
//  byte difference — the doc and the skill cannot drift from the schema or
//  from each other.
//
//  Run:  ~/.bun/bin/bun run scripts/extensions/gen-contract.ts [--check]
// ============================================================================
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import { join, resolve } from 'node:path'
import { z } from 'zod'

const ROOT = resolve(import.meta.dir, '..', '..')
const DOC = join(ROOT, 'docs', 'EXTENSIONS.md')
const SKILL_REF = join(ROOT, 'mercury-skills', 'extension-maker', 'references', 'CONTRACT.md')
const BUNDLED_REF = join(ROOT, 'src', 'skills', 'bundled', 'extension-maker', 'references', 'CONTRACT.md')
const BEGIN = '<!-- contract:begin — generated by scripts/extensions/gen-contract.ts; edit the schemas, not this section -->'
const END = '<!-- contract:end -->'

const manifestMod = await import('../../src/extensions/manifest.ts')
const catalogueMod = await import('../../src/extensions/catalogue.ts')

type JsonSchema = {
  type?: string
  description?: string
  properties?: Record<string, JsonSchema>
  required?: string[]
  items?: JsonSchema
  additionalProperties?: JsonSchema | boolean
  anyOf?: JsonSchema[]
  enum?: unknown[]
  const?: unknown
}

function typeWord(schema: JsonSchema): string {
  if (schema.const !== undefined) return `\`${JSON.stringify(schema.const)}\``
  if (schema.enum) return schema.enum.map(v => `\`${String(v)}\``).join(' · ')
  if (schema.anyOf) return schema.anyOf.map(typeWord).join(' or ')
  if (schema.type === 'array') return `list of ${schema.items ? typeWord(schema.items) : 'items'}`
  if (schema.type === 'object' && schema.additionalProperties && typeof schema.additionalProperties === 'object') {
    return `map of name → ${typeWord(schema.additionalProperties)}`
  }
  if (schema.type === 'object') return 'object'
  return schema.type ?? 'value'
}

function fieldRows(schema: JsonSchema, prefix = ''): string[] {
  const rows: string[] = []
  const required = new Set(schema.required ?? [])
  for (const [name, child] of Object.entries(schema.properties ?? {})) {
    const path = prefix ? `${prefix}.${name}` : name
    rows.push(`| \`${path}\` | ${typeWord(child)} | ${required.has(name) ? 'yes' : 'no'} | ${(child.description ?? '').replace(/\n/g, ' ')} |`)
    const nested = child.type === 'object' && child.properties ? child : child.items?.type === 'object' && child.items.properties ? child.items : undefined
    const mapValue = child.additionalProperties && typeof child.additionalProperties === 'object' && (child.additionalProperties as JsonSchema).properties ? (child.additionalProperties as JsonSchema) : undefined
    if (nested) rows.push(...fieldRows(nested, child.type === 'array' ? `${path}[]` : path))
    if (mapValue) rows.push(...fieldRows(mapValue, `${path}.<name>`))
    if (child.anyOf) {
      for (const arm of child.anyOf) {
        if (arm.properties) rows.push(...fieldRows(arm, `${path}.<name>`))
      }
    }
  }
  return rows
}

function table(title: string, schema: JsonSchema): string {
  return [`### ${title}`, '', '| field | shape | required | meaning |', '|---|---|---|---|', ...fieldRows(schema), ''].join('\n')
}

export function renderContract(): string {
  const manifestSchema = z.toJSONSchema(manifestMod.ExtensionManifestSchema(), { io: 'input', unrepresentable: 'any' }) as JsonSchema
  const catalogueSchema = z.toJSONSchema(catalogueMod.CatalogueSchema(), { io: 'input', unrepresentable: 'any' }) as JsonSchema
  const lines: string[] = []
  lines.push(BEGIN, '')
  lines.push('## The contract (generated from the runtime schemas)', '')
  lines.push(`- an extension's name: ${manifestMod.NAME_RULE}; the id everywhere is \`<name>@<source label>\`; the reserved labels are ${manifestMod.RESERVED_LABELS.map(l => `\`${l}\``).join(', ')}.`)
  lines.push('- ONE manifest, `mercury-extension.json`, at the extension root; every path in it stays inside the root.')
  lines.push('- ONE catalogue, `mercury-extensions.json`, at a source root — or a single `mercury-extension.json` when the repository IS the extension.')
  lines.push('- unknown top-level keys: a warning at load, an error under `mercury extensions validate`; unknown keys INSIDE `contributes`/`needs` are errors at load.')
  lines.push(`- \`module\` is reserved: ${manifestMod.RESERVED_MODULE_REASON}.`)
  lines.push('- approval is per contributions hash — sha256 over the canonicalised `contributes` + `needs` blocks: a version bump alone carries approval over; a changed command line, server, or need re-asks.')
  lines.push('- the substitutions: `${MERCURY_EXTENSION_ROOT}`, `${MERCURY_EXTENSION_DATA}`, `${option.KEY}` in command lines, args, env values and prompt bodies; every other `${…}` stays literal. Hooks and servers receive `MERCURY_EXTENSION_ROOT`, `MERCURY_EXTENSION_DATA` and one `MERCURY_EXTENSION_OPTION_<KEY>` per option; a `sensitive` option renders a visible placeholder in prose the model reads.')
  lines.push('')
  lines.push(table('`mercury-extension.json` — field by field', manifestSchema))
  lines.push(table('`mercury-extensions.json` — field by field', catalogueSchema))
  lines.push(END)
  return lines.join('\n')
}

function spliceDoc(docText: string, contract: string): string {
  const begin = docText.indexOf(BEGIN)
  const end = docText.indexOf(END)
  if (begin === -1 || end === -1) throw new Error(`docs/EXTENSIONS.md is missing the contract markers`)
  return docText.slice(0, begin) + contract + docText.slice(end + END.length)
}

const contract = renderContract()
const check = process.argv.includes('--check')
const doc = readFileSync(DOC, 'utf8')
const nextDoc = spliceDoc(doc, contract)
const skillRef = `${contract}\n`
if (check) {
  let clean = true
  if (nextDoc !== doc) {
    console.error('docs/EXTENSIONS.md contract section is stale')
    clean = false
  }
  for (const path of [SKILL_REF, BUNDLED_REF]) {
    let current = ''
    try {
      current = readFileSync(path, 'utf8')
    } catch {
      current = '<absent>'
    }
    if (current !== skillRef) {
      console.error(`${path} is stale`)
      clean = false
    }
  }
  process.exit(clean ? 0 : 1)
}
writeFileSync(DOC, nextDoc)
for (const target of [SKILL_REF, BUNDLED_REF]) {
  mkdirSync(dirname(target), { recursive: true })
  writeFileSync(target, skillRef)
}
console.log('contract rendered into docs/EXTENSIONS.md, the skill reference, and the bundled copy')
