import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { check, fixture, emit, status, finish, call, done, tx, capture, receiptsFor } from './transactionProof.js'

const f = fixture(['calc.py'])
writeFileSync(f.files[0]!, 'def add(a, b):\n    return a + b\n')
mkdirSync(join(f.root, 'tests'))
writeFileSync(join(f.root, 'tests', '__init__.py'), '')
writeFileSync(join(f.root, 'tests', 'test_calc.py'), 'import unittest\nfrom calc import add\nclass TestCalc(unittest.TestCase):\n    def test_add(self):\n        self.assertEqual(add(2, 3), 5)\n')
const SYS_PY = '/usr/bin/python3'
process.env.MERCURY_PYTHON = SYS_PY
const { runPythonTests } = await import('../../src/services/ide/pythonTests.js')
const { makeOwnerKey } = await import('../../src/services/run/ownerKey.js')
const { resolveResource } = await import('../../src/services/resources/registry.js')
await import('../../src/services/resources/adapters/ide.js')
await import('../../src/services/resources/adapters/test.js')

emit(f)
const early = await finish(f)
const opened = tx.latestTransaction(f.root)!
check('A1 observed edit is saved on the first finish attempt', opened?.steps.filter(s => s.kind === 'apply').length === 1)
const fake = await tx.noteStep({ id: opened.id, owner: f.owner, from: f.root, kind: 'apply', summary: 'pretend apply', refs: ['mercury://receipt/rcpt-doesnotexist'] })
check('A2 an unresolvable ref refuses the internal note', fake.state === 'refused' && fake.reason.includes('does not resolve'))
const receipt = receiptsFor(f.owner).at(-1)
check('A3 automatic change carries the real observer receipt', opened.steps[0]?.refs[0] === `mercury://receipt/${receipt?.id}`)
check('B1 only the real post-change check is missing', early.data.outcome === 'failed' && early.data.result.includes('no check has run since the last change') && !early.data.result.includes('stabilize'))
const run = await runPythonTests({ from: f.root, framework: 'unittest', selectionLabel: 'all' })
check('B2 the real Python test run is green', run.state === 'ok' && run.record.counts.failed === 0)
if (run.state === 'ok') {
  const { runWithCwdOverride } = await import('../../src/utils/cwd.js')
  const resource = await runWithCwdOverride(f.root, () => resolveResource(`mercury://test/run/${run.record.id}`, { owner: f.owner, cwd: f.root }))
  check('B3 its durable test ref resolves', resource.state === 'ok')
}
emit(f, 'test.run', { paths: [], toolName: 'Test', input: { op: 'run' } })
const complete = await finish(f, 'completed', ['pytest arm untested on this fixture'])
check('B4 the observed edit and real check complete', complete.data.outcome === 'succeeded')
check('B5 uncertainty is preserved verbatim', tx.getTransaction(opened.id, f.root)?.unresolved.includes('pytest arm untested on this fixture') === true)
const late = await tx.noteStep({ id: opened.id, owner: f.owner, from: f.root, kind: 'verify', summary: 'late note' })
check('B6 a finished record refuses further notes', late.state === 'refused')

emit(f)
emit(f, 'test.run', { paths: [], outcome: 'failed', ok: false, toolName: 'Test', input: { op: 'run' } })
const red = await finish(f)
check('C1 the newest failed check blocks completion', red.data.outcome === 'failed' && red.data.result.includes('the newest check since the last change failed'))
const failed = await finish(f, 'failed', ['test_add still red'])
check('C2 failed finish preserves uncertainty', failed.data.outcome === 'no-change' && tx.latestTransaction(f.root)?.verdict === 'failed' && tx.latestTransaction(f.root)?.unresolved.length === 1)

const strangeOwner = makeOwnerKey({ workspace: f.root, sessionId: 'another-process', lane: 'main' })
const resumed = await tx.resumeTransaction({ id: opened.id, owner: strangeOwner, from: f.root })
check('D1 latest.json points at the newest record', tx.latestTransaction(f.root) !== null)
check('D2 durable records re-read after finish', resumed !== null && resumed.record.verdict === 'completed')
check('D3 another owner sees the receipt stale and nothing is replayed', resumed !== null && resumed.applyRefChecks.length === 1 && resumed.applyRefChecks[0]?.resolves === false && resumed.applyRefChecks[0].note.includes('nothing was replayed'))
check('D4 the trail lists both loops', tx.listTransactions(f.root).length === 2)
const one = await resolveResource(`mercury://ide/transaction/${opened.id}`, { owner: f.owner, cwd: f.root })
check('E1 the resource reads the structured completed record', one.state === 'ok' && (one.resource.structured as { verdict?: string }).verdict === 'completed')
check('E2 the latest resource resolves', (await resolveResource('mercury://ide/transaction/latest', { owner: f.owner, cwd: f.root })).state === 'ok')
const listing = await resolveResource('mercury://ide/transaction', { owner: f.owner, cwd: f.root })
check('E3 the resource listing keeps both records', listing.state === 'ok' && listing.resource.children?.length === 2)

const internal = await tx.openTransaction({ owner: f.owner, intent: 'historical session refs', from: f.root })
const ref = 'mercury://agent/b1234'
const getAppState = () => ({ tasks: { b1234: { id: 'b1234', type: 'local_bash', status: 'running', description: 'fixture shell', startTime: Date.now() } } })
const noted = await tx.noteStep({ id: internal.id, owner: f.owner, from: f.root, kind: 'apply', summary: 'historical session evidence', refs: [ref], getAppState })
check('F1 historical session refs still resolve through the service reader', noted.state === 'ok')
const readerless = await tx.noteStep({ id: internal.id, owner: f.owner, from: f.root, kind: 'diagnose', summary: 'no reader', refs: [ref] })
check('F2 the same ref without a reader still refuses', readerless.state === 'refused' && readerless.reason.includes('unavailable'))
const mixed = await tx.noteStep({ id: internal.id, owner: f.owner, from: f.root, kind: 'diagnose', summary: 'mixed refs', refs: [ref, 'mercury://agent/nope'], getAppState })
check('F3 a mixed live and fabricated set refuses whole without a step', mixed.state === 'refused' && tx.getTransaction(internal.id, f.root)?.steps.length === 1)
const reader = await tx.resumeTransaction({ id: internal.id, owner: f.owner, from: f.root, getAppState })
const noReader = await tx.resumeTransaction({ id: internal.id, owner: f.owner, from: f.root })
check('F4 historical reader-aware liveness stays live', reader?.applyRefChecks[0]?.resolves === true)
check('F5 reader-less liveness stays stale', noReader?.applyRefChecks[0]?.resolves === false)
await finish(f, 'abandoned')

const idle = await finish(f, 'abandoned')
check('G1 nothing to finish preserves the exact result', idle.data.outcome === 'no-change' && idle.data.result === 'Nothing to finish — no transaction is open at this root.')
for (let n = 0; n < 4; n++) emit(f)
const queued = await call(f, { op: 'status' })
check('G2 a batch of changes opens one unsaved journal and loses none', queued.data.result.startsWith('unsaved record [open]') && queued.data.result.includes('4 change(s)') && tx.openTransactionIdFor(f.root) === null)
await finish(f, 'abandoned')
check('G3 finish saves and closes the journal', tx.latestTransaction(f.root)?.steps.length === 4 && tx.openTransactionIdFor(f.root) === null)
await capture._drainTxAutoCaptureForTesting()
check('G4 status names the latest record after finish', (await status(f)).includes('Latest record:'))
delete process.env.MERCURY_PYTHON
done('prove-closed-loop')
