import * as React from 'react'
import { exitChordNoticeText } from '../../PromptInput/ExitChordNotice.js'
import { useState } from 'react'
import { Box, Text } from '../../../ink.js'
import TextInput from '../../TextInput.js'
import { useKeybinding } from '../../../keybindings/useKeybinding.js'
import { useExitOnCtrlCDWithKeybindings } from '../../../hooks/useExitOnCtrlCDWithKeybindings.js'
import { useTerminalSize } from '../../../hooks/useTerminalSize.js'
import { BASH_TOOL_NAME } from '../../../tools/BashTool/toolName.js'
import { WebFetchTool } from '../../../tools/WebFetchTool/WebFetchTool.js'
import {
  permissionRuleValueFromString,
  permissionRuleValueToString,
} from '../../../utils/permissions/permissionRuleParser.js'
import type { PermissionBehavior, PermissionRuleValue } from '../../../types/permissions.js'

export type PermissionRuleInputProps = {
  onCancel: () => void
  onSubmit: (ruleValue: PermissionRuleValue, ruleBehavior: PermissionBehavior) => void
  ruleBehavior: PermissionBehavior
}

/**
 * Free-text rule entry. The two teaching examples are generated by running
 * the engine's serialiser over real values, so the taught syntax can never
 * drift from the parsed one.
 */
export function PermissionRuleInput({
  onCancel,
  onSubmit,
  ruleBehavior,
}: PermissionRuleInputProps): React.ReactNode {
  const [value, setValue] = useState('')
  const { columns } = useTerminalSize()
  const pendingExit = useExitOnCtrlCDWithKeybindings()

  useKeybinding('confirm:no', () => onCancel(), { context: 'Settings' })

  const exampleTool = permissionRuleValueToString({ toolName: WebFetchTool.name })
  const exampleBash = permissionRuleValueToString({
    toolName: BASH_TOOL_NAME,
    ruleContent: 'ls:*',
  })

  function handleSubmit(submitted: string): void {
    // Empty or whitespace-only input is ignored: no submit, no error.
    if (submitted.trim() === '') return
    onSubmit(permissionRuleValueFromString(submitted), ruleBehavior)
  }

  return (
    <Box
      flexDirection="column"
      borderStyle="round"
      borderColor="permission"
      paddingX={1}
    >
      <Text bold color="permission">
        Add {ruleBehavior} permission rule
      </Text>
      <Text dimColor>
        A rule is a tool name, optionally followed by a specifier in
        parentheses — for example <Text bold>{exampleTool}</Text> or{' '}
        <Text bold>{exampleBash}</Text>
      </Text>
      <TextInput
        value={value}
        onChange={setValue}
        onSubmit={handleSubmit}
        columns={columns - 6}
        cursorOffset={value.length}
        onChangeCursorOffset={() => {}}
        showCursor
      />
      <Text color="subtle">
        {pendingExit.pending
          ? exitChordNoticeText(pendingExit.keyName)
          : 'enter submit · esc cancel'}
      </Text>
    </Box>
  )
}
