#!/usr/bin/env bun

;(globalThis as Record<string, unknown>).MACRO = { VERSION: '1.0.0' }
const { enableConfigs } = await import('../../src/utils/config.ts')
enableConfigs()

import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const scratch = mkdtempSync(join(tmpdir(), 'sg8-bench-'))
for (const spelling of ['MERCURY_CONFIG_DIR', 'MERCURY_HOME']) {
  process.env[spelling] = join(scratch, 'home')
}
mkdirSync(join(scratch, 'home'), { recursive: true })
const recordsDir = join(scratch, 'daemon')
const crewDir = join(scratch, 'crew')
const draftDir = join(scratch, 'config')
for (const d of [recordsDir, crewDir, draftDir]) mkdirSync(d, { recursive: true })

let failures = 0
function check(label: string, ok: boolean, detail?: string): void {
  if (ok) console.log(`  ✅ ${label}`)
  else {
    failures += 1
    console.log(`  ❌ ${label}${detail ? ` — ${detail}` : ''}`)
  }
}

const CALIBRATED_CLASS = process.platform === 'darwin' && process.arch === 'arm64'
function gateLatency(label: string, ok: boolean, detail?: string): void {
  if (CALIBRATED_CLASS) check(label, ok, detail)
  else console.log(`  [REPORTED-ONLY · uncalibrated machine class] ${label}${detail ? ` — ${detail}` : ''}`)
}

function dist(samples: number[]): { p50: number; p95: number; p99: number; max: number; n: number } {
  const s = [...samples].sort((a, b) => a - b)
  const at = (q: number) => s[Math.min(s.length - 1, Math.floor(q * s.length))]!
  return { p50: at(0.5), p95: at(0.95), p99: at(0.99), max: s[s.length - 1]!, n: s.length }
}

async function measure(n: number, warmup: number, fn: () => Promise<unknown> | unknown): Promise<number[]> {
  for (let i = 0; i < warmup; i++) await fn()
  const out: number[] = []
  for (let i = 0; i < n; i++) {
    const t0 = performance.now()
    await fn()
    out.push(performance.now() - t0)
  }
  return out
}

const DEAD_PID = 4_194_999
const worker = (n: number, live: boolean) => ({
  schema: 1,
  runnerId: `concourse-w${n}`,
  sessionId: `bench-sess-${n}`,
  workspaceId: join(scratch, `ws-${n}`),
  isolation: 'exclusive',
  modelKey: 'fable',
  spawnedAt: Date.now() - 60_000,
  lastLiveAt: Date.now(),
  pid: live ? process.pid : DEAD_PID,
})
writeFileSync(
  join(recordsDir, 'concourse-workers.json'),
  JSON.stringify({ version: 1, workers: Object.fromEntries([1, 2, 3, 4, 5].map(n => [`concourse-w${n}`, worker(n, n <= 3)])) }),
)

const report: Record<string, unknown> = {
  schema: 1,
  machineClass: 'capable-workstation (darwin arm64 — the dev box; per-machine-class floors only ever tighten)',
  note: 'generated by prove-concourse-budgets.ts — regenerate deliberately; the gates in the prover are the law, this file is the recorded distribution artifact',
}

console.log('§1 target resolver — the bounded-summary read (§13: p95 ≤ 10ms, max ≤ 25ms)')
{
  const { resolveInitialSurface } = await import('../../src/context/surfaceRoute.ts')
  const samples = await measure(200, 20, () => resolveInitialSurface())
  const d = dist(samples)
  report['targetResolverMs'] = d
  gateLatency(`p95 ${d.p95.toFixed(2)}ms ≤ 10ms`, d.p95 <= 10, JSON.stringify(d))
  gateLatency(`max ${d.max.toFixed(2)}ms ≤ 25ms`, d.max <= 25, JSON.stringify(d))
}

console.log('§2 warm switch — buildConcourseSnapshot over five workers (< 100ms p95)')
{
  const { buildConcourseSnapshot } = await import('../../src/services/concourse/concourseSnapshot.ts')
  const samples = await measure(120, 10, () => buildConcourseSnapshot({ recordsDir, crewDir, draftDir }))
  const d = dist(samples)
  report['warmSwitchSnapshotMs'] = d
  gateLatency(`p95 ${d.p95.toFixed(2)}ms < 100ms`, d.p95 < 100, JSON.stringify(d))
}

console.log('§3 dispatch receipts — reservation→working through the owner path (< 50ms p95)')
{
  const { makeConcourseDispatchHandler } = await import('../../src/daemon/concourseDispatch.ts')
  const dispatchDir = join(scratch, 'dispatch-daemon')
  mkdirSync(dispatchDir, { recursive: true })
  writeFileSync(
    join(dispatchDir, 'concourse-workers.json'),
    JSON.stringify({ version: 1, workers: { 'concourse-w1': worker(1, true) } }),
  )
  let n = 0
  const handler = makeConcourseDispatchHandler({
    admit: async () => ({ ok: true as const, runnerId: 'concourse-w1', sessionId: 'bench-sess-1', workspaceId: join(scratch, 'ws-1') }),
    deliver: async () => true,
    dir: dispatchDir,
  })
  const samples = await measure(100, 10, () => handler({ clientMessageId: `bench-${n++}`, prompt: 'bench', workspaceDir: scratch }))
  const d = dist(samples)
  report['dispatchOwnerPathMs'] = d
  gateLatency(`p95 ${d.p95.toFixed(2)}ms < 50ms`, d.p95 < 50, JSON.stringify(d))
}

console.log('§4 attach fold — snapshot+suffix over a 200-record transcript tail (< 100ms p95)')
{
  const wt = await import('../../src/services/concourse/workerTranscript.ts')
  const fold = (wt as Record<string, unknown>)['foldWorkerTranscriptChunk'] ?? (wt as Record<string, unknown>)['default']
  const lines = Array.from({ length: 200 }, (_, i) => JSON.stringify({ type: 'assistant', i, text: `record ${i}` })).join('\n') + '\n'
  if (typeof fold === 'function') {
    const samples = await measure(150, 10, () => (fold as (carry: string, chunk: string) => unknown)('', lines))
    const d = dist(samples)
    report['attachFold200Ms'] = d
    gateLatency(`p95 ${d.p95.toFixed(2)}ms < 100ms`, d.p95 < 100, JSON.stringify(d))
  } else {
    const samples = await measure(150, 10, () => lines.split('\n').filter(Boolean).map(l => JSON.parse(l)))
    const d = dist(samples)
    report['attachFold200Ms'] = { ...d, note: 'parse-cost proxy (fold export not found by name)' }
    gateLatency(`p95 ${d.p95.toFixed(2)}ms < 100ms (parse proxy)`, d.p95 < 100, JSON.stringify(d))
  }
}

console.log('§5 context size — the five-worker snapshot stays snapshot-scale (< 32 KiB)')
{
  const { buildConcourseSnapshot } = await import('../../src/services/concourse/concourseSnapshot.ts')
  const snap = await buildConcourseSnapshot({ recordsDir, crewDir, draftDir })
  const bytes = JSON.stringify(snap).length
  report['snapshotBytes'] = bytes
  check(`snapshot ${bytes}B < 32768B`, bytes < 32_768, String(bytes))
}

console.log('§6 idle work — the snapshot path allocates no timers/listeners')
{
  const before = process.getActiveResourcesInfo?.() ?? []
  const { buildConcourseSnapshot } = await import('../../src/services/concourse/concourseSnapshot.ts')
  for (let i = 0; i < 10; i++) await buildConcourseSnapshot({ recordsDir, crewDir, draftDir })
  const after = process.getActiveResourcesInfo?.() ?? []
  const grewTimers = after.filter(r => r === 'Timeout').length > before.filter(r => r === 'Timeout').length + 1
  report['idleResourceDelta'] = { before: before.length, after: after.length }
  check('ten builds grow no timer population', !grewTimers, JSON.stringify({ before: before.length, after: after.length }))
}

console.log('§7 the artifact')
{
  report['memoryRssBytes'] = process.memoryUsage().rss
  report['citedStandingEvidence'] = {
    inputEchoUnder50msP95: 'the rendezvous echo laws (scripts/attention) — the standing <50ms p95 gate',
    eventToVisibleUnder250msP95: 'prove-attention-visibility.ts — the 250ms budget MINTED at (measured p95 0ms/max 6ms over the real owner→bridge→store chain)',
    liveSceneBudgets: 'the pulse suite scene gates (input_processing ≤1500ms etc.)',
    windowsIdleBase: 'windows-tasks TASK-004: ~43 B/s idle (60-61 chunks / ~2.6KB per 60s, all attributable) at 19045/WT 1.24 — the basis, frozen POST the naked-pair fix',
  }
  const out = join(import.meta.dir, 'baselines', 'bench-concourse.json')
  if (!existsSync(out) || process.argv.includes('--remint')) {
    writeFileSync(out, `${JSON.stringify(report, null, 1)}\n`)
    check('bench-concourse.json minted (the retained distribution artifact)', true)
  } else {
    check('bench-concourse.json retained frozen (gates measured live; --remint re-measures)', true)
  }
}

rmSync(scratch, { recursive: true, force: true })
console.log(failures === 0 ? '\nPROVE-CONCOURSE-BUDGETS: PASS' : `\nPROVE-CONCOURSE-BUDGETS: ${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
