
import {
  getAgentTranscriptPath,
  getEntrypoint,
  getNodeEnv,
  getProjectDir,
  getProjectsDir,
  getTranscriptPath,
  getTranscriptPathForSession,
  isChainParticipant,
  isEphemeralToolProgress,
  isPersistedProgressEntry,
  isTranscriptMessage,
  MAX_TRANSCRIPT_READ_BYTES,
} from './sessionStorage/paths.js'
export {
  clearAgentTranscriptSubdir,
  getAgentTranscriptPath,
  getNodeEnv,
  getProjectDir,
  getProjectsDir,
  getTranscriptPath,
  getTranscriptPathForSession,
  getWorkflowTranscriptDir,
  isChainParticipant,
  isCustomTitleEnabled,
  isEphemeralToolProgress,
  isTranscriptMessage,
  MAX_TRANSCRIPT_READ_BYTES,
  readAgentMetadata,
  sessionIdExists,
  setAgentTranscriptSubdir,
  writeAgentMetadata,
} from './sessionStorage/paths.js'
import {
  applyPreservedSegmentRelinks,
  applySnipRemovals,
  buildAttributionSnapshotChain,
  buildConversationChain,
  buildFileHistorySnapshotChain,
  checkResumeConsistency,
  extractFirstPrompt,
  findLatestMessage,
  getFirstMeaningfulUserMessageTextContent,
  removeExtraFields,
  cleanMessagesForLogging,
  isLoggableMessage,
} from './sessionStorage/chain.js'

import {
  getProject,
  appendEntryToFile,
  getSessionMessages,
} from './sessionStorage/writer.js'
import { loadSessionFile, loadTranscriptFile } from './sessionStorage/loading.js'
export { loadTranscriptFile } from './sessionStorage/loading.js'
export {
  adoptResumedSessionFile,
  flushSessionStorage,
  recordAttributionSnapshot,
  recordContentReplacement,
  recordContextCollapseCommit,
  recordContextCollapseSnapshot,
  recordFileHistorySnapshot,
  recordQueueOperation,
  recordSidechainTranscript,
  recordTranscript,
  registerAgentTranscriptDestination,
  removeTranscriptMessage,
  resetProjectFlushStateForTesting,
  resetProjectForTesting,
  resetSessionFilePointer,
  setInternalEventReader,
  setInternalEventWriter,
  setRemoteIngressUrlForTesting,
  setSessionFileForTesting,
} from './sessionStorage/writer.js'

export {
  buildConversationChain,
  checkResumeConsistency,
  getFirstMeaningfulUserMessageTextContent,
  removeExtraFields,
  cleanMessagesForLogging,
  isLoggableMessage,
} from './sessionStorage/chain.js'


export {
  cacheSessionTitle,
  clearSessionMessagesCache,
  clearSessionMetadata,
  doesMessageExistInSession,
  extractAgentIdsFromMessages,
  extractTeammateTranscriptsFromTasks,
  fetchLogs,
  findUnresolvedToolUse,
  getAgentTranscript,
  getCurrentSessionAgentColor,
  getCurrentSessionTag,
  getCurrentSessionTitle,
  getLastSessionLog,
  getLogByIndex,
  getSessionFilesLite,
  getSessionFilesWithMtime,
  getSessionIdFromLog,
  isLiteLog,
  linkSessionToPR,
  loadAllLogsFromSessionFile,
  loadAllProjectsMessageLogs,
  loadAllProjectsMessageLogsProgressive,
  loadAllSubagentTranscriptsFromDisk,
  loadFullLog,
  loadMessageLogs,
  loadSameRepoMessageLogs,
  loadSameRepoMessageLogsProgressive,
  loadSubagentTranscripts,
  loadTranscriptFromFile,
  reAppendSessionMetadata,
  restoreSessionMetadata,
  saveAgentColor,
  saveAgentName,
  saveAgentSetting,
  saveAiGeneratedTitle,
  saveCustomTitle,
  saveMode,
  saveTag,
  saveTaskSummary,
  saveWorktreeState,
  searchSessionsByCustomTitle,
  transcriptCensus,
  enrichLogs,
  type SessionLogResult,
} from './sessionStorage/logs.js'
