#!/usr/bin/env bash
# gate-class: cpu
# gate-watch: src/daemon/** src/substrate/flagRegistry* src/types/permissions*
# gate-watch: src/utils/boxLock* src/services/resources/adapters/health*
# gate-watch: src/services/engine-connector/seatProjections* src/utils/spawnLedger* docs/DURABILITY.md
# gate-watch: src/tools/MonitorTool/**
# gate-watch: src/cli/headless/turnDriver* src/cli/print* src/services/saturn/** src/tools/ScheduleWakeupTool/**
set -u
. "$(dirname "$0")/../lib/suite-env.sh" || exit 78; suite_env_guard "$0"
prover_mark() { local p="$1"; case "$p" in */scripts/*) p="scripts/${p##*/scripts/}";; ./*) p="${p#./}";; esac; printf '── %s  %ss rc=%s\n' "$p" "$(( SECONDS - $2 ))" "${3:?proof exit code required}"; }

here="$(cd "$(dirname "$0")" && pwd)"
bun="${BUN:-$HOME/.bun/bin/bun}"
fail=0
echo "############################################################"
echo "# Mercury daemon — proof harness"
echo "############################################################"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-pty-degrade.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-pty-degrade.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-box-facts.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-box-facts.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-supervisor-lock.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-supervisor-lock.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-daemon-verbs.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-daemon-verbs.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-daemon-signin-live.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-daemon-signin-live.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-dispatch-death-settles.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-dispatch-death-settles.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-control-ops-ledger.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-control-ops-ledger.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-daemon-env-scrub.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-daemon-env-scrub.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-seat-work-poll.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-seat-work-poll.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-session-activity.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-session-activity.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-drained-turn-edge.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-drained-turn-edge.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-reconfigure-respawn.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-reconfigure-respawn.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-roster-stdin.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-roster-stdin.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-headless-permission-mode.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-headless-permission-mode.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-daemon-dir-seam.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-daemon-dir-seam.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-worker-census.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-worker-census.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-halt-roster.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-halt-roster.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-worker-recon.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-worker-recon.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-warm-runner.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-warm-runner.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-warm-consent-boot.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-warm-consent-boot.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-newborn-grace.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-newborn-grace.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-kit-birth.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-kit-birth.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-birth-replay.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-birth-replay.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-runner-quiescence.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-runner-quiescence.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-retire-drive.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-retire-drive.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-capability-census.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-capability-census.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-runner-refusal-drive.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-runner-refusal-drive.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-parked-state.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-parked-state.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-reactivate-door.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-reactivate-door.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-close-all.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-close-all.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-switch-boundary.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-switch-boundary.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-status-honesty.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-status-honesty.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-focus-one-writer.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-focus-one-writer.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-protocol-shape.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-protocol-shape.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-compact-state-word.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-compact-state-word.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-interrupt-agent-wait.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-interrupt-agent-wait.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-stop-acknowledged.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-stop-acknowledged.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-hard-stop-cut.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-hard-stop-cut.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-cap-seat.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-cap-seat.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-first-byte-drive.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-first-byte-drive.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-reissue-rows-drive.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-reissue-rows-drive.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-daemon-handshake.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-daemon-handshake.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-field-findings-daemon-older.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-field-findings-daemon-older.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-recall-relay.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-recall-relay.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-recall-runner.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-recall-runner.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-starting-door.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-starting-door.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-send-hops.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-send-hops.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-rename-migration.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-rename-migration.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-wire-answer-whole.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-wire-answer-whole.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-saturn-core.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-saturn-core.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-saturn-adversarial.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-saturn-adversarial.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-saturn-keyless.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-saturn-keyless.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-saturn-fire-plain-frame.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-saturn-fire-plain-frame.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-leak-sweep.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-leak-sweep.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-loop-cadence.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-loop-cadence.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-live-turn-chars.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-live-turn-chars.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-liveness-stamp.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-liveness-stamp.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-seat-live-counter.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-seat-live-counter.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-seat-line-adversarial.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-seat-line-adversarial.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-worker-liveness-identity.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-worker-liveness-identity.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-quit-reaps-the-tree.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-quit-reaps-the-tree.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-daemon-owner-watch-budget.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-daemon-owner-watch-budget.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-owner-handover.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-owner-handover.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-daemon-log-stamps.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-daemon-log-stamps.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-restart-waits-live.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-restart-waits-live.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-daemon-departure.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-daemon-departure.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-compaction-hold.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-compaction-hold.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-credential-change-reaches-runner.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-credential-change-reaches-runner.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-openai-lane-after-relogin.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-openai-lane-after-relogin.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-midturn-line.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-midturn-line.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-dupline-agent-drain.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-dupline-agent-drain.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-dupline-arms.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-dupline-arms.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-dupline-subagent-sleep.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-dupline-subagent-sleep.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-monitor-window-drive.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-monitor-window-drive.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-watch-park-drive.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-watch-park-drive.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-wake-hold-drive.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-wake-hold-drive.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-saturn-window-hold.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-saturn-window-hold.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-no-memory-guard.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-no-memory-guard.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-model-landing-facts.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-model-landing-facts.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-process-sweep.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-process-sweep.ts" "$__t" "$__rc"
__t=$SECONDS; __rc=0; "$bun" run "$here/prove-process-sweep-tables.ts" || { __rc=$?; fail=1; }; prover_mark "$here/prove-process-sweep-tables.ts" "$__t" "$__rc"
echo "############################################################"
if [ "$fail" = "0" ]; then echo "# ✅ ALL DAEMON PROOFS PASS"; else echo "# ❌ SOME DAEMON PROOFS FAILED"; fi
echo "############################################################"
exit "$fail"
