#!/usr/bin/env node
// regen-bridge — assets/unity/bridge/** → src/services/unity/bridgeFiles.generated.ts
// (the regen-addon grammar; `--check` drift-gates the unity-bridge suite).
// The C# package ships INSIDE the single-file bundle as SOURCE — it never
// compiles here (compiles-in-editor is the written Windows-box field
// drill); unity_bridge_install materializes it into a project's Packages/.
// Deterministic: files sorted, digest over the sorted (path, content)
// stream.
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const bridgeRoot = join(repo, 'assets', 'unity', 'bridge')
const outPath = join(repo, 'src', 'services', 'unity', 'bridgeFiles.generated.ts')

function walk(dir) {
  const out = []
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) out.push(...walk(p))
    else out.push(p)
  }
  return out
}

let files
try {
  files = walk(bridgeRoot)
    .map(p => ({ path: relative(bridgeRoot, p).split('\\').join('/'), content: readFileSync(p, 'utf8') }))
    .sort((a, b) => (a.path < b.path ? -1 : 1))
} catch {
  console.error(`regen-bridge: no package sources at ${bridgeRoot}`)
  process.exit(1)
}
if (files.length === 0) {
  console.error('regen-bridge: package dir is empty — nothing to embed')
  process.exit(1)
}

const h = createHash('sha256')
for (const f of files) h.update(f.path).update('\0').update(f.content).update('\0')
const digest = h.digest('hex')

const generated = `// GENERATED by scripts/unity-bridge/regen-bridge.mjs from assets/unity/bridge/ — DO NOT EDIT.
// Regenerate: node scripts/unity-bridge/regen-bridge.mjs   (drift-gated by --check in scripts/unity-bridge/)

export interface UnityBridgeFile {
  /** Path relative to <project>/Packages/com.mercury.unity-bridge/ */
  path: string
  content: string
}

export const UNITY_BRIDGE_DIGEST = '${digest}'

export const UNITY_BRIDGE_FILES: readonly UnityBridgeFile[] = ${JSON.stringify(files, null, 2)}
`

if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(outPath, 'utf8')
  } catch {
    console.error('regen-bridge --check: generated module missing — run the regen')
    process.exit(1)
  }
  if (current !== generated) {
    console.error('regen-bridge --check: DRIFT between assets/unity/bridge/ and bridgeFiles.generated.ts — run: node scripts/unity-bridge/regen-bridge.mjs')
    process.exit(1)
  }
  console.log(`regen-bridge --check: clean (${files.length} files, digest ${digest.slice(0, 12)}…)`)
  process.exit(0)
}

writeFileSync(outPath, generated)
console.log(`regen-bridge: wrote ${outPath} (${files.length} files, digest ${digest.slice(0, 12)}…)`)
