// gen-durable-matrix — render the durable-operation matrix from the typed
// table in src/substrate/durableOperationMatrix.ts (the flag-table pattern:
// untracked derived output — generate → read → never commit).
//
//   bun scripts/reliability/gen-durable-matrix.ts          # write .out copy
//   bun scripts/reliability/gen-durable-matrix.ts --check  # exit 1 if the
//                                                          # .out copy is stale
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  DURABLE_OPERATION_MATRIX,
  FAILURE_CLASSES,
  RESOURCE_BOUNDS,
  STATE_CLASSES,
  type DurableOperationRow,
} from '../../src/substrate/durableOperationMatrix.ts'

const DOC = join(import.meta.dir, '.out', 'DURABLE-OPERATION-MATRIX.md')

const DOMAIN_TITLES: Record<DurableOperationRow['domain'], string> = {
  filestore: 'FileStore kernel',
  teams: 'Teams',
  tasks: 'Tasks',
  mailbox: 'Mailbox',
  runs: 'Autonomous runs',
  daemon: 'Daemon records',
  cron: 'Cron / schedules',
  stores: 'Remaining stores',
  changes: 'Multi-file text change sets',
  lifecycle: 'Lifecycle sweeps',
}

function render(): string {
  const lines: string[] = []
  lines.push('<!-- GENERATED by scripts/reliability/gen-durable-matrix.ts — do not hand-edit.')
  lines.push('     Source of truth: src/substrate/durableOperationMatrix.ts')
  lines.push('     Untracked derived output: generate, read, never commit. -->')
  lines.push('')
  lines.push('# Durable Operation Matrix')
  lines.push('')
  lines.push(
    'Every load-bearing durable operation in Mercury: files touched, lock owner, ' +
      'write order, idempotency key, publication, CURRENT recovery behavior, and the ' +
      'interruption windows an abrupt process exit opens. Rows are updated in place as ' +
      'the durability slices land — this is always the as-built truth, and the pinned ' +
      'failure classes (FC1–FC8) tie rows to the deterministic fixtures in ' +
      '`scripts/reliability/prove-interruption-windows.ts`.',
  )
  lines.push('')
  lines.push('## Failure classes')
  lines.push('')
  for (const fc of FAILURE_CLASSES) lines.push(`- \`${fc}\``)
  lines.push('')
  lines.push('## State classes')
  lines.push('')
  lines.push(
    'Where each row\'s durable TRUTH lives. This axis scopes the single-writer ' +
      'migration (group commit): only `authority` rows hold state a competing writer can ' +
      'silently lose, so only they move onto the durable authority — the other three ' +
      'are the reasons a row does not need to.',
  )
  lines.push('')
  for (const sc of STATE_CLASSES) {
    const n = DURABLE_OPERATION_MATRIX.filter(r => r.stateClass === sc).length
    const migrated = DURABLE_OPERATION_MATRIX.filter(r => r.stateClass === sc && r.migrated).length
    lines.push(`- \`${sc}\` — ${n} row(s)${sc === 'authority' ? `, ${migrated}/${n} migrated` : ''}`)
  }
  lines.push('')
  lines.push(
    '`immutable` carrying no primary row is a finding, not a gap: immutable artefacts ' +
      'exist (the ChangeSet bundle\'s original bytes, ' +
      'content-addressed artifact blobs, snapshots) but only ever as COMPONENTS of a row ' +
      'whose truth lives elsewhere. Naming the class is what makes that checkable.',
  )
  lines.push('')
  const domains = [...new Set(DURABLE_OPERATION_MATRIX.map(r => r.domain))]
  for (const domain of domains) {
    lines.push(`## ${DOMAIN_TITLES[domain]}`)
    lines.push('')
    for (const r of DURABLE_OPERATION_MATRIX.filter(x => x.domain === domain)) {
      lines.push(`### \`${r.id}\` — ${r.operation}`)
      lines.push('')
      lines.push(
        `- **State class:** \`${r.stateClass}\`` +
          (r.authorityArtifact ? ` — truth lives in ${r.authorityArtifact}` : '') +
          (r.migrated ? ' · **migrated to the durable authority**' : ''),
      )
      lines.push(`- **Schema / epoch:** ${r.schemaOrEpoch}`)
      lines.push(`- **Owner key:** ${r.ownerKey}`)
      lines.push(`- **Files (write order):** ${r.files.map(f => `\`${f}\``).join(' → ')}`)
      lines.push(`- **Projections:** ${r.projections.join(' · ') || 'none'}`)
      lines.push(`- **Lock owner:** ${r.lockOwner}`)
      lines.push(`- **Write order:** ${r.writeOrder}`)
      lines.push(`- **Idempotency key:** ${r.idempotencyKey}`)
      lines.push(`- **Publication:** ${r.publication}`)
      lines.push(`- **Recovery (as-built):** ${r.recovery}`)
      lines.push(`- **Interruption windows:**`)
      for (const w of r.interruptionWindows) lines.push(`  - ${w}`)
      lines.push(`- **Failure classes:** ${r.failureClass.map(f => `\`${f}\``).join(', ')}`)
      lines.push(`- **Source:** ${r.source.map(s => `\`${s}\``).join(', ')}`)
      lines.push('')
    }
  }
  lines.push('## Resource bounds')
  lines.push('')
  lines.push(
    'Every long-lived durable structure: writer, ' +
      'declared bound, the reaper enforcing it, what a reap preserves, and the proof that ' +
      'exercises the boundary. A bound in a comment is not evidence — these rows are.',
  )
  lines.push('')
  lines.push('| Structure | Writer | Bound | Reaper | Preserves | Proof |')
  lines.push('|---|---|---|---|---|---|')
  for (const r of RESOURCE_BOUNDS) {
    lines.push(
      `| \`${r.id}\` — ${r.structure} | ${r.writer} | ${r.bound} | ${r.reaper} | ${r.preserves} | \`${r.proof}\` |`,
    )
  }
  lines.push('')
  return lines.join('\n')
}

const doc = render()
if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(DOC, 'utf8')
  } catch {
    console.error('❌ rendered durable-operation matrix missing — run gen-durable-matrix.ts')
    process.exit(1)
  }
  if (current !== doc) {
    console.error('❌ rendered durable-operation matrix is stale — regenerate: bun scripts/reliability/gen-durable-matrix.ts')
    process.exit(1)
  }
  console.log('✅ rendered durable-operation matrix matches the table')
} else {
  mkdirSync(join(import.meta.dir, '.out'), { recursive: true })
  writeFileSync(DOC, doc)
  console.log(`wrote ${DOC}`)
}
