#!/usr/bin/env bun
import React from 'react'
import { tally, usagePlanWorld } from './lib/usage-plan-world.ts'

const { check, finish } = tally()
const world = await usagePlanWorld()
try {
  const { owner, reader, fresh, quota, ink } = world
  const { HelmTelemetryRail } = await import(world.path('src/components/HelmTelemetryRail.tsx'))
  const { railPlanAt } = await import(world.path('src/utils/helmGeometry.ts'))
  const width = railPlanAt(178, true).telemetryW
  const card = () => React.createElement(ink.Box, { flexDirection: 'row', justifyContent: 'flex-end', width: 178 }, React.createElement(HelmTelemetryRail, { width, availRows: 44 }))
  const board = await world.mount(card())
  const kimi = owner.usageForProvider('moonshot')
  const glm = owner.usageForProvider('zai')
  console.log(`Kimi owner: ${JSON.stringify(kimi.windows)}`)
  console.log(`Z.AI owner: ${JSON.stringify(glm.windows)}`)
  const metered = kimi.windows.filter(w => w.usedPct !== undefined)
  check('loopback /usages was read once and the GLM quota path once, with no other request', world.requests.length === 2 && world.requests.includes('GET /coding/v1/usages') && world.requests.includes('GET /api/monitor/usage/quota/limit'), JSON.stringify(world.requests))
  check('Kimi views have the stated 5h and 7d order, percentages and resets', metered.map(w => `${w.label}:${w.usedPct}`).join('|') === '5h:50|7d:25' && metered[0]?.resetsAtMs === world.resetAtMs && metered[1]?.resetsAtMs === world.resetAtMs + 7 * 86_400_000, JSON.stringify(metered))
  check('Kimi views come from the one observed decoder, not a surface copy', JSON.stringify(kimi.windows) === JSON.stringify(owner.kimiManagedWindowViews(reader.kimiObservedManagedUsage())))
  const composed = owner.windowSourceUsages({ model: 'glm-fixture' })
  check('the GLM-focused card carries the same Kimi window views', composed.primary.provider === 'zai' && JSON.stringify(composed.others.find(u => u.provider === 'moonshot')?.windows) === JSON.stringify(kimi.windows))
  const frame = board.frame()
  world.save('usage-card', frame)
  check('the card paints actual Kimi 5h and 7d mini-bars, not text percentages alone', /5h [█░]{4} 50%/.test(frame) && /7d [█░]{4} 25%/.test(frame), frame)
  check('the card carries each provider-stated absolute reset', metered.every(w => board.runs().some(run => run.includes(`resets ${quota.formatClock(w.resetsAtMs!)}`))), board.runs().join(' | '))
  check('the card uses the shared freshness words without truncating them', metered.every(w => frame.includes(fresh.usageAgeWords(w, world.now())!)), frame)
  check('the Z.AI owner reads the GLM Coding Plan windows the fixture stated (5h 17%, 7d 3%) with no absence sentence', glm.shape === 'subscription-windows' && glm.windows.map(w => `${w.label}:${w.usedPct}`).join('|') === '5h:17|7d:3' && glm.absence === undefined, JSON.stringify({ shape: glm.shape, windows: glm.windows, absence: glm.absence }))
  const compact = (value: string) => value.replace(/\s/g, '')
  const painted = compact(board.runs().join(''))
  check('the GLM block paints its own 5h and 7d mini-bars beside the Kimi pair, under its plan label', /5h [█░]{4} 17%/.test(frame) && /7d [█░]{4} 3%/.test(frame) && painted.includes(compact('GLM Coding Plan usage')), board.runs().join(' | '))
  check('GLM has exactly the two stated credit windows, no pool, no balance, the tool-call figure, and no binding on a per-provider read', glm.windows.length === 2 && glm.pools.length === 0 && glm.balance === undefined && glm.figures?.length === 1 && glm.binding === undefined, JSON.stringify(glm.figures))
  check('the source-rendered sidebar stays inside 178x51 without render errors', world.inBounds(frame) && !frame.includes('RENDER ERROR'))
  const requestsBefore = world.requests.length
  await owner.refreshProviderUsage('zai', { fetchImpl: world.fetchImpl, force: true })
  check('a forced GLM refresh sends exactly one quota request, the key raw', world.requests.length === requestsBefore + 1 && world.requests.at(-1) === 'GET /api/monitor/usage/quota/limit' && world.quotaAuthForms.every(form => form === 'raw'), JSON.stringify(world.quotaAuthForms))

  world.focus('moonshot')
  await board.repaint(card())
  check('a Kimi-focused card paints the same pair', /5h [█░]{4} 50%/.test(board.frame()) && /7d [█░]{4} 25%/.test(board.frame()))
  world.save('usage-card-kimi-focused', board.frame())
  world.setNow(world.observedAtMs + fresh.usageStaleAfterMs() + 60_000)
  await board.repaint(card())
  check('a stale observation keeps its bars and says stale in the one vocabulary', /5h [█░]{4} 50%/.test(board.frame()) && compact(board.runs().join('')).includes(compact(fresh.usageAgeWords(metered[0]!, world.now())!)), board.frame())
  world.save('usage-card-stale', board.frame())
  world.refuse(true)
  await owner.refreshProviderUsage('moonshot', { fetchImpl: world.fetchImpl, now: world.now, force: true })
  check('a failed read retains the last observation with its old stamp', owner.usageForProvider('moonshot').windows[0]?.observedAtMs === world.observedAtMs)
  world.refuse(false)
  const before = world.records.getUsageRecordVersion()
  world.setBody({ limits: [{ ...world.fiveHour, detail: { ...world.fiveHour.detail, used: '70' } }] })
  await owner.refreshProviderUsage('moonshot', { fetchImpl: world.fetchImpl, now: world.now, force: true })
  await world.settle()
  check('a fresh Kimi answer wakes the subscribed sidebar immediately', world.records.getUsageRecordVersion() > before && /5h [█░]{4} 70%/.test(board.frame()), board.frame())
  check('a weekly window the next reply omits disappears, never a fabricated 0% (the GLM 7d row beside it stays its own)', !/7d [█░]{4} 25%/.test(board.frame()) && !/7d [█░]{4} 0%/.test(board.frame()) && owner.usageForProvider('moonshot').windows.length === 1, board.frame())
  const quotaOnly = reader.decodeKimiManagedUsage({ usage: { used: '1', limit: '10' } }, world.now())
  check('an overall quota with no duration never becomes an invented week', owner.kimiManagedWindowViews(quotaOnly ?? null).map(w => w.label).join('|') === 'quota')
  const malformed = reader.decodeKimiManagedUsage({ limits: [{ window: { duration: 7, timeUnit: 'TIME_UNIT_DAY' }, detail: { used: null, limit: '100' } }] }, world.now())
  check('an unreadable weekly figure is absent, never zero', malformed === undefined)
  check('no fixture request escaped loopback', world.escaped.length === 0, JSON.stringify(world.escaped))
  board.close()
} finally {
  world.close()
}
finish()
