#!/usr/bin/env bun
// ============================================================================
//  scripts/ui/lib/gen-emoji-properties.ts — regenerate the vendored
//  Emoji-property table (scripts/ui/lib/emojiProperties.ts) from a local copy
//  of Unicode's emoji-data.txt (UTS #51; the canonical file lives at
//  https://unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt).
//
//  The table is what the paint census (prove-no-emoji-presentation.ts) reads:
//  a terminal that routes emoji-eligible code points to its colour font
//  (Windows Terminal) paints every Emoji=Yes code point as a pictograph, and
//  every Emoji_Presentation=Yes code point as one regardless of any selector.
//  Neither the prover nor the product ever fetches the data — this generator
//  is the one place the file is read, offline, by hand, and the output is
//  committed. The header of the generated module names the Unicode version
//  the data carries so a stale table is visible at a glance.
//
//    ~/.bun/bin/bun scripts/ui/lib/gen-emoji-properties.ts <path/to/emoji-data.txt>
// ============================================================================
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const source = process.argv[2]
if (!source) {
  console.error('usage: bun scripts/ui/lib/gen-emoji-properties.ts <path/to/emoji-data.txt>')
  process.exit(2)
}

const text = readFileSync(source, 'utf8')
const versionLine = /^# Version: (\S+)/m.exec(text)
if (!versionLine) {
  console.error('the file carries no "# Version:" header line — is this emoji-data.txt?')
  process.exit(2)
}
const version = versionLine[1]!

type Range = [number, number]
const byProperty = new Map<string, Range[]>()
for (const raw of text.split('\n')) {
  const line = raw.split('#')[0]!.trim()
  if (line === '') continue
  const [codepoints, property] = line.split(';').map(part => part.trim())
  if (!codepoints || !property) continue
  const [lo, hi] = codepoints.includes('..')
    ? (codepoints.split('..').map(h => parseInt(h, 16)) as Range)
    : [parseInt(codepoints, 16), parseInt(codepoints, 16)]
  const list = byProperty.get(property) ?? []
  list.push([lo!, hi!])
  byProperty.set(property, list)
}

/** Sort and merge touching/overlapping ranges so the table is canonical. */
function canonical(ranges: Range[]): Range[] {
  const sorted = [...ranges].sort((a, b) => a[0] - b[0])
  const out: Range[] = []
  for (const [lo, hi] of sorted) {
    const last = out[out.length - 1]
    if (last && lo <= last[1] + 1) last[1] = Math.max(last[1], hi)
    else out.push([lo, hi])
  }
  return out
}

const emoji = canonical(byProperty.get('Emoji') ?? [])
const presentation = canonical(byProperty.get('Emoji_Presentation') ?? [])
if (emoji.length === 0 || presentation.length === 0) {
  console.error('no Emoji / Emoji_Presentation rows found')
  process.exit(2)
}
const count = (ranges: Range[]): number => ranges.reduce((n, [lo, hi]) => n + (hi - lo + 1), 0)
const hex = (cp: number): string => '0x' + cp.toString(16).toUpperCase().padStart(4, '0')
const rows = (ranges: Range[]): string => {
  const cells = ranges.map(([lo, hi]) => `[${hex(lo)}, ${hex(hi)}]`)
  const lines: string[] = []
  for (let i = 0; i < cells.length; i += 6) lines.push('  ' + cells.slice(i, i + 6).join(', ') + ',')
  return lines.join('\n')
}

const out = `// ============================================================================
//  scripts/ui/lib/emojiProperties.ts — GENERATED by gen-emoji-properties.ts
//  from Unicode emoji-data.txt (UTS #51), Unicode version ${version}.
//  Do not hand-edit: re-run the generator against a newer emoji-data.txt.
//
//  Emoji=Yes           ${count(emoji)} code points in ${emoji.length} ranges — a terminal whose
//                      font fallback prefers its colour font paints these as
//                      pictographs unless the glyph reads as text to it.
//  Emoji_Presentation  ${count(presentation)} code points in ${presentation.length} ranges — emoji by
//                      default everywhere; no selector makes them text.
// ============================================================================

export const EMOJI_DATA_UNICODE_VERSION = '${version}'

/** VARIATION SELECTOR-15: requests text presentation for the preceding glyph. */
export const TEXT_PRESENTATION_SELECTOR = 0xfe0e
/** VARIATION SELECTOR-16: requests emoji presentation for the preceding glyph. */
export const EMOJI_PRESENTATION_SELECTOR = 0xfe0f

/** Inclusive [lo, hi] ranges, sorted, non-overlapping: Emoji=Yes. */
export const EMOJI_RANGES: ReadonlyArray<readonly [number, number]> = [
${rows(emoji)}
]

/** Inclusive [lo, hi] ranges, sorted, non-overlapping: Emoji_Presentation=Yes. */
export const EMOJI_PRESENTATION_RANGES: ReadonlyArray<readonly [number, number]> = [
${rows(presentation)}
]

function inRanges(ranges: ReadonlyArray<readonly [number, number]>, codePoint: number): boolean {
  let lo = 0
  let hi = ranges.length - 1
  while (lo <= hi) {
    const mid = (lo + hi) >> 1
    const [from, to] = ranges[mid]!
    if (codePoint < from) hi = mid - 1
    else if (codePoint > to) lo = mid + 1
    else return true
  }
  return false
}

/** True when the code point carries the Unicode Emoji property. */
export function hasEmojiProperty(codePoint: number): boolean {
  return inRanges(EMOJI_RANGES, codePoint)
}

/** True when the code point carries the Unicode Emoji_Presentation property. */
export function hasEmojiPresentation(codePoint: number): boolean {
  return inRanges(EMOJI_PRESENTATION_RANGES, codePoint)
}
`

const target = join(dirname(fileURLToPath(import.meta.url)), 'emojiProperties.ts')
writeFileSync(target, out)
console.log(`wrote ${target}: Unicode ${version}, Emoji ${count(emoji)} cps / ${emoji.length} ranges, Emoji_Presentation ${count(presentation)} cps / ${presentation.length} ranges`)
