#!/usr/bin/env bun

import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const repoRoot = resolve(import.meta.dir, '..', '..')
const dist = join(repoRoot, 'dist', 'mercury.mjs')
const outDir = join(repoRoot, 'assets', 'completions')

if (!existsSync(dist)) {
  console.error('dist/mercury.mjs missing — run `bun run build.ts` first (completions derive from the BUILT registry)')
  process.exit(1)
}

function helpOf(args: string[]): string {
  try {
    return execFileSync((process.execPath.includes('bun') ? 'node' : process.execPath), [dist, ...args, '--help'], {
      encoding: 'utf8',
      timeout: 60_000,
      env: { ...process.env },
    })
  } catch (e) {
    return String((e as { stdout?: string }).stdout ?? '')
  }
}

const rootHelp = helpOf([])

function parseLongOptions(help: string): string[] {
  const opts = new Set<string>()
  for (const m of help.matchAll(/(?:^|[\s,])(--[a-zA-Z][\w-]*)/gm)) {
    opts.add(m[1]!)
  }
  return [...opts].sort()
}

function parseSubcommands(help: string): string[] {
  const section = help.split(/^Commands:$/m)[1]
  if (!section) return []
  const names = new Set<string>()
  for (const line of section.split('\n')) {
    const m = line.match(/^ {2}([a-z][\w|-]*)/)
    if (!m) continue
    for (const name of m[1]!.split('|')) names.add(name)
  }
  return [...names].sort()
}

const rootOptions = parseLongOptions(rootHelp)
const subcommands = parseSubcommands(rootHelp)
const SIDE_EFFECTFUL_SUBS = new Set(['daemon'])
const subOptions: Record<string, string[]> = {}
for (const sub of subcommands) {
  subOptions[sub] = SIDE_EFFECTFUL_SUBS.has(sub) ? [] : parseLongOptions(helpOf([sub]))
}

const banner = `# GENERATED by scripts/project-services/gen-completions.ts from the BUILT CLI's
# live command registry — do not hand-edit; regenerate after CLI changes
# (the prove-completions-current.ts gate enforces this).`

const bash = `${banner}
_mercury_completions() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[1]}"
  local subcommands="${subcommands.join(' ')}"
  local root_opts="${rootOptions.join(' ')}"
  case "\$prev" in
${subcommands
  .map(
    s => `    ${s})
      COMPREPLY=( $(compgen -W "${(subOptions[s] ?? []).join(' ')}" -- "\$cur") )
      return 0
      ;;`,
  )
  .join('\n')}
  esac
  if [[ "\$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "\$root_opts" -- "\$cur") )
  else
    COMPREPLY=( $(compgen -W "\$subcommands" -- "\$cur") )
  fi
  return 0
}
complete -F _mercury_completions mercury
`

const zsh = `#compdef mercury
${banner}
_mercury() {
  local -a subcommands root_opts
  subcommands=(${subcommands.map(s => `'${s}'`).join(' ')})
  root_opts=(${rootOptions.map(o => `'${o}'`).join(' ')})
  if (( CURRENT == 2 )); then
    _describe 'mercury command' subcommands
    compadd -- \${root_opts[@]}
    return
  fi
  case "\${words[2]}" in
${subcommands
  .map(
    s => `    ${s})
      compadd -- ${(subOptions[s] ?? []).map(o => `'${o}'`).join(' ')}
      ;;`,
  )
  .join('\n')}
    *)
      compadd -- \${root_opts[@]}
      ;;
  esac
}
_mercury "\$@"
`

const fishLines: string[] = [banner]
for (const s of subcommands) {
  fishLines.push(
    `complete -c mercury -n "not __fish_seen_subcommand_from ${subcommands.join(' ')}" -a "${s}"`,
  )
  for (const o of subOptions[s] ?? []) {
    fishLines.push(
      `complete -c mercury -n "__fish_seen_subcommand_from ${s}" -l "${o.slice(2)}"`,
    )
  }
}
for (const o of rootOptions) {
  fishLines.push(
    `complete -c mercury -n "not __fish_seen_subcommand_from ${subcommands.join(' ')}" -l "${o.slice(2)}"`,
  )
}
const fish = fishLines.join('\n') + '\n'

const files: Record<string, string> = {
  'mercury.bash': bash,
  _mercury: zsh,
  'mercury.fish': fish,
}

if (process.argv.includes('--check')) {
  let drift = 0
  for (const [name, content] of Object.entries(files)) {
    const path = join(outDir, name)
    const committed = existsSync(path) ? readFileSync(path, 'utf8') : null
    if (committed !== content) {
      drift++
      console.log(`DRIFT: assets/completions/${name} does not match the live registry — regenerate (bun run scripts/project-services/gen-completions.ts)`)
    } else {
      console.log(`PASS: assets/completions/${name} matches the live registry (${subcommands.length} subcommands, ${rootOptions.length} root options)`)
    }
  }
  process.exit(drift > 0 ? 1 : 0)
}

mkdirSync(outDir, { recursive: true })
for (const [name, content] of Object.entries(files)) {
  writeFileSync(join(outDir, name), content)
  console.log(`wrote assets/completions/${name}`)
}
console.log(`(${subcommands.length} subcommands · ${rootOptions.length} root options · from ${dist})`)
